### ISSUE TITLE
Notification Email missing Team name

### ISSUE THREAD

**Issue by Cyrille37** [mattermost/mattermost-server#10020]
#### Summary
The Notification Email does not containt the "Team" name.

#### Steps to reproduce

1. Do something that throw a notification email.
2. The received notification email contains the "Channel" name and the "User" name, but not mention of the "Team" name.

#### Expected behavior

That there is a "Team" name reference somewhere in the email body or in the email subject.

#### Possible fixes

Add a "Team" name reference, like the title of a thread can be "Team / Channel".

**Comment by jasonblais** [comment]
Hey @Cyrille37, do you know if email batching is enabled on your system? If you're a System Admin, you can find this in **System Console > Email > Enable Email Batching**.

Also, which Mattermost server version do you have? You can find this via the Mattermost main menu next to your user profile (in top left corner), then About Mattermost, then Mattermost Version.

**Comment by Cyrille37** [comment]
Hello @jasonblais 
The server is a "Mattermost 5.4.0" at https://framateam.org.
Do you mean that email batching have email template that can be customized to add the "Team" name ?

**Comment by jasonblais** [comment]
Thanks @Cyrille37 for following up! 

Email batching refers to grouping notifications together and sending them (for instance) every 15 minutes, rather than sending a separate email notification for every message.

You can find out if email batching is enabled in **System Console > Email > Enable Email Batching**, or ask your System Administrator to help check that for you.

**Comment by Cyrille37** [comment]
Thanks a lot for explanations.
Cheers.
