### ISSUE TITLE
[MM-9494] If the keyboard is open, swiping down past it should close it

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10161]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9494)

This ticket should be done on the mattermost-mobile repository: https://github.com/mattermost/mattermost-mobile

------

Note this is for iOS only.

Repro: 
1. Click into the texbox to open the keyboard
2. Swipe down to scroll the channel, extending over top of the text input box

Observed: Keyboard stays open

Expected: 
Keyboard should close if the swipe action goes overtop the text input box. Do not close the keyboard if the swipe action is only on the channel, and not over the keyboard. See iMessages or Messenger as examples.

[See iMessage, FB messenger, most other apps for example]

**Comment by courtneypattison** [comment]
I'll give it a go :)

**Comment by hanzei** [comment]
Great, thanks @courtneypattison! Let us know, if you have any questions.

**Comment by courtneypattison** [comment]
After looking into this issue for a couple of weeks, I haven't found a way to implement it. There's a [an example](https://github.com/facebook/react-native/blob/master/RNTester/js/InputAccessoryViewExample.js) in the React Native repo that is very close to this functionality, but it is not keyboard avoiding. I contacted the author of the example to ask if he knew how to make it keyboard avoiding and he gave me some [code](https://gist.github.com/PeteTheHeat/b0ca2b3a82c06d11d43d2ebcea9dd1c8) he couldn't get working cleanly. I've got [the code](https://snack.expo.io/@courtneypattison/interactive-keyboard-avoiding-scroll-view) working for phones before iPhoneX, but InputAccessoryView is pretty buggy. My next thought is to wrap the post list and post text box in a ScrollView that has the interactive keyboard dismiss mode and then use the keyboard listeners from [this example](https://snack.expo.io/@courtneypattison/interactive-keyboard-avoiding-scroll-view), but I'm not sure if that makes sense or is possible. Any suggestions would be amazing. This issue is driving me crazy!

**Comment by hanzei** [comment]
@enahum Do you have feedback on the thoughts from @courtneypattison above?

**Comment by enahum** [comment]
We were looking at AccessoryView and there is a library from wix to accomplish the same result but none of them were helpful at the time.

Perhaps building a native module is the way to go, haven’t looked into this for almost a year, so no idea what options are out there

**Comment by enahum** [comment]
I'm taking care of this one.
