### ISSUE TITLE
Isolate unit tests for selectors and make them more thorough

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10200]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13693)

The unit tests for many of the selectors in the mattermost-redux repo share state which makes them difficult to test in isolation. Notably, the tests for channel-related selectors has almost 180 lines of setup code to construct the state used for all of the tests. Since these tests aren't very well isolated, they're mostly only testing a single code path when some of them are very complicated, so splitting them out would also make it so we can test them thoroughly.

**Comment by larkox** [comment]
May I take this one?

**Comment by larkox** [comment]
I created a draft for this task, since it will take some time, and I want to make sure I am doing what it is expected from the beginning.
At the time I am writing this post, I have extracted two functions: getMyChannels and getChannelsInCurrentTeam. It would be great if someone from the team could take a look to the draft and confirm me I am on the right track.
Thanks!
