### ISSUE TITLE
Android and iOS App resets E-Mail settings

### ISSUE THREAD

**Issue by eStudyMedien** [mattermost/mattermost-server#10321]
#### Summary
Andoid App V1.16.0 Build 175 (iOS-App on iPhone X too) on Mattermost-Server 5.8.0: 
Profil -> Einstellungen -> Benachrichtigungen -> E-Mail 
If you enter this menu in the app (also without saving), your E-Mail settings are set to default "15 Minutes"
This is online shown in the Desktop-App or browser; not in the Android App. The Android App still shows you "Nie"

**Comment by amyblais** [comment]
Hi @eStudyMedien,

Are these the reproduction steps?
1. Set email notifications to "immediately" on the desktop app and keep the Notification setting modal open on the desktop app.
2. Change the email notification setting on mobile app to "Never".

Is this the Observed?
The Notification Setting on Desktop changes to "After 15 minutes" instead of "Never". However, this seems to just be a temporary issue in the UI - if you close the settings modal and reopen it, the setting correctly shows "Never".

We have a ticket here that sounds like could be the issue you're experiencing: https://mattermost.atlassian.net/browse/MM-14013.

**Comment by eStudyMedien** [comment]
Hi,

this is what we do and how Mattermost acts:

Step 1 – Desktop App
[cid:image002.jpg@01D4C923.A48365A0]
Mattermost works how it should; no E-Mails.


Step 2 – Mobile App (Android and iOS)
If you only enter the Menu „E-Mail“ in the Mobile App and then leave the Menu ...
[cid:image002.jpg@01D4C9CA.622B7920]


Step 3 – Desktop App
... the settings are (re-)set to „15 Minutes“
[cid:image001.jpg@01D4C9C9.BDCB8C30]


That’s the problem.

Kind regards
Björn Nilson


Von: amyblais <notifications@github.com>
Antworten an: mattermost/mattermost-server <reply@reply.github.com>
Datum: Donnerstag, 21. Februar 2019 um 01:48
An: mattermost/mattermost-server <mattermost-server@noreply.github.com>
Cc: "Support, eStudy" <estudy@hs-duesseldorf.de>, Mention <mention@noreply.github.com>
Betreff: Re: [mattermost/mattermost-server] Android and iOS App resets E-Mail settings (#10321)


Hi @eStudyMedien<https://github.com/eStudyMedien>,

Are these the reproduction steps?

  1.  Set email notifications to "immediately" on the desktop app and keep the Notification setting modal open on the desktop app.
  2.  Change the email notification setting on mobile app to "Never".

Is this the Observed?
The Notification Setting on Desktop changes to "After 15 minutes" instead of "Never". However, this seems to just be a temporary issue in the UI - if you close the settings modal and reopen it, the setting correctly shows "Never".

We have a ticket here that sounds like could be the issue you're experiencing: https://mattermost.atlassian.net/browse/MM-14013.

**Comment by amyblais** [comment]
Thank you, I was able to reproduce this and opened a ticket here: https://mattermost.atlassian.net/browse/MM-14301.

**Comment by amyblais** [comment]
Closing this as this has been fixed for v5.9 release (to be released on March 16th).
