### ISSUE TITLE
[Help Wanted] [MM-13824] Add a translation string to address an issue with a German translation

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10335]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13824)

*Context:*

*Translation key: api.team.join_team.post_and_forget*

Unit: http://translate.mattermost.com/de/mattermost/translate/platform.po#unit=544502

Source: "%v joined the team".

Current German translation: "%v ist dem Team beigetreten" for "[User] joined the Team". However, if it is "You joined the team", the translation should be "Sie sind dem Team beigetreten".

The translation to German is dependent on the content of the %v variable. The server should treat them differently and have two strings - one for a 3rd person and another in 1st person.

**Comment by joshuabezaleel** [comment]
Hey @esethna , I am new to this translation aspect of the Mattermost. If I may ask, which file/code should I take a look into to make a change on this? 
And does this mean that I need to check the %v whether it's the signed in user or not? 

Thank you very much. Have a nice day :slightly_smiling_face:

**Comment by hanzei** [comment]
@hmhealey could you please take a look at the questions above?

**Comment by hmhealey** [comment]
@joshuabezaleel You'll need to change this on the web app. If you take a look [here](https://github.com/mattermost/mattermost-webapp/blob/master/components/post_markdown/system_message_helpers.jsx#L89), this is where it uses the existing string. You'll need to add a new translation string to go along with `api.team.join_team.post_and_forget`, and then we'll need to figure out how to tell that function that the message refers to the current user. Perhaps we could pass in the current user ID and compare that against the post props since I think that should include the ID of the user that joined.

I'd also note that the server also has a version of this string that will continue to be incorrect, but we can't do anything about that one since the same message is displayed to all users for it.

**Comment by MartB** [comment]
Where does the "You" even come from, its supposed to be an username in that string and not a You, so this has basically nothing to do with the server but with the improper handling in the webapp. Am i missing something? 

Isnt this the place where stuff goes wrong?
https://github.com/mattermost/mattermost-webapp/blob/master/components/post_view/combined_system_message/__snapshots__/combined_system_message.test.jsx.snap
