### ISSUE TITLE
Improve emoji picker performance

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10346]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12752)

See https://mattermost.atlassian.net/browse/MM-12395 for more details, but the emoji picker is slow again with no specific point of regression causing the problem.

Looking at the performance flame charts, it seems like we're doing a lot of unnecessary work on scrolling: each emoji takes about 100 microseconds to evaluate its render function, and with ~10,000 of them, we're spending ~1s just trying to change the scroll focus for the sections. This can probably be reworked to avoid the re-render pass at that level.

For this ticket, investigate ways to improve the performance of the emoji picker on the web app through either the above suggestion or some other method.

If you have any questions or want to discuss the ticket, feel free to ask `@sudheerdev` or `@harrison` in the ~Developers: Performance channel on community.mattermost.com

**Comment by eshyong** [comment]
Hi, I'd be interested in working on this ticket. I just cloned the repo and followed these directions. Is there anything else I need to do to get started?

**Comment by eshyong** [comment]
It looks like this is filed in the `mattermost-server` repo, but I assume I should be looking at the frontend repo – probably [desktop](https://github.com/mattermost/desktop) or [web](https://github.com/mattermost/mattermost-webapp)?

**Comment by cpoile** [comment]
@eshyong Definitely in the webapp repo, possibly in desktop and mobile too (if they use different code -- unsure about that). 

I think many tickets are consolidated into the mattermost-server repo to keep it all in one place. That's why you're finding it here.

Hope that helps!

**Comment by hanzei** [comment]
Hey @eshyong,

Do the answers above solve your question?

**Comment by eshyong** [comment]
@hanzei yes, sorry I haven't made much progress on this issue, and others have suggested that I take on smaller tasks to start with. You can reopen this to others, since I probably won't be working on this anytime soon.

**Comment by cometkim** [comment]
I'll take this :)

**Comment by cometkim** [comment]
There are definitely unnecessary renderings.

When

1. Move cursor without scrolling:
    EmojiPicker did render because of the `state.cursor` changed.x
    
    ![image](https://user-images.githubusercontent.com/9696352/60381040-6e1b7100-9a89-11e9-88d4-2b35cb2ae97b.png)

2. Scroll (same as jump to category):
    EmojiPicker did render because of the `state.divTopOffset` changed.
  
    ![image](https://user-images.githubusercontent.com/9696352/60381062-bd61a180-9a89-11e9-86e4-1ec931cc9757.png)

EmojiPickerCategorySection renders unnecessarily because children ref is always created even each child is not updated. About ~60% of the rendering could be avoidable but is still heavy.

It's still rendering too many items at VDOM and DOM. It can be optimized by fixed-size virtualized list just like Slack do.

![image](https://user-images.githubusercontent.com/9696352/60381203-e3884100-9a8b-11e9-8cdd-1ec08433115c.png)

Maybe re-inventing EmojiPicker components is much easier and efficient way than making a patch.

**Comment by cometkim** [comment]
Will file a PR soon.

**Comment by jespino** [comment]
@cometkim I took a look on this part some time ago, and I think if we restructure a bit the code, we can use react-window or something similar to only render the emojis visible there, is super easy to know where to cut because the emojis always have the same size there.

**Comment by cometkim** [comment]
@jespino Yeah agreed that. I think to clean up legacy codes is the first thing to do. eg, to migrate emoji related actions/selectors to mattermost-redux.

**Comment by jespino** [comment]
@cometkim We have in one hour and a half a meeting about the future of mattermost-redux, because probably for support multiserver in mobile we will need something more memory efficient than redux, so I don't discard that we end up moving the redux part again inside of mattermost-webapp, I'm not sure if that movement now makes sense. If you want to join to the meeting will be here: https://mattermost.zoom.us/j/4985210732

**Comment by cometkim** [comment]
@jespino Ok. I understood the point. I'll join the meeting but probably only chat.

**Comment by hanzei** [comment]
@cometkim Just want to check what the status of this issue is

**Comment by cometkim** [comment]
@hanzei I have suspended it because I don't have enough mana.

Introduction of TypeScript and Hooks is really good news to me it is the way I'm used to it. I'll make a PR that completely rewrites the codebase around of EmojiPicker.

Just started here -> https://github.com/mattermost/mattermost-webapp/pull/3648.

**Comment by hanzei** [comment]
Nice, thanks @cometkim :tada:

**Comment by esethna** [comment]
Closing based on this comment: https://github.com/mattermost/mattermost-webapp/pull/3648#issuecomment-650776195
