### ISSUE TITLE
[Help Wanted] [MM-14833] No option to deactivate BOT account from System>> Users

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#10543]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-14833)

When viewing BOT accounts in Users>> Admin there is no Deactivate option

There should be an option to disable / deactivate BOT accounts when viewing them from the list of users but the option is missing.

Steps:
- Create a BOT
- Ensure the BOT is active 
- Go to System Console >> Users and locate the BOT
- Click on the Role drop-down
*Expected*: The BOT account has a disable/deactivate option (not sure which)
*Observed*: The BOT account does not have a disable/deactivate option

**Comment by CooperAtive** [comment]
I'll take this

**Comment by jasonblais** [comment]
A bot isn't a real user, so as an administrator I wouldn't actually expect bots to appear in a list of system users. As a result, I'm leaning towards hiding bots from System Console > Users list, instead of allowing one to disable bots on this page.

Instead, we'll hide bots from System Console > Users. https://github.com/mattermost/mattermost-server/issues/10596
