### ISSUE TITLE
[Edge] Cannot upload screenshot image using Ctrl + V

### ISSUE THREAD

**Issue by maruTA-bis5** [mattermost/mattermost-server#10862]
#### Summary
Edge users cannot upload the screenshot image using `Ctrl + V`.

#### Steps to reproduce
1. Press `Print Screen` or `Alt + Print Screen` to take screenshot to clipboard.
2. Focus to post box.
3. Press `Ctrl + V` to upload screenshot image.

Reproduced in 5.10.0 EE (without license), community.mattermost.com, commuity-daily.mattermost.com.

#### Expected behavior
Screenshot image file will upload.

#### Observed behavior (that appears unintentional) 
Below error was reported in console.
```
0: Function expected
file_upload.jsx (506,155)
```
![image](https://user-images.githubusercontent.com/1310661/57921492-71dba580-78d8-11e9-8c49-2944e6597818.png)

Other browsers (Firefox, Chrome, DesktopApp) are no problem.

**Comment by amyblais** [comment]
Hi @maruTA-bis5, I believe the shortcut for uploading an image is ``Ctrl + U``, let me know if I've misunderstood anything?

**Comment by steevsachs** [comment]
The issue here is that Edge does not support the `File` constructor (https://developer.mozilla.org/en-US/docs/Web/API/File), used in `file_upload.jsx` on line 508: https://github.com/mattermost/mattermost-webapp/blob/master/components/file_upload/file_upload.jsx#L508

This same issue occurs in IE, which may be more of an issue since Edge is moving to Chromium and the full File API should then be supported.

I'd be happy to take a stab at a workaround when the File constructor is not supported if a fix seems valuable.

**Comment by amyblais** [comment]
Hi @steevsachs, thank you, and that would be great if you are open to submitting a fix for this issue. Please let us know if you have any questions on how to get started.

**Comment by steevsachs** [comment]
Sure thing, I’ll give it a go!

**Comment by steevsachs** [comment]
@amyblais PR opened. Pinging you here because I'm not sure how this gets assigned internally :)

**Comment by amyblais** [comment]
Thank you! Opened a Jira ticket for reference: https://mattermost.atlassian.net/browse/MM-15916.
