### ISSUE TITLE
Posting links ending in _ (underscore)

### ISSUE THREAD

**Issue by normoes** [mattermost/mattermost-server#11247]
#### Summary
Posting links ending in `_` (underscore) excludes the `_` (underscore) from the actual link.

This happens in the desktop application as well as in the web application.

#### Steps to reproduce
Post the link https://example.com/_ in a mattermost channel.

#### Expected behavior
Clicking the link opens https://example.com/_.

A mouseover highlights https://example.com/_ (the complete link).

#### Observed behavior (that appears unintentional) 
Clicking the link opens https://example.com/ instead of https://example.com/_.

A mouseover highlights https://example.com/ instead of https://example.com/_.

#### Possible fixes
Sorry, no idea.

**Comment by normoes** [comment]
Seems like github has the same problem ;)

**Comment by amyblais** [comment]
Hi @normoes, we used to have a ticket for this but it was closed by the development team as "Won't fix" because currently this follows GitHub markdown standard and a special case for this would add complexity for limited value: https://mattermost.atlassian.net/browse/MM-13990.

I'll close this issue for now, please feel free to share this on our feature request forum here: https://mattermost.uservoice.com/forums/306457-general.
