### ISSUE TITLE
Implement http.Hijacker for plugins' ServeHTTP

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11288]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-16473)

As per [this conversation](https://community.mattermost.com/core/pl/8hg5kh5xe78w7rtmtk9bzc13eo), it seems not to be possible to upgrade the `ServeHTTP` hook to expose a websocket connection likely because `httpResponseWriterRPCServer` doesn't implement `http.Hijacker`.

In theory, this should be a straightforward proxy to the `http.Response` object within, but more experimentation is required.

**Comment by lieut-data** [comment]
The changes here are technically easy -- if they work as theorized -- but the hard part will be writing a good set of unit tests to exercise websockets sufficiently to be certain of the implementation.

**Comment by manland** [comment]
I will give it a try ;)

**Comment by manland** [comment]
So after 2 * 3 hours on this problem I think it's not possible 1/5 :sweat: 

This is what i understand : 

Client --HTTP (ws)--> MM --GRPC--> Plugin

When MM give the request to the plugin it build a new request for the Plugin.

And it's trivial to implement `Hijack` on the `httpResponseWriterRPCServer` struct but impossible on the `httpResponseWriterRPCClient` 0/5.

Even if we add `Hijack` on `httpResponseWriterRPCClient` this will not work because we will `upgrade` the RPC request and not the initial Http request.

I think the only way to do it it's 1/5 : 

* Add a new special endpoint on plugin (like `public` for example mm.com/plugin/my.plugin.id/ws)
* Add hook in plugin to received messages
* Make a gateway in MM server to pass messages from/to websocket

What do you think?

**Comment by lieut-data** [comment]
Thanks for the investigation, @manland! It sounds like the difficulty is the building of a new request for the plugin each time. I'm not terribly familiar with the flow of websockets, but I'm imagining that when the request gets upgraded, it's saved for reuse as such. Is there a path where we mimic that approach by saving upgraded requests with the plugin context, effectively acting as the gateway you describe?

**Comment by manland** [comment]
IMHO we can : 

Web --WS--> MM --GRPC hook--> Plugin

For example if a plugin has a `WsHook`, MM server upgrade request for plugin (or ask to plugin if it accept the ws request). And then every time a message come in WS it's dispatched to plugin by grpc and send back to WebSocket.

If Mattermost is ok with that feature, I will give it a try ;) Can you share the question and the potential implementation in your daily please? It's a big new feature and I don't want to complexify MM just for me :D

**Comment by lieut-data** [comment]
Agreed that this is a non-trivial undertaking. Let me raise it with the team for discussion as you suggest.

**Comment by lieut-data** [comment]
Sorry for the delay on this one, @manland. I can see the potential use case here, but as you suggest: it's a big new feature, and I'm not sure it makes sense to complicate things right now. We may revisit in the future.

**Comment by lieut-data** [comment]
@streamer45 has indicated he'd like to take a second stab at this ticket.
