### ISSUE TITLE
MacOS Desktop: ⌘+→ and ⌘+← should go back/forward in history

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11433]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-15539)

Repro steps:
1) View a few channels
2) Press ⌘\+← and ⌘\+→ when not focused on any textbox

Observed: Nothing happens
Expected: You go forward or backward in history similar to pressing ⌘+[ and ⌘+]. If you are focused on a textbox, it should not do anything.

**Comment by rexredinger** [comment]
I'll take this one.

**Comment by rexredinger** [comment]
Looks like we have a couple issues.

1. Electron doesn't support defining menu items with multiple shortcuts for the same input. We can hack around this by having identical hidden menu actions for Back/Foward that map to additional key commands.
2. OSX seems to just generally have a problem with munging up ⌘+← and ⌘+→  inputs for many applications.  I confirmed this by simply remapping default ⌘+[ and ⌘+] to the arrow-style and confirming it just doesn't work.  I am still looking into why this happens and what, if anything, we can do to address it.

**Comment by rexredinger** [comment]
Spent some more time simply getting some sort of working ⌘+← history command to work.  And there are a few more hitches.
1. Hidden Electron menu items don't respond to accelerators . So the workaround in # 1 of my previous comment is a not as viable.  You can still make alternative Back/Forward commands with their own accelerators and give them empty labels, but it looks a bit wonky in the menu.
<img width="126" alt="Screen Shot 2019-06-28 at 2 48 44 PM" src="https://user-images.githubusercontent.com/303007/60364337-e1eb4a00-99b3-11e9-87a2-d5f8aca571ff.png">

2. By default, stepping through History also drops cursor focus into the comment bar for that channel.  This functionally disables ⌘+← and ⌘+→ because they are OSX system-level shortcuts for cursor movement.  OSX takes the ⌘+← and ⌘+→ keys and attempts to move the cursor, and does not propagate that command sequence to the Electron menu.  You can get ⌘+←/→ to work by clicking in the side bar in between each History jump, but that's no really very helpful.  We could also try to find a way to prevent the default cursor refocus that occurs as part of History traversal, but that seems equally unhelpful.

3. The above is also true for Alt+←/→ and Ctrl+←/→ inputs.

This feature may just need to be tabled until there is either a "more native" Desktop app, or Electron provides more robust tools for shortcut commands.  We could also opt to find an alternative shortcut for History navigation, if the problem is that ⌘+[/] is disliked.

**Comment by jespino** [comment]
@hmhealey what do you think about it?

**Comment by hmhealey** [comment]
Oh yeah, I hadn't thought of the hotkey conflicts when you're in a textbox. When I filed the ticket, I was mostly thinking of how browsers work, but I forgot that we're more text-focused than a browser.

Thanks for the research, @rexredinger. I agree that we can just leave this for now unless we find some better way to handle it in the future. I'm not even sure a more native Desktop app would support this since we'd still want input focused on the textbox anyway.
