### ISSUE TITLE
Use properly styled scrollbars throughout the app on all browsers

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#11439]
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-13370)

Some browsers (Firefox, IE11, Edge) use the system scroll bar in some places (the centre channel, modals), but in other places (channel sidebar, RHS), they use a nicer scroll bar like Chrome does. For example, here's a screenshot of the RHS and centre channel in Firefox when both have scrollbars
!image-2018-12-06-15-20-26-699.png|thumbnail! 

We should look at unifying the scrollbars throughout the app to use a nicer, more consistent style

**Comment by AGMETEOR** [comment]
I will take this

**Comment by hanzei** [comment]
Thanks for working on this @AGMETEOR

**Comment by AGMETEOR** [comment]
@hanzei I asked for some more clarity on this via the ticket comments. Do you mind taking a look?

**Comment by hanzei** [comment]
@AGMETEOR I've pinged two developers to get there input on your question.

**Comment by AGMETEOR** [comment]
@hanzei I am just following up on this. We had sort of forgotten about it.

**Comment by hanzei** [comment]
Hey @AGMETEOR, just want to check if you are still working on this ticket

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by mikeygbd** [comment]
I would like to give this a shot.

**Comment by hanzei** [comment]
Thanks @mikeygbd

**Comment by jasonblais** [comment]
Hey @mikeygbd, checking in to see how things are going? Any questions so far?

**Comment by breditter** [comment]
Hey!
I'm a fledgling in the open source world, however I'd love to take on this task if help is still needed. Any feedback / advice along the way would also be greatly appreciated. Thank you!
noticed many left this issue without solving it hope its beginner friendly :)

**Comment by jasonblais** [comment]
@breditter Welcome! 😄 

@hmhealey or @esethna are you open to confirming if this ticket is still valid? Just want to make sure since it was created a while ago.

@breditter In terms of guidance, the developer's guide referenced in the ticket description is a good start, and if you have any questions, join our [Contributors community channel](https://community.mattermost.com/core/channels/tickets).

**Comment by hmhealey** [comment]
Yeah, it's still valid, but I don't think the details of the ticket have been fleshed out properly.

@esethna Do any of the newer UX designs include a design for how scroll bars in the app should look?

**Comment by breditter** [comment]
@hmhealey I was wondering the same thing Please let me know the specifics. And also there is a file named _mattermost-webapp/sass/components/_scrollbar.scss_  does it have to do something with global scrollbar.
thank you:)

**Comment by esethna** [comment]
We should ideally use the nicer scroll bar styling that we have in the RHS: https://i.gyazo.com/22090c7b0cf29216d09bf2d2deec18e7.gif

However, one requirement for this would be how we can make the scroll bar ux on tablet devices easier? For example, can we detect if the device is running Windows in tablet mode and display a permanent and wider scroll bar rather than a hiding scrollbar that makes tablet use more difficult? 

See related tickets with some open questions: 
- https://mattermost.atlassian.net/browse/MM-22813
- https://mattermost.atlassian.net/browse/MM-22856

@breditter let us know if you'd be interested in taking this on/ Likely we'd have to work closer with you on a proposed solution that accomplishes the goals of all the linked tickets. cc// @andrewbrown00 on design

**Comment by esethna** [comment]
Also cc// @asaadmahmood on the above

**Comment by breditter** [comment]
Hey @jasonblais @esethna I'm not entirely sure how to code when multiple devices are involved. I would love to work on this or atleast watch how this gets tackled ( as I'm completely new to web development I suppose someone a bit more experienced should take on this). I wouldn't mind stepping back.
Please let me know where these discussions are done.

**Comment by hmhealey** [comment]
Yeah, perhaps this is a little bit bigger than we expected. I think we should take some time on our end to discuss exactly what's expected here since it's rather open-ended right now, and there's a few open questions with the design that need to be answered.

@breditter Perhaps you'd be interested in helping us do some code cleanup to have a chance to explore the code base a bit? We've got a number of tickets available to migrate the web app to TypeScript (like [this one](https://github.com/mattermost/mattermost-server/issues/13727)) and a few to remove some old usage of JQuery and add some end-to-end tests for the affected code (like [this one](https://github.com/mattermost/mattermost-server/issues/15162)) that should be decent starting points.

**Comment by hmhealey** [comment]
Closing this ticket for now while we add some more detail to it.
