### ISSUE TITLE
Email notifications and account verification link

### ISSUE THREAD

**Issue by LocalHeroPro** [mattermost/mattermost-server#11434]
Host OS and version: Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-51-generic x86_64)
Mattermost server version: 5.12.0
Browser webapp: everywhere
Desktop App: 4.2.1 on Windows / Linux
Mobile App: don't have System Console
I'm running Mattermost on server, without any virtualization etc.

1. When I set in Account Settings > Email notifications to Never, I still get notifications.
2. When I set Enable Email Notifications in System Console > Notifications to `false`, I can't Send Email Invite - because of "Email is currently disabled for your team, and email invitations cannot be sent. Contact your System Administrator to enable email and email invitations.". But I want to disable notifications not all email functionality. I also have Enable Email Invitations set to true. Confusing.
3. Also, when I have set Require Email Verification to `true` and then User don't receive message for that. Confusing.

So right now I have to disable Email Verification and disable notifications. When I want to send email invitation I enable notifications only for that reason.

**Comment by amyblais** [comment]
Hi @LocalHeroPro,

1. Sounds like a potential bug, are you getting the unexpected email notifications if you're on mobile or on your computer or both? Do you have email notifications also disabled on mobile?
2. I'll probably ask UX to review if this flow could be improved.
3. Sounds like a potential bug, have the users also checked if the account verification email may have gone to their spam / junk email folder?

**Comment by LocalHeroPro** [comment]
Sorry, point 3 is develop of point 2 and have to sound like:
When I set Enable Email Notifications in System Console > Notifications to false, I can't Send Email Invite - because of "Email is currently disabled for your team, and email invitations cannot be sent. Contact your System Administrator to enable email and email invitations." I also have Enabled Email Invitations to true. Also, when I have set Require Email Verification to true and then User don't receive message for that. Because Email Notifications is set to false. Confusing.
I think we have to separate functionality of Email Notifications and necessary functionality for other implementations, like Email Verification, Email Invitation, etc.

**Comment by amyblais** [comment]
Hi @LocalHeroPro,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
I realized we actually have a ticket for this here: https://mattermost.atlassian.net/browse/MM-15661.

**Comment by LocalHeroPro** [comment]
So I'm not the only one.

PS.: On contribution forum I used all the voices few months ago.

**Comment by S1M0N** [comment]
Just want to chime in that I am seeing similar issues, regarding point 1 in the OP, on our Mattermost. The only part of this that would make any sense is that I'm the Server Admin, so perhaps my personal settings are being overridden by that? Though this shouldn't matter and still qualifies as a bug in my view, as setting my personal notifications for email to Never, should result in just that, no email notifications. 

Small note, our Mattermost instance is part of the GitLab Omnibus Package, rather than a standalone install. 

We have Server Email Notifications enabled, with batching:  
![image](https://user-images.githubusercontent.com/727018/62010665-b76be880-b13b-11e9-8a5f-fc7c8053bfcd.png)

And my personal notification settings are set to never send emails, and I have confirmed this setting shows the same across web, desktop client, and mobile app:
![image](https://user-images.githubusercontent.com/727018/62010673-ca7eb880-b13b-11e9-84ce-d2c68559bd45.png)

However I continue to receive email notifications of messages:
![image](https://user-images.githubusercontent.com/727018/62010691-06b21900-b13c-11e9-8ac0-97a35451ed41.png)

Any thoughts on this, or if I'm missing something, would be welcomed.

**Comment by amyblais** [comment]
Closing as the above ticket is fixed. Please re-open this issue if upgrading to v5.14 doesn't resolve the problem.
