### ISSUE TITLE
[Linux/KDE] clicking URLs to sites with authentication brings to main screen

### ISSUE THREAD

**Issue by shaforostoff** [mattermost/mattermost-server#11476]
click this link in the chat:
https://gitlab.airmusictech.com/kpilch/cpp-style-guide
it is not accessible without login, so in browser i see login screen
after entering credentials, browser open main page instead of repo.

if i repeat this step, main page is shown saying "you are already signed in".

i think it happens because mattermost does URL resolution itself.

does not happen on winows or mac

**Comment by krjn** [comment]
I tried on two instances and neither resolved the URL themselves.

I'm not sure how Gitlab does redirection after login in, but my guess it is through the cookie, since there is nothing on the URL. If that is the case, my best guess is this behaviour difference is not related to Mattermost, but to your browser.

I'd try configuring another browser as the default one and repeating the test. Preferably, the other browser would be a standard configured one - without anything customized with regards to cookies. If that doesn't work, I'd open the dev tools on both setups (e.g. Linux and Windows), check 'preserve logs' before repeating the test and compare the headers on both cases. Specifically, upon first hitting the URL a cookie should be set and it should be maintained.

**Comment by amyblais** [comment]
Hi @shaforostoff, did the suggestion above help?

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
