### ISSUE TITLE
Image preview of plain text URLs doesn't work with an external image proxy

### ISSUE THREAD

**Issue by rofafor** [mattermost/mattermost-server#11857]
#### Summary
Image/link preview works with an external image proxy (atmos/camo) **only** when inline markdown is used.

#### Steps to reproduce
1. Setup and enable an external image proxy: atmos/camo with Mattermost 5.13
2. Paste a image link as inline markdown into a channel: `![alt](https://media.giphy.com/media/JpG2A9P3dPHXaTYrwu/giphy.gif)` - image metadata fetched using a proxied URL and preview is shown
3. Paste the same link as plain text into a channel: `https://media.giphy.com/media/JpG2A9P3dPHXaTYrwu/giphy.gif` - image metadata fetched using an original URL instead of the proxied and no preview

#### Expected behavior
Image metadata should always be fetched via an image proxy if enabled. Markdown and plain text inputs should act similarly.

#### Observed behavior (that appears unintentional) 
Having a strict external network access control on a mattermost server ends up having GET timeouts while trying to fetch the images (metadata) directly without the configured proxy and therefore empty metadata is passed to clients:
```
{"level":"debug","ts":1565605727.1227393,"caller":"app/post_metadata.go:83","msg":"Failed to get embedded content for a post","post_id":"emqibetqfbf75ktz1myfxe1giy","error":"Get https://media0.giphy.com/media/xTiTngBQncyTMceuXK/giphy.gif: dial tcp X.X.X.X:443: i/o timeout"}
```
The empty metadata ends up with no preview functionality in clients.

#### Possible fixes
The rewrite of URLs should also be enabled for plain text messages in *RewriteImageURLs()*:
https://github.com/mattermost/mattermost-server/blob/master/model/post.go#L467.

**Comment by amyblais** [comment]
@hmhealey Do you have an idea on this?

**Comment by hmhealey** [comment]
Hi @rofafor. Do you have the [Enable Link Previews](https://docs.mattermost.com/administration/config-settings.html#enable-link-previews) setting enabled on your server? It's available in the Site Configuration > Posts section of the System Console. As of Mattermost 5.12, that setting needs to be enabled for previews of plain text image URLs to be displayed

**Comment by zetaab** [comment]
@hmhealey Enable link previews is enabled. However, the mattermost server itself does not have any internet access. Mattermost server should use image-proxy to download metadata information from images, but it is not using proxy for plain text URLs - its using proxy only if text contains https://github.com/mattermost/mattermost-server/blob/master/model/post.go#L467

**Comment by hmhealey** [comment]
Oh, I see. I didn't think that the image proxy might be involved with this as well.

The problem with the Mattermost server sending the plain text link through the image proxy is that it doesn't actually know that it should be looking for an image. The older logic was "dumb" since it just looked for an image file extension on the URL to identify images, but the new logic tries to actually identify what the content instead of just making an assumption based off the URL. That gets us into a bit of a loop since we can't determine if a link is an image without making a request and we can't make the request without possibly sending it through the image proxy.

We'll keep this case in mind while we investigate how to fix this feature in environments where Mattermost has limited internet access. I don't know if others have the same setup you do where Mattermost can still access the internet through an image proxy, but that could be something we recommend if we can find some way to make this work.
