### ISSUE TITLE
Extend EnsureBot helper function to include bot images

### ISSUE THREAD

**Issue by marianunez** [mattermost/mattermost-server#11900]
Bots may have a profle image and an icon that will show in the [LHS](https://docs.mattermost.com/process/training.html#lhs) of the webapp. The api offers separate calls to add these after bot creation. 

The [EnsureBot](https://github.com/mattermost/mattermost-server/blob/baedcc856ff474e0a8e7082cf0b94f99c2b5f0cf/plugin/helpers_bots.go#L12) helper function currently creates a bot user and should be extended to be able to create one that includes given profile and/or icon images.

The proposal is to extend `EnsureBot` that will could also receive relative paths to the plugin folder of an icon and/or profile images which will load and pass to the api to set them respectively. This can be implemented using [functional options](https://github.com/tmrts/go-patterns/blob/master/idiom/functional-options.md#constructor) through a `EnsureBotWithOptions(*Bot, …Options)`  where `Options` could start by having the relative path for the profile image and one for the bot image.

----

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-17297

**Comment by alxsah** [comment]
I would like to pick this up if possible.

**Comment by marianunez** [comment]
Thanks @alxsah 🎉

**Comment by alxsah** [comment]
Apologies if this is a stupid question - could someone please clarify which format the images would be in, and whether they would have fixed dimensions?

I'm trying to understand whether any formatting/resizing of the images would be needed before passing them to the API. Thanks.

**Comment by ali-farooq0** [comment]
> Apologies if this is a stupid question - could someone please clarify which format the images would be in, and whether they would have fixed dimensions?


@alxsah the bot icon image is supposed to be `svg` format, any other formatting is rejected when setting the icon for a bot.
For profile image, I believe it can be any common image format `png, jpeg` you can see the [setProfileImage](https://github.com/mattermost/mattermost-server/blob/master/app/user.go#L874) api to see the validation there.

> 
> I'm trying to understand whether any formatting/resizing of the images would be needed before passing them to the API. Thanks.

Nope, the underlying api should take care of that, if not, then maybe we should add validation in a common spot so the underlying api does validation for however it is invoked. Otherwise you can just do the same validation as https://github.com/mattermost/mattermost-server/blob/master/app/user.go#L874 for the profile image.

Hope this helps :)

**Comment by alxsah** [comment]
@ali-farooq0 That makes sense, thanks again. I'll take a look at some of the existing validation.
