### ISSUE TITLE
Send rendered HTML instead of raw markdown in email notifications

### ISSUE THREAD

**Issue by harshilsharma2** [mattermost/mattermost-server#13455]
Currently an email notification shows raw message text which looks bad when the text is markdown.

For example-
![](https://i.imgur.com/22e6vFh.png)

It would be much better for UX and for readibility of the message in notifications if email contained rendered HTML for markdown instead of raw text.

**Comment by jasonblais** [comment]
Hmm, as far as I know this should be supported, though it could have broken https://mattermost.atlassian.net/browse/MM-1762

@harshavardhana wondering if your email preferences are set to plain text or HTML? Also, which Mattermost server version are you using?

**Comment by jasonblais** [comment]
Hmm, as far as I know this should be supported, though it could have broken https://mattermost.atlassian.net/browse/MM-1762

@harshilsharma63  wondering if your email preferences are set to plain text or HTML? Also, which Mattermost server version are you using?

**Comment by harshilsharma63** [comment]
@jasonblais I received this notification from https://community.mattermost.com . I coultn't find any email preference in user settings and also not in system console of my local Mattermost instance. Can you help me locate it?

**Comment by jasonblais** [comment]
Hey @harshilsharma63, sorry I confused myself. The ticket I referenced above isn't relevant for Markdown rendering.

This needs some research to look into how we can handle the Markdown rendering, since it would probably require a go markdown parser which would need to be modified for our use cases.

Would you be open to contributing this to the feature proposals forum, and we can track interest and comments there? https://mattermost.uservoice.com/forums/306457-general
