### ISSUE TITLE
Passwords : Length limit and allowed special characters

### ISSUE THREAD

**Issue by LilianCruanes** [mattermost/mattermost-server#13644]
### Summary
Hi ! We have recently integrated Mattermost in the [SystemA's plAtform](https://systema.earth) and mattermost's accounts are automatically created (via the API) when participants register to the plAtform.
The plAtform allows 255 characters password that can contain any characters.
But Mattermost limits them to 64 characters and even if all password's limitations are unchecked in the System Console, passwords like `"aahh47a૱┯┰┱┲❗►◄ĂăǕǖꞀ¤Ð¢℥Ω℧Kℶℷℸⅇ⅊⚌⚍⚎⚏⚭⚮⌀⏑⏒⏓⏔⏕⏖⏗⏘⏙⏠"` don't work, the api raises this error : `Your password must contain at least 10 characters.`

#### Consequence
When a participant give a password that is not allowed by the Mattermost server, it's account on the plAtform is created but he cannot authenticate to the discussion space cause its Mattermost account was'nt created.

#### Steps to reproduce
- Uncheck all passwords' limitations in the System Console.
- Try to create an user with `password = "aahh47a૱┯┰┱┲❗►◄ĂăǕǖꞀ¤Ð¢℥Ω℧Kℶℷℸⅇ⅊⚌⚍⚎⚏⚭⚮⌀⏑⏒⏓⏔⏕⏖⏗⏘⏙⏠"`

#### Question
I know that the 64 characters' limitation is due to the blowfish 72 characters' limitation. (https://github.com/mattermost/mattermost-server/issues/9972)
I know that if this limitation was raised, user that gave a 100 characters password could authenticate with the 72 first characters of its password  only.
But it will also work if he type its 100 characters' password.
**So I would like to know if it is possible to override the 64 characters limitation and to know which special characters are allowed by the Mattermost server (maybe there is a regex ?).**
<br/>
Thanks for your help :)

Lilian.

**Comment by amyblais** [comment]
@crspeller @DSchalla Do you know the answers to the above questions:
 - If it is possible to override the 64 characters limitation
 - Which special characters are allowed by the Mattermost server (maybe there is a regex?)

**Comment by DSchalla** [comment]
Hi @LilianCruanes,

regarding the validation, I fear it's a problem related to the unicode characters. We are checking the length of the string for the password and cap it at 64, as you've noticed. Now your string is in theory just 49 characters long, but because of the way Go handles it it is being recognized as 126, here a small Go Snippet to demonstrate and the piece in the code where we check the length:

https://play.golang.org/p/FvLEJ__OqhF
https://github.com/mattermost/mattermost-server/blob/master/utils/password.go#L17

We currently don't provide an option to overwrite the max. length, so until then I'd recommend to rely on a strong combination of [A-z0-9] and any non-unicode special characters until we've discussed the problem internally and the potential impact of fixing it this way.

Let me know if there are any other questions!

**Comment by LilianCruanes** [comment]
Hi @DSchalla, thanks for your answer !
I've fixed password length problem limiting the plAtform's password's length to 64 characters, it could work alike a long time, that's ok.
But the biggest problem for us is that not all unicode characters are allowed, is there a way to allow them ?

**Comment by LilianCruanes** [comment]
Did you forget me ? :) @amyblais @DSchalla

**Comment by DSchalla** [comment]
Absolutely not forgotten, we actually discussed the topic yesterday on our community server - Feel free to join if you'd like of course!

The problem is that bcrypt has not a character limitation but a byte limitation, which we currently enforce at 64 bytes in a string. You can absolutely use unicode character, but since Unicode characters can be up to 4 byte in size, this reduces the amount of characters you can use with your password.

So as example, you can use a 64 character password with normal ASCII symbols, but if you use Unicode you may only be able to use a 30 character password. If we would allow any higher byte count for the password bcrypt would just truncate it. The only possible solution is to migrate to another hashing algorithm at some point, which is currently not on a roadmap.

My recommendation would be to either reduce the password length with unicode characters so that the byte count is equal or lower to 64, or use 64 ASCII characters as passwords if you would like to use the maximum.

**Comment by LilianCruanes** [comment]
> My recommendation would be to either reduce the password length with unicode characters so that the byte count is equal or lower to 64, or use 64 ASCII characters as passwords if you would like to use the maximum.

@DSchalla Thanks, I think it is not a very clean solution, but 64 bytes' password could make the job at this time :)

A last question :

When users register on the SystemA's plAtform a temporary mattermost account is created for them and it is named "tmp-<user's uuid>".
A bit later, they are queried to type an username and the python scripts automatically asigns the typed username to the temporary account.

So I had to enable validation on the username's field and at this time I am using this python regex : `^[a-z]([a-z0-9\.\-\_]){3,21}$`
But sometimes the username seems to be not accepted by the Mattermost server and the username typed by the user is not assigned to its mattermost's account, which is always called "tmp-<user's uuid>".

**So where is the username regex ? What am I missing in my regex ?**

**Comment by LilianCruanes** [comment]
@DSchalla @amyblais I'm so sorry to run you... But a lot of account are created without username caused by an username's error. It's very confusing, it would be possible to fastly answer me to the question that I post in my last message here ?

> **So where is the username regex ? What am I missing in my regex ?**

**Comment by DSchalla** [comment]
Hi @LilianCruanes,

I am sorry to hear that it's a unclean solution for you, we are sadly bound by the limits of the hashing algorithm. Increasing the password byte limit would just result in truncating it never the less after 64 bytes.

For the username, did you take a look at the source code for the user model here? https://github.com/mattermost/mattermost-server/blob/master/model/user.go#L751

If you got any questions regarding it, let me know.

Thanks,
Daniel

**Comment by LilianCruanes** [comment]
Oh weird, my regex looks good and errors are always here... I'm going to investigate this, the error seems to be on my side, thanks for your help @DSchalla @amyblais 
See you :)
