### ISSUE TITLE
Server ignores SqlSettings.DataSource for PostgreSQL driver in Linux.

### ISSUE THREAD

**Issue by p620-dev** [mattermost/mattermost-server#13659]
#### Summary
As stated in the title.

#### Steps to reproduce
By following [your own guide](https://docs.mattermost.com/install/install-debian.html#installing-mattermost-server) and launching the server with the connection information changed at step 7.
First encounter at v5.19.0 but appears to date as far back as v4.10.10 at least.
Debian 10, amd64
#### Expected behavior
The changes made to the config file must be acknowledged.
#### Observed behavior (that appears unintentional) 
![mattermost](https://user-images.githubusercontent.com/60119712/72765468-9de4be80-3bfd-11ea-975c-6f771560a50e.png)

**Comment by amyblais** [comment]
@cpanato @grundleborg Would you know if this is a bug or an error on our documentation?

**Comment by agnivade** [comment]
Are you using postgres or mysql ? Because it looks like you want to use postgres, but the dsn is of mysql type.

**Comment by p620-dev** [comment]
> Are you using postgres or mysql ? Because it looks like you want to use postgres, but the dsn is of mysql type.

Due to your corrections the issue was resolved, however I would still consider this a bug.
In my configuration I've assumed that the `driver` part of the DSN would be filled automatically since it has already been configured within `SqlSettings.DriverName` (as the things are with MySQL, it appears). However, not only it wasn't, but, instead of raising an error for example, the server actually ignored the configuration completely (as erroneous, I guess) in this case and instead filled it with a default placeholder (with `[::1]:5432` as target host) which is completely misleading and caused me to interpret it as a bug.

**Comment by agnivade** [comment]
Glad to hear that it has been resolved !

Regarding the dsn bit, I believe this has to do with how the `database/sql` package works. [sql.Open](https://golang.org/pkg/database/sql/#Open) accepts both driverName and dataSourceName. The config values are the ones we pass to that function.

> instead filled it with a default placeholder (with [::1]:5432 as target host

The "server" did not do anything extra on it's own AFAIU. This is just the result of passing those 2 values to Go's database driver. Resolving the port to 5432 just seems to be what it internally figures out.

Also, `mysql` does not have drivername in it's DSN - https://github.com/go-sql-driver/mysql/#usage. But `postgres` does - https://godoc.org/github.com/lib/pq. So in some cases, the drivername needs to be in the DSN, and in some cases, it doesn't. And it all depends on how the internal database driver library is implemented.

However, this scenario does seem like something more folks might trip on. Perhaps we can document this caveat more strongly somewhere ? Would you be open to filing a new issue so that we can discuss this further and possibly create a documentation PR ?

**Comment by agnivade** [comment]
I'll go ahead and close this one as the original issue seems to be resolved. Please feel free to create an issue to clarify the documentation, or even a PR to improve it would be much appreciated!
