### ISSUE TITLE
Do not silently close modified Edit Post dialog on a mouse click outside it

### ISSUE THREAD

**Issue by mvitaly2003** [mattermost/mattermost-server#13831]
#### Summary
If you try to edit a message in chat and accidentally click outside Edit Post dialog, the dialog silently closes and all your changes get lost.
I found a related issue #10771 that seems to be fixed in 5.12 but it was only related to dragging text out from edit dialog, not to clicking outside of it.

#### Steps to reproduce
Open a chat, find any of your messages and choose 'Edit' from 'More Actions' menu, then change text and do a click outside the edit dialog (e.g. for activating application back after switching to another one). This is reproduced on Mattermost server 5.17.1 and client 4.3.2.

#### Expected behavior
Mattermost either should show a confirmation dialog (like it does when you delete a message) or it shouldn't close this dialog with unsaved changes on a mouse click outside the dialog.

#### Observed behavior (that appears unintentional) 
Edit dialog just disappears w/o saving your changes and w/o asking your if you want to save them.

#### Possible fixes
1. Ignore clicking outside of an edit dialog when there are unsaved changes
2. Add a confirmation before closing an edit dialog with modified text

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-22360.

**Comment by JonathonReinhart** [comment]
Please address this. It is absolutely maddening to spend 15 minutes editing a message, just to lose your edits because you clicked outside of the dialog box.

This is a serious UX problem because it is different from the way users normally expect an application to work. No other windowing system I've ever used since Windows 3.1 would close a dialog box when you click outside of it, and I don't understand the rationale for why it should ever behave this way.

**Comment by amyblais** [comment]
This has been fixed for upcoming v5.22 release which is scheduled for April 16th,
