### ISSUE TITLE
Possible typo in maximum file size for profile picture

### ISSUE THREAD

**Issue by checkaayush** [mattermost/mattermost-server#13882]
#### Summary
Maximum file size supported is 1000 MB for profile picture in account settings on commnuity hosted version. Assuming 1000 MB is a typo which needs fixing.

#### Steps to reproduce
1. Head over to community-release.mattermost.com.
2. Go to Account Settings > General Settings > Profile Picture
3. Message says maximum file size supported is 1000 MB.

#### Expected behavior
Maximum file size supported should be way less than 1000 MB.

#### Observed behavior (that appears unintentional) 
Maximum file size supported is 1000 MB.

#### Possible fixes
Update the max file size supported as a reasonable value.

**Comment by amyblais** [comment]
Opened a ticket to investigate: https://mattermost.atlassian.net/browse/MM-22564.

**Comment by amyblais** [comment]
@checkaayush This was an intentional change on the community servers. One option is to considering separating max file size for profile pictures from the global Maximum File Size config setting (under File Storage section in the system console). Would you be open to help opening a feature request issue for this?

**Comment by checkaayush** [comment]
https://github.com/mattermost/mattermost-server/issues/13903
