### ISSUE TITLE
SAML attribute blank/empty

### ISSUE THREAD

**Issue by terafirmanz** [mattermost/mattermost-server#14379]
### Summary
When user logs in using SAML if one of the attributes passed back is blank login fails e.g. Title is set to title attribut but the Identity source has no title for that user

#### Steps to reproduce
set all SAML attributes to accept fields in the response then login with a user who does not have one of those files

#### Expected behavior
Some attributes should be optional anythign other than ID, username and maybe email should accept blank values 

#### Observed behavior (that appears unintentional) 
There was an error logging you in as one of the SAML attributes was incorrect.

**Comment by amyblais** [comment]
@terafirmanz Would you be open to sharing these additional details:

1. What Mattermost server version are you on?
2. What OS and version are you on?
3. Do you see any errors in logs?
4. What are your SAML related config settings set to?

**Comment by terafirmanz** [comment]
Hi,

1. we are on 5.22
2. We are on Ubuntu 18.04
3. Yes : "user_id": "", "method": "POST", "err_where": "SamlInterfaceImpl.DoLogin", "http_code": 302, "err_details": "Title attribute is missing"}
The user had no title in Active Directory so SAML passed a blank value.
4. how much do you need? I am using the old library and the new SAML library has too many issues for us to get it working just yet (other cases open for these). Other than that setup with ADFS and working for users. 

When I remove the SAML config for the Title attribute this user can then login successfully.

**Comment by amyblais** [comment]
Thank you, I have pinged our support team to take a look at this,

**Comment by sbishel** [comment]
This should be reviewed and probably fixed. I don't think we are distinguishing between a missing attribute and an existing attribute that is empty.

**Comment by sbishel** [comment]
https://mattermost.atlassian.net/browse/MM-25283

**Comment by RikuXan** [comment]
@sbishel Is it possible that this issue has reappeared due to a regression or something similar?
My newly installed, on-premises 6.3.0 Mattermost Enterprise (installed on K8s via the official Helm Chart) shows the same behaviour after having configured the SAML 2.0 field *Preferred Language Attribute*. 

The configuration field is set to *locale*, which is also the name of the Keycloak user attribute that is mapped into the SAML response. The Keycloak user attribute is non-mandatory, and while the SAML login works when the attribute is set (even to an empty string), it fails with the same error message as described above when the attribute is missing and the SAML response thus lacks its locale assertion.

**Comment by zsrv** [comment]
I've run into the same problem with Mattermost 10.2.0: I've configured SAML authentication and set the optional first and last name attributes. If a user does not have their first and/or last name set, Mattermost returns error "SAML login was unsuccessful because one of the attributes is incorrect. Please contact your System Administrator.". If the user sets their first and last name, login is successful.
