### ISSUE TITLE
Emojis from Emoji 5.0 and 11.0

### ISSUE THREAD

**Issue by larsnaesbye** [mattermost/mattermost-server#14528]
It would be real nice to have the newer emojis available from Emoji 5.0 and 11.0 available through the emoji picker.

If there is a way I can help to add them according to a prescribed procedure, I'd love to concoct a pull request.

**Comment by amyblais** [comment]
I think there is a ticket open related to this https://mattermost.atlassian.net/browse/MM-22642. @hmhealey might know if this can be opened as a Help Wanted issue.

**Comment by larsnaesbye** [comment]
Ah okay, thank you @amyblais . That ticket says 13.1, that's of course much newer than my suggested 5.0 and 11.0. 

If there's a way emojis have been added in the past, I might just follow it :-)

**Comment by hmhealey** [comment]
Updating the emoji sets is something we'd definitely like to do, but we've ran into some issues with that. We used to use https://github.com/github/gemoji to generate a list of emojis and emoji images, but they've since stopped supporting extracting emoji images. We've considered things going forward like relying on the browser to provide native emojis instead of supplying emoji images, but we haven't had time to fully explore that idea yet.

We have a meeting scheduled next week to explore that a bit further. I can let you know if we end up creating Help Wanted tickets out of that.

**Comment by larsnaesbye** [comment]
@hmhealey What was the outcome of the meeting?

**Comment by wezm** [comment]
FYI I'm willing to contribute AU$250 to anyone that can make progress on this. [See my post for more details](https://www.wezm.net/v2/posts/2020/bounties/#update-mattermost-server-to-support-emoji-added-after-unicode-9-0).

**Comment by hmhealey** [comment]
@larsnaesbye It's on my roadmap to work on next after I get some big sidebar updates into testing. Unfortunately those updates are taking longer than we wanted, but emoji updates are still planned for after that

**Comment by larsnaesbye** [comment]
Cool. Let me know if there's anything I can do to help.
