### ISSUE TITLE
Posted websocket event doesn't include self mentions

### ISSUE THREAD

**Issue by thezboe** [mattermost/mattermost-server#14676]
Mattermost Version: 5.21.0
#### Summary
Websocket mention field does not include my user id if I mention myself in a message. This is especially important for automated bots that have commands that take user mentions.
For example, a `forsale` command should work the same when I run it on my user as any other user.

#### Steps to reproduce
If user @user sends a message:
`pinging @user`
The websocket event mention field will be null even though there is a mention in the message.

#### Expected behavior
All mentioned users should be present in the mention field.

**Comment by thezboe** [comment]
Also, mentions are not listed for users who are not in the same channel as the message they are mentioned in.

**Comment by amyblais** [comment]
@thezboe Do you see any log errors or console errors? Do you have a sample payload?

**Comment by hahmadia** [comment]
Hello @thezboe and @amyblais ,

I was able to track this down to here: 
https://github.com/mattermost/mattermost-server/blob/master/app/notification.go#L136

It seems that we are intentionally removing self mentions if the post is not coming from a webhook (I assume it's because a webhook post wouldn't have the property of post.UserId). I'm not sure the reason why we are removing self-mentions but it's being done intentionally as there is a comment that specifically says `prevent the user from mentioning themselves`. 

Hope this helps!

**Comment by streamer45** [comment]
> Hello @thezboe and @amyblais ,
> 
> I was able to track this down to here:
> https://github.com/mattermost/mattermost-server/blob/master/app/notification.go#L136
> 
> It seems that we are intentionally removing self mentions if the post is not coming from a webhook (I assume it's because a webhook post wouldn't have the property of post.UserId). I'm not sure the reason why we are removing self-mentions but it's being done intentionally as there is a comment that specifically says `prevent the user from mentioning themselves`.
> 
> Hope this helps!

I believe that was added cause it was possible to create a infinite loop. @wiggin77 should know more about it.

**Comment by wiggin77** [comment]
> I believe that was added cause it was possible to create a infinite loop. @wiggin77 should know more about it.

Thanks @streamer45 .  If you are referring to https://github.com/mattermost/mattermost-server/pull/14410/files , then it only involved posts of type auto-responder.

**Comment by amyblais** [comment]
@hahmadia / @streamer45 Is this something that should be documented?
