### ISSUE TITLE
Slow text entry

### ISSUE THREAD

**Issue by hjek** [mattermost/mattermost-server#15012]
#### Summary
Text entry is slow when entering messages on Mattermost

#### Steps to reproduce
- Start typing a message on Mattermost
- Wait for text box to catch up with what was typed, sometimes 5+ seconds

Software used:
- Firefox 78.0.2 (64-bit)
- Mattermost 5.23.1

#### Expected behavior
I'm expecting the message box to catch up with my typing with a delay less than 200 ms. The CPU is maxing out whenever I start typing. I can confirm this happens on Chromium as well, and both on Debian and Fedora on different devices.

#### Observed behavior (that appears unintentional) 
![mm_text_entry](https://user-images.githubusercontent.com/11958965/87258493-3de01e00-c4a4-11ea-851c-f906075910d6.gif)

#### Possible fixes
Sorry, I'm not sure how to fix this, but text boxes work fine on other websites, such as Github.

**Comment by amyblais** [comment]
@hjek Are there any console errors you could help share?

**Comment by hjek** [comment]
Not getting any console errors. :neutral_face:

**Comment by hjek** [comment]
Console log from when I've opened Mattermost and start typing in a message:
```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. off-topic
Loading bigbluebutton plugin index.js:107:16
Loading gabay.mattermost-rtl-plugin plugin index.js:107:16
Loaded gabay.mattermost-rtl-plugin plugin index.js:93:20
Loaded bigbluebutton plugin index.js:93:20
websocket connecting to wss://*****.***/api/v4/websocket websocket_client.jsx:35:20
computer woke up - fetching latest 2 needs_team.tsx:92:24
```

**Comment by sudheerDev** [comment]
@hjek, I don't see any logged issue so far for this issue, Can you send me a chrome performance profile of the issue?. 

To record a performance profile. 

Right-click on the tab.
Click on inspect
Click on performance tab
Click on record
Start typing in the textbox
Stop recording the profile.

**Comment by hjek** [comment]
> Can you send me a chrome performance profile of the issue?

@sudheerDev, [Profile-20200715T154011.json.zip](https://github.com/mattermost/mattermost-server/files/4928044/Profile-20200715T154011.redacted.zip)

**Comment by hjek** [comment]
Was the performance profile of any use? Is there more information I can provide to aid debugging, or are there any settings I can twiddle to narrow down the issue?

**Comment by sudheerDev** [comment]
@hjek Thanks for sending in the profile. 

Could you try few things and let me know how typing feels in the scenarios

1. Chrome incognito 
2. Another browser(Like firefox)
3. i see that you have rtl plugin enabled. Can you ask your admin to disable and then try the app in incognito

Let me know if any of the following steps result in better typing experience

**Comment by mm--** [comment]
I'm also getting this issue, with both Firefox 77 and Chromium on GNU/Linux, with Mattermost version 5.22.1. I don't see the RTL plugin enabled on the instance I'm using.

I notice that the typing lag is slightly decreased when Markdown formatting is turned off. I only have access to a minified JS source, so I noticed that an event handler named `Cn` was taking the most time. Searching within the minified source, I saw there was something like `Cn.MARKDOWN_PREVIEW`.

Intuitively, it seems like there's some keydown event handler that's doing too much. Like, maybe the keydown event is causing a React state change which causes every dependent thing to be recalculated on every single keystroke. It seems like some of these events (like Markdown previewing or name/channel suggestions) should be debounced.

**Comment by Schleuse** [comment]
I've had performance issues in a channel which contained highlighted code written in a specific way.
After some profiling I've figured out that the Highlighting seems to be the Problem (in my case anyway).

Deleting the highlighted code fixed the performance issues for me. I've opened an [Issue at hightlight.js](https://github.com/highlightjs/highlight.js/issues/2656) for this.

**Comment by jeffrysleddens** [comment]
We ran into the same problem after going from 5.19.1 to 5.25.5.  Very sluggish text input. Enabled plugins: Jira, Matterpoll and Memese.

**Comment by ChristianCiach** [comment]
Same issue since recent update to Mattermost 5.26.2 and using Firefox 81.0.1. Text input is also sluggish when using Chrome, but not as bad as with Firefox. Unfortunately I don't know which version of Mattermost we were using before the update that introduced the issue.

For me, it probably has nothing to do with highlighted code, because this issue presents itself in every chat, even those without any code.

**Comment by amyblais** [comment]
Hi all,
1. Do you have any specific tools on your end that we can use to measure the database performance of the instance? If yes, can you please share the results and the documentation for reference?
2. Are there any server log errors or console errors that you can help share?
3. Can you help test if you see same results in different browsers?
4. Can you help disable any plugins enabled on your server and see if it changes the behaviour?

**Comment by jeffrysleddens** [comment]
Interesting fact, when I perform a search in a channel and leave the search results open the typing slowness in the chat input is greatly intensified.

**Comment by RalfJung** [comment]
> For me, it probably has nothing to do with highlighted code, because this issue presents itself in every chat, even those without any code.

I have the same problem. When I do not do anything else on my laptop it is okay, but once there is anything going on in background (even if just some of my 4 cores are used), Mattermost becomes basically unusable. Other websites (GitHub or Zulip) still have very responsive text input, but Mattermost can have multi-second input latency.

This is using Firefox 82. I even [reported this in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1650731) but actually it affects only Mattermost, not other websites.

Let me know if gathering more profiles or so would be useful.

**Comment by ahmaddanialmohd** [comment]
Hi, everyone.

I tested this on a fresh vanilla instance on the following environment:
* Mattermost Server 5.26.2
* Firefox 82.0 (64-bit)
* Chrome 86.0.4240.111 (Official Build) (x86_64)
* Mac OS 10.15.7 (19H2)

While comparing the text input delay between Chrome and Firefox, I do not see any significant difference between the browsers.

Putting the possibility of addons contributing to the issue into perspective, can you confirm if the problem is observed in the *Incognito* mode of Firefox?

When the issue occurs, how is the resource consumption like for Firefox? (using top or htop to verify this). For example:

![image](https://user-images.githubusercontent.com/49461314/96910326-e9503400-14d1-11eb-9d58-ccfab73974ec.png)

Additionally, can you also reproduce the issue on https://community.mattermost.com/ if you have an account?

**Comment by jeffrysleddens** [comment]
For me the problem occurs on busy channels or channels with a lot of history. In new empty channels the typing is fast as normal.

**Comment by RalfJung** [comment]
> Putting the possibility of addons contributing to the issue into perspective, can you confirm if the problem is observed in the Incognito mode of Firefox?

I created a fresh profile for Firefox. To reproduce the problem in its extreme form, I then also had to enable WebRender. Then I see an extreme slowdown in Mattermost once there is background load on my CPU, but not on other websites.

Without WebRender, the slowdown is much less pronounced, and does not seem to be much worse on Mattermost than it is elsewhere (without having objective measurements, this is hard to tell).

**Comment by RalfJung** [comment]
Okay I have to correct that, even without WebRender the latency is still notably higher in Mattermost than on other websites.

**Comment by amyblais** [comment]
Could be related: There was [a forum post](https://forum.mattermost.org/t/mattermost-v5-22-0/9529/8) about this earlier and we submitted a PR for the Go project: https://go-review.googlesource.com/c/net/+/237957 (still under review).

**Comment by hjek** [comment]
> Putting the possibility of addons contributing to the issue into perspective, can you confirm if the problem is observed in the _Incognito_ mode of Firefox?

Yes, the issue happens in incognito mode in Firefox, too.

> Additionally, can you also reproduce the issue on https://community.mattermost.com/ if you have an account?

I can reproduce on community.mattermost.com as well.

**Comment by RalfJung** [comment]
A firefox dev analyzed a perf profile that I uploaded and noted

> The profile that you did include has very large input lag, but it looks like all of that time is being spent running JS in Mattermost. 

So it looks like Mattermost is doing some JS on the critical path between entering a character and showing it on the screen. If possible, it would be great if you could switch to some other API that does not block processing the input until JS is done -- APIs which seem to be used by applications such as GitHub or Zulip, which both provide "enhanced input mode" (emoji, auto-completion of @-mentions) without causing enormous input delays.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-30407

**Comment by hjek** [comment]
> When the issue occurs, how is the resource consumption like for Firefox? (using top or htop to verify this).

Here are two screenshots showing resource consumption while typing and not typing in community.mattermost.com in Firefox.

![typing_cpu](https://user-images.githubusercontent.com/11958965/98588601-4159a980-22cc-11eb-916b-46c79a1b42bf.gif)

**Comment by roelandschoukens** [comment]
I have the same issue both on the desktop app and in a browser, but it only happens if the extra panel (recent mentions or search) is open.

**Comment by kongr45gpen** [comment]
Can reproduce this on desktop Firefox. It is especially pronounced on the RHS with long threads open (eg >300 messages sent).   A quick performance analysis shows too many DOM Events caused by `onkeydown` events on the text input.

![Screenshot_20201123_052024](https://user-images.githubusercontent.com/720678/99926809-9a552300-2d4b-11eb-931e-676506cd1fcd.png)

**Comment by Susticle** [comment]
A user of an instance maintained by me notified me about this a while ago. Now I was able to see the problem myself with Chromium/Firefox (Linux) in a longer discussion thread.

CPU load is very high when it happens and seems to be worse with Firefox.

So for me it appears similar as described here:
https://github.com/mattermost/mattermost-server/issues/15012#issuecomment-714669237

**Comment by hmhealey** [comment]
Is anyone on Mattermost 5.30 or newer able to still reproduce this issue? We made some decent performance fixes, particularly for users with a large number of channels and when typing in the RHS, in that release, so this problem might be resolved now.

**Comment by ChristianCiach** [comment]
@hmhealey The issue has been solved for me in the meantime. Unfortunately, I am not the one in charge of our mattermost installation, so I cannot tell you when our IT department installed which versions of mattermost - or if something else has been changed that resolved this issue.

**Comment by hmhealey** [comment]
As long as something fixed them, that's good at least. Hopefully it's improved for others as well.

**Comment by kongr45gpen** [comment]
For me, unfortunately the issue still exists, albeit a bit less pronounced (Mattermost 5.31.6, Firefox 84.0.2 on 64-bit Linux). I have about 100 channels in the LHS, and this issue only shows up when the RHS sidebar is full of messages (e.g. long thread opened, or many returned search results)

**Comment by hjek** [comment]
> Is anyone on Mattermost 5.30 or newer able to still reproduce this issue?

Thanks for you work on this issue, @hmhealey. I am still experiencing this issue on community.mattermost.com

**Comment by jasonsmith425** [comment]
Since upgrading from 5.29.1 to 5.32.1 I and at least some other users are experiencing a lot of slowness. I have made a lot of typos because of this issue.

**Comment by lieut-data** [comment]
@jasonsmith425, @hjek & @kongr45gpen -- we have a pending change (https://github.com/mattermost/mattermost-redux/pull/1407) which I expect will address at least /some/ of the problems here. In the course of that investigation, I've discovered other issues and expect to follow up in the coming weeks. But my hope is that that fix gets us past the really painful part of this issue.

It will hopefully be live on community-daily in a few days, after which I'd love your feedback. The plan is to include in v5.33 as well as backport to our v5.31 ESR.

**Comment by stefanct** [comment]
AFAICT it was not included in v5.33.1. Am I right in assuming it will be in v5.33.2? An update on any further plans would be appreciated. Sorry for pestering but this issue makes some MM instances hardly usable for me...

**Comment by agnivade** [comment]
Yes, this is in 5.33.2.

@stefanct , @kongr45gpen - Would you be able to try with a MM version >= 5.33.2 and let us know if there is an improvement? There is still some performance left to extract, but users have reported a slightly better experience.

**Comment by jasonsmith425** [comment]
I would agree our performance got less bad with 5.33.3 but it's still bad.

**Comment by agnivade** [comment]
Thanks @hjek for the report! It wasn't me who worked on the issue but @lieut-data :) The slowness isn't to do with suggestions AFAIK, but we saw this happen for users with a lot of DM messages open. But clearly, this is happening to you with just 2 DM channels too.

/cc @lieut-data if you want to gather any info.

**Comment by lieut-data** [comment]
@hjek, I really appreciate your continued testing and observations here. The screen recording you've shared is unlike anything we've been able to reproduce so far.

I know a few months back you were able to provide a performance trace while typing: could I trouble you for a fresh one against our community server? Ideally using Chromium, since it should also contain some of the React events showcasing reconciliation and such.

Also, for reference, what kind of computer specs are you running? We can still reproduce some issues when we artificially slow down the CPU (in Chrome). Obviously, the specs shouldn't matter at all for something like this, but it would be helpful to align all the o set actions together.

**Comment by stefanct** [comment]
on an abstract level the problem seems obvious: you are executing waaaaay too much code on every key press.
the performance is very different between firefox and chromium. on the latter i get a few dozen, maybe up to 200ms lag. on firefox it is unusable with lag in the seconds as shown above. but even on chromium the cpu load heavily increases when typing and tbh this is ridiculous. if you are investing time in testing cpu loads on simple text entry and have to take cpu specs into consideration you have long left the road of sanity IMHO. if i could i would use an irc bridge (true) or telnet (joke)... anything would be more convenient than this. yes, i am snarky. i always get snarky if devs focus on "features" instead of usability and break tools i have to use, sorry, not really sorry.

one observation from my side. i only have 2 instances to test. the number of channels or users or the server version seems to play a much bigger role than the content/history or the rate of messages. on a small instance (with 5.25.2) with ~5 active concurrent users and only a few channels the lag in ff is usable. on the other one (with some more current mm) there are >60 users in the channels and two dozen channels or so. there is not much traffic in either of the two but there is a log more content/history in the first (faster!) one. on the second instance the lag is really bad. but as i grumbled above none of this *should* matter.

**Comment by lieut-data** [comment]
> on an abstract level the problem seems obvious: you are executing waaaaay too much code on every key press.

Indeed: as near as I understand it, the issue stems from our incorrect usage of Redux that ultimately results in a ton of unnecessary React overhead. Tackling this isn't impossible, but it requires intentional and un-distracted effort.

> i always get snarky if devs focus on "features" instead of usability and break tools i have to use, sorry, not really sorry.

@stefanct, I don't mind the honest feedback. My sentiments run in the same direction :)

**Comment by hjek** [comment]
> Also, for reference, what kind of computer specs are you running?

- CPU: AMD E1-2100 APU (2) @ 1.0GHz 
- GPU: AMD ATI Radeon HD 8210 
- Memory: 2822MiB / 3365MiB

> could I trouble you for a fresh one against our community server? Ideally using Chromium,

I tried Chromium on community.mattermost.com and performance was okay. Performance is worse when recording a profile, so not sure how accurate an picture it paints.

[Profile-20210428T002436.json.zip](https://github.com/mattermost/mattermost-server/files/6388065/Profile-20210428T002436.json.zip)

That other recording of community.mattermost.com is from Firefox 88. The input latency there is very temperamental.

**Comment by lieut-data** [comment]
@hjek, thanks for that trace! It roughly compares to my own in terms of the raw events happening. (On my my 2.5 GHz Quad-Core Intel Core i7, the effects are not nearly as severe as what you're seeing, but I can simulate your pain with a 4x or 6x CPU throttling.)

What this tells me is that the pending work we intend to do in addressing the fundamentals is still the right approach here, and that you're at least not running into "a different issue." All I can say for now is: stay tuned.

**Comment by lieut-data** [comment]
@hjek, I won't turn down data :)

Note that while I remain tangentially involved in this investigation, @hmhealey and team are driving next steps. There are various issues at play here, some of which may indeed by Firefox specific.

**Comment by renchili** [comment]
this been reported to my teams today after the upgrade from 5.19.2 to 5.31.3 !
anything we can do 
now we are facing bad reputation in our company facing mattermost

and we find this nothing linked to mattermost server-side
is not even interchange anything with server-side then consumed too much RAM and CPU on WebClient user's browser

Typically the issue is Firefox even cannot move mouse

**Comment by renchili** [comment]
any update on this?

**Comment by ccoenen** [comment]
> any update on this?

One wonders how "text entry" isn't more of a priority for a chat platform...

**Comment by jwilander** [comment]
Hi all, looking into slow typing issues is a big priority for us and we're diving deeper into the investigation right now. We have some recent fixes like https://github.com/mattermost/mattermost-webapp/pull/8092 that have shown some improvement and there's more to come.

We're looking at improving typing performance across all platforms but from a quick read through the read it looks like there might be some more severe issues specific to Firefox. I've created a JIRA ticket for us to go investigate issues on Firefox specifically https://mattermost.atlassian.net/browse/MM-36116.

**Comment by renchili** [comment]
hi  about your so-called  improvement, we have deployed in production env and users' feedback is like this:
> an IM system cannot make the most important things work, how come they dare release new features that called `improvement`

**Comment by jwilander** [comment]
Hi @renchili while we understand these types of issues are frustrating I'm going to ask you to please keep the feedback constructive. As I said above this is a big priority for us and we're working on it but it's also not always an easy one-off fix for a web application as complex as ours is. We'll be making and shipping improvements as fast as we can identify and fix the issues. Some of these improvements will have more or less impact than others but we will be addressing these issues and working them until they're fixed.

**Comment by hjek** [comment]
> anything we can do

@renchili A workaround is to use [GhostText](https://ghosttext.fregante.com/) to edit messages in an external text editor, or you could ask your teams to use the [Mattermost Desktop app](https://github.com/mattermost/desktop/releases) rather than Firefox.

**Comment by renchili** [comment]
Actually, we already tried to use the Mattermost Desktop app on Mac big Sur but it even worse than using chrome Browser
can check it also very stuck and slow:
1 typing 
2 scrolling left side channel list

**Comment by ccoenen** [comment]
> [...] to use the [Mattermost Desktop app](https://github.com/mattermost/desktop/releases) rather than Firefox.

I am struggeling to not write a _very_ blunt answer to that. Here's the least offensive one I could come up with:

If you suggest this, you are breaking the web even more. **You** are actively doing this.

By breaking mattermost in firefox this badly in the first place, you are passively contributing to ever more people switching to chrome. But by suggesting to use something different, even if it's the desktop app (which is electron/webkit) you are going over to _actively_ hurting the web.

Pleas do not do that.

**Comment by stefanct** [comment]
> please keep the feedback constructive. As I said above this is a big priority for us and we're working on it but it's also not always an easy one-off fix for a web application as complex as ours is.

the feedback you should be able to realize from this thread should be pretty clear and actually quite constructive: your complexity is killing you and you broke the most fundamental feature of your application so that your users are borderline insulting you out of despair (I kept myself from posting "you had one job" memes but it crossed my minds several times thinking about this issue). try seeing it from an ordinary user's perspective: we just want to read and write some text messages maybe sparingly interjected with some links or pictures. sure, some fancy text formatting or autocompletions are handy from time to time but it's obviously not worth it if the consequence is that such huge problems like this one arise and remain unfixed for a year. replying by "this is a big priority for us" is as insulting as replies one receives from the first level support of big corporations when they completely fuck up.

IMHO this whole situation is primarily not a technical issue but the symptom of a bigger management issue where "features" are more important than most basic usability. my stakes here are multiple orders of magnitudes lower than yours and even most others' here (i am actually wondering why i am investing that much time) but still i get unbearably frustrated by such replies (ah, right, that's why - i am angry). the complexity and "features" are not a burden imposed by others - no, you (as an organization) chose to implement that and apparently neither manage it properly nor test it sufficiently. the right reaction would be to sit back and discuss refactorings, cleanups, getting rid of the complexity, and management changes so this won't happen again - not trying to find excuses.

however, while that is clearly (to me) the underlying issue, this issue (sic! ;) is the wrong place for discussing the broader base and we should focus on the actual problem at hand. the "any news yet?" messages are equally unhelpful. please stay on topic and those you want to further rant^Wdiscuss about the deeper problems please choose the right channels for that, which is probably the developer or meta forums (but most of it has to happen within the company anyway i guess).

**Comment by jwilander** [comment]
@stefanct I'll be the first to admit that we haven't focused on web app performance enough over the last year. We have to strike a balance between building new features/improvements and paying off technical debt/ensuring performance and we've definitely leaned much too heavily on the building new features side. We are rotating in the other direction now. I'm also not trying to use the complexity of the application as an excuse. It's just a fact that we have to deal with. Sure, we're responsible for what goes into the application but none of those decisions are made in a vacuum. We've got many users and customers who are asking for these things and we also find them personally useful as well. Again, not an excuse, just a fact. The burden is on us to make sure these new additions don't have a negative impact on the performance of the application. In this case, we haven't done a great job at that. There's a number of reasons, or excuses, why that's the case but, yes, it doesn't change the fact of where we are now.

I apologize if you took offence to me saying this is a big priority for us, and yeah, I know, it does sound like that typical big corp "generic go away/deflection response". That's on me. I try to be genuine with my communication and make it come across as such but I'm not always successful. That said, it is a big focus for us. Our Web Platform team has this as the number 1 objective to focus on until it's fixed. We're also working on setting up benchmarks and tests so that we can better track performance issues in the future. For example, there's a [POC here for starting to track our selector memoization effectiveness](https://github.com/mattermost/mattermost-webapp/pull/8189) that's the first step in better performance tracking of the web app. There's also a [PR this morning](https://github.com/mattermost/mattermost-webapp/pull/8222) that is the result of an investigation done by @hmhealey into why typing gets laggy/slow when receiving posts. We'll be discussing these and more changes in [~Developers: Webapp](https://community.mattermost.com/core/channels/webapp) if anyone wants to take part, lurk or wants to help us investigate/fix the issues.

I do appreciate the candid feedback and it's definitely something we need, and want, to hear.

**Comment by hjek** [comment]
> If you suggest this, you are breaking the web even more. **You** are actively doing this.

Hey, easy now on the accusations please, @ccoenen. I only reported this issue, and I'm not a Mattermost employee. I was just sharing two possible workarounds for @renchili, one of which works in Firefox.

**Comment by jwilander** [comment]
Hi all, looking for some help testing to see if a recent fix in this PR https://github.com/mattermost/mattermost-webapp/pull/8302 helps the typing performance on Firefox (and other platforms). Can anyone who's experiencing bad slow typing issues create an account on this server https://mattermost-webapp-pr-8302.test.mattermost.cloud/signup_user_complete/?id=4q1kmpiqrjfkze4pkq1p9mosmc and see if the typing is any better?

**Comment by stefanct** [comment]
I am not sure if anyone would notice on such a tiny server instance, i.e. one without a more significant number of users, channels, or messages. I cannot really tell (compared to a 5.35.1 instance it seems to be a bit better and consistent when just holding down a key in the input field though).

**Comment by kongr45gpen** [comment]
I'm honestly not sure what kind of difference there is, since it's hard to compare servers with different channels, users etc.. (However it's still slower than chrome, at least on Linux)

In case it helps anyone, since it seems that the issues get worse the more elements there are on the page, I sent a bunch of messages on the off-topic channel, so the way I reproduce the slow typing speed is:
1. Search "message" in the search bar
2. The RHS will load 100 messages
3. Start typing a new message normally

**Comment by jwilander** [comment]
Re @stefanct: Yeah, it's hard to test it well without a lot of traffic on the server but I do recall a few people seeing the typing be slow even in an empty channel. Was hoping this might have an impact on that. Thanks for checking and the feedback though!

Re @kongr45gpen: Is it only noticeably slower when there's a lot of elements on screen? For example if you go to an empty new channel is the typing normal and fine? We know the RHS has some performance problems because it's not virtualizing the components it loads. That means even if a component isn't displayed on screen it's still rendered on the DOM. In the center channel we do have virtualization. What shouldn't be happening though is that typing is slow when there's no changes or activity happening in the RHS. @kongr45gpen would you be able to grab me two perf profiles of you typing in an empty channel and also a full channel with the RHS open you like to describe? That would help immensely.

**Comment by kongr45gpen** [comment]
@jwilander Indeed, an empty channel is much faster than a full channel with an open static RHS. (Not sure how related this is to this issue, though)

Here are the two profiles: [firefox_performance.tar.gz](https://github.com/mattermost/mattermost-server/files/6716632/firefox_performance.tar.gz)

**Comment by jwilander** [comment]
Awesome, thanks! That helps confirm that it's likely related to some unnecessary re-rendering or recomputation related to some onscreen components. I'll look through the profiles to see if anything stands out.

**Comment by ocrete** [comment]
Here is another profiling log from Firefox. In this case, I had a "thread" open on the right side and typing in there is painfully slow.
[mattermost-typing.json.gz](https://github.com/mattermost/mattermost-server/files/6786748/mattermost-typing.json.gz)

**Comment by jwilander** [comment]
Thanks @ocrete, that's helpful! Was it a long thread (eg. 50+ replies)? One of the things we're adding right now to the RHS threads is virtualization which will only render the replies in the thread on screen (we already do this in the center channel). This should help a lot with performance in longer threads. @koox00 is working on that right now https://mattermost.atlassian.net/browse/MM-36698.

cc @hmhealey some more performance profiles for us to look at

**Comment by ocrete** [comment]
@jwilander No, the thread was rather short (<10 messages), but I'm in may channels and most of them have large backlogs, but I'm not sure if it matters. I have low performance even in threads with 3 messages, but another thread with 8 messages is even sloewr I think. Actually, in that channel, even typing in the main window is slow for some reason. this is actually slow typing

**Comment by jwilander** [comment]
Hmm interesting. What version are you on? And does your server have a lot of traffic? Eg. lots of people constantly posting in channels you're a member of even if you're not looking at them right now. That's another hotspot that we've identified and have made fixes for recently that will be in the upcoming 5.37 release.

**Comment by ocrete** [comment]
We're on 5.35.4, it doesn't have so much traffic, maybe 150 users, but I think I can see it even when most people are not active.

**Comment by jwilander** [comment]
Thanks, that's helpful. One more question, do you only see the issues on Firefox? Or do they persist on Chrome, other browsers or the desktop app too?

https://github.com/mattermost/mattermost-webapp/pull/8302 should result in some improvement and is currently slated for 5.38. We're continuing to dig into the issues further.

**Comment by ocrete** [comment]
In Firefox, every letter is slow, but in Chrome, many are fast, but then it blocks for some letters.

**Comment by jwilander** [comment]
I've submitted a PR here https://github.com/mattermost/mattermost-webapp/pull/8396 that should hopefully help. @ocrete (or anyone else) would you mind creating an account on the test server for that PR [by going here](https://mattermost-webapp-pr-8396.test.mattermost.cloud/signup_user_complete/?id=yfsamjtey3gr9kamjyaxh8bf1c) and seeing if the typing performance is better? I loaded a bunch of test data onto it to get it closer to a real server. It's not a perfect substitute for a server with real traffic/data but it's a start.

**Comment by kongr45gpen** [comment]
From a very quick test in Firefox, it seems that the performance is order of magnitudes better in the new PR! Compared to a server with an older version, the letters appear to be written instantly, even though the profiler still shows a large number of DOM events.

Note: I typed `@sysadmin` in the search bar to populate the RHS with a number of DOM elements.

**Comment by ocrete** [comment]
I can confirm the same observations here, it's a huge improvement.

**Comment by jwilander** [comment]
That's great to hear! Thanks for the help with the profiles and testing. That really let us narrow down the issue a bunch. After it gets tested for regressions and dev reviewed we'll get that merged. We'll consider backporting it to older versions too.

**Comment by kongr45gpen** [comment]
I've cherry-picked this commit in a used server, with collapsible reply threads enabled, and can confirm the massive improvement in performance as well

**Comment by jwilander** [comment]
Awesome, thanks @kongr45gpen !

For your knowledge and everyone else's on the thread:

There were a couple issues with drafts not persisting correctly after the changes. Fixes for those have been merged now:

* https://github.com/mattermost/mattermost-webapp/pull/8411
* https://github.com/mattermost/mattermost-webapp/pull/8428

We're testing them on community-daily.mattermost.com right now to make sure the regressions with drafts are fixed. After a few more days of that we'll be looking into backporting the fixes to 5.37. The changes will also be included in the 5.38 release next month.

cc @amyblais

**Comment by ccoenen** [comment]
Thank you for the analysis, patch and testing to everyone involved!

**Comment by renchili** [comment]
@jwilander  thanks for the news, but 5.31.x still in life cycle means it will no longer be maintained?

**Comment by jwilander** [comment]
@renchili 5.31.x is still in support until October and we'll be releasing a new version of it with the above fix.

**Comment by WGH-** [comment]
I can confirm that 5.37.1 fixed it for me  👍🏻  (I'm using Firefox).

**Comment by jwilander** [comment]
Thanks @WGH-, that's something we can take a look at. Would you be willing to open a new issue for that with extra details about environment and exactly what you're seeing?

**Comment by discostur** [comment]
Hi,

just upgraded from v5.36.1 (all was good) to v6.1.0 and typing is sometimes really slow. Does anyone else have problems with v6.1.0?

Thanks

**Comment by jasonsmith425** [comment]
Yes, 6.1 feels slower to me as well.

**Comment by dparv** [comment]
We experience this as well on version: 5.39.0. By any change a regression?

**Comment by movy** [comment]
Just began to experience extreme lag when typing on MacOS client Version 5.1.1 (20700) and server Mattermost Version: 7.2.0, 
Never experienced anything like this prior server v7, or even v6, as we skipped several upgrade cycles exactly for similar regression experiences, but eventually had to upgrade due to accumulating security fixes.

**Comment by OtterlyOlive** [comment]
Getting this on MacOS client Version 5.2.2 (26066) & server Mattermost Version: 7.5.1 deployed on Linux.

**Comment by Apteryks** [comment]
@jwilander  Pinging you in case you'd like to review the information here and determine whether this should be reopened.

I'm experiencing the slow text input problem when my Mattermost tab has been opened for a long time (a few hours) in Firefox 102.11.esr (more precisely, GNU IceCat).  All other sites I use are fine, it's just Mattermost that peaks a CPU core processing text input (when the problem is triggered -- in a fresh tab it works fine)

Here's a performance profile obtained with Firefox Profiler while the input was sluggish (multiple seconds delay): https://share.firefox.dev/3qElZmg.  This is with Mattermost 7.10.2.

**Comment by jwilander** [comment]
Thanks @Apteryks for the report. Have you experienced it on any other browsers or the desktop app?

@hmhealey @M-ZubairAhmed weren't one of you chasing down a memory leak recently? I wonder if that could be related.

**Comment by Apteryks** [comment]
@jwilander sorry, I have only used Mattermost in GNU IceCat (a variant of Firefox ESR).  I can put it to the test in Chromium and report back.  The problem hasn't appeared since disabling notifications, and doesn't appear to be related to a memory leak.  It's related to javascript on the critical input path when desktop notifications are enabled, somehow, as hinted by the profile dump linked above.

**Comment by hmhealey** [comment]
From what we've found, the major leak was fixed a few months back when we fixed the WebSocket reconnect handlers were getting doubled (or more) up. That's the one that was causing the app to lag heavily or crash when the computer when the WebSocket reconnected (usually when the computer came back from sleep).

We're not aware of any other memory leaks at the moment outside the general buildup of data in the web app since we don't have any sort of garbage collection for data loaded from the server

**Comment by Apteryks** [comment]
I haven't seen the problem in Chromium (actually, `ungoogled-chromium` as packaged in GNU Guix), with desktop notifications enabled.  So it seems the problem only affects Firefox ESR with notifications allowed.

**Comment by milesrichardson** [comment]
This laggy typing is an issue for me in the macOS App. In About -> Mattermost, I see: `Version 4.6.1 (4.6.1.7401)`. Maybe relevant, I have two servers open in the app.

Is there something specific I should look for in DevTools and/or its profiler? Here's what I see while typing a single message:

![image](https://github.com/mattermost/mattermost/assets/835921/7d551601-f01a-40ca-9e2a-3da7d9ad9ddb)

**Comment by VincentSC** [comment]
Why was this issue closed? It's far from solved!

**Comment by lieut-data** [comment]
Hi @VincentSC, this issue is over two years old. If you're seeing something in a recent build, could you open a new ticket with reproduction steps? Thanks!

**Comment by desrod** [comment]
I can confirm this also affects the standalone, Electron mattermost-desktop client on Linux. It's quite obvious, has the look and feel of a 'keylogger' capturing and logging keystrokes in real time (not implicating that, but the behavior is similar).
