### ISSUE TITLE
No desktop or mobile notifications in direct messages involving more than 2 participants

### ISSUE THREAD

**Issue by rtadros-Galois** [mattermost/mattermost-server#15198]
#### Summary
I don't receive desktop or mobile notifications in direct messages involving more than 2 participants.

#### Steps to reproduce
Happens on both desktop (v.5.22.2 on Google Chrome) and iOS (version 1.33.1). 

#### Expected behavior
Receiving direct message notifications even when the message has more than 2 participants.

#### Observed behavior (that appears unintentional) 
I get notifications when mentioned, and direct message notifications when it's just me + someone else. If the message has > 2 people, I don't receive notifications.

#### Possible fixes
N/A

**Comment by amyblais** [comment]
@rtadros-Galois This sounds to be expected behavior. On Group Message channels you only get a notification for messages where you are mentioned. If you want notifications for all messages in the channel, then you can go to the channel header > Notification preferences > Send desktop notifications > For all activity.

**Comment by rtadros-Galois** [comment]
Aha. Didn't know that the notifications are disabled by default for group messages.
