### ISSUE TITLE
Sidebar: Categories are being duplicated

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#15273]
After updating to .26 and starting use of categories, I'm finding problems with duplications of default categories such as "FAVORITES" and even "CHANNELS":

Example, "FAVORITES" is duplicated with identical contents on both:
![image](https://p153.p0.n0.cdn.getcloudapp.com/items/eDuBPdL2/2020-08-16_23-53-34.jpeg)

"CHANNELS" is a little different. It is listed twice, but the contents are missing entirely in the second one.

**Comment by amyblais** [comment]
@ylluminate I think this was fixed for v5.26 but seems to be still happening. Are there any other repro steps or server log errors you can help share to diagnose this issue?

//cc @hmhealey

**Comment by hmhealey** [comment]
There probably wouldn't be anything in the logs, but I could use some more details to figure out what might've caused this.

1. Are you running Mattermost EE or TE? If you have EE, are you running multiple servers in a cluster?
2. Is this affecting all users on your instance or just you?

**Comment by Ndrou** [comment]
Same issue appears in 5.32.1 for us for one user only...

**Comment by hmhealey** [comment]
@Ndrou What version did they first have the issue on?

As far as I'm aware, that shouldn't happen any more for anyone that first used the new sidebar in 5.29 or greater, but the new fixes unfortunately don't affect anyone who were affected by the bug before then. The best we have for fixing it for people previously affected is that I can give you some SQL queries to clear their sidebar so that it'll be reset the next time they reload the app.

**Comment by Ndrou** [comment]
@hmhealey
The issue appeared in 5.32.1 but just for one user.
After investigation, i think that a migration has created duplicates in database for this user, we just removed these duplicates in database and everythink is OK now.

**Comment by hmhealey** [comment]
Glad to hear it! Hopefully it was just a one-off issue since newer migrations are able to use the database to prevent duplicates by using predetermined IDs for those categories. Definitely let us know if it comes up again.

I'm going to close this issue since we should've closed it back when we added the fix for it previously. Feel free to reopen if necessary though.

**Comment by ylluminate** [comment]
This is still happening in `5.33.2` consistently for multiple users for us. Can you please advise as to the steps you took to resolve this @Ndrou?  

This has been plaguing us since last August.

**Comment by hmhealey** [comment]
It can be fixed on a per-user basis by deleting all of the sidebar information from the database for each affected user. This'll delete all of one user's custom categories and any changes they may have made to other categories so that the initial Favorites/Channels/DMs categories will be recreated the next time they open Mattermost.

```sql
start transaction;
delete from sidebarcategories where userid in (select id from users where username = 'USERNAME');
delete from sidebarchannels where userid in (select id from users where username = 'USERNAME');
commit;
```

We unfortunately couldn't fix it for existing users automatically, but changes made in 5.29 will prevent it from affecting anyone that wasn't already affected by this before.

**Comment by ylluminate** [comment]
So I'm coming back to this issue again.  Wiping out all of the user's sidebar custom categories is not really an option. At least a couple users are just too highly customized to deal with the backlash that this will cause. Interestingly this duplication of the "FAVORITES" category is only present on one or two of the teams the users are in. How can this be handled in a more limited fashion so as to remove it from that one specific team?

**Comment by ylluminate** [comment]
Alright, so I went ahead and dug into the situation via a graphical database editor and isolated the issue down via finding the `UserId` and `TeamId` elements of the affected users. I then filtered these further down such that I would only show the rows of these limited user and team IDs within the `SidebarCategories`. Upon doing this I found the duplications clearly enough and deleted the duplicated rows that were in the wrong order / clearly duplicated.

This appears to have resolved the issue... Hopefully I didn't break anything else by doing this that might be somehow associated...

**Comment by hmhealey** [comment]
Removing the duplicate ones manually should be totally fine, but make sure to clean up any SidebarChannels that might've ended up in those categories since it might cause those channels to be missing from the sidebar.

Let us know if there seems to be any trends among the duplicated channels. Unfortunately, we haven't had any other reports of it, so it's been hard to investigate any outstanding issues. Hopefully those are just left over from an older version since the ID field for those categories will look different when created in newer versions since it's now derived from the other fields for non-custom categories.
