### ISSUE TITLE
Major headaches with advisor-bar

### ISSUE THREAD

**Issue by grajsor** [mattermost/mattermost-server#15349]
#### Summary
Unable to disable intrusive and annoying advisor-bar

#### Steps to reproduce
Hit F5 (refresh) to see it, every time.

#### Expected behavior
Previous non-intrusive and enjoyable UI.

#### Observed behavior (that appears unintentional) 
Irritation, frustration, annoyance.

#### Possible fixes
Let us disable advisor-crap.

**Comment by WhatlsGoogle** [comment]
Could not agree more.

**Comment by amyblais** [comment]
Does the notification stop after you have clicked Contact Us?

**Comment by grajsor** [comment]
> Does the notification stop after you have clicked Contact Us?

No. It also spams in PM:s as "Mattermost Advisor" once a day, on top of the annoying bar on refresh.

**Comment by dfun90** [comment]
Posted a question if there's a way to disable it on the Mattermost Server, but yea, I know that you guys need to make some money with Mattermost, but there should be a way to deactivate the information banner and daily message from the Mattermost Advisor suggesting to upgrade to the Enterprise license. It's a bit annoying. (Also, pitching to my boss to spend $60k annually (for our existing user count with the E20 license) isn't the easiest of tasks, even if the E20 provides a lof of nice things.)

My suggestion would be to show this advisory information only once when the user count is reached and then let the server admin have an option like "Don't show again" or "Remind me again later".

**Comment by esadur** [comment]
Hi all. I’m working with the team to track down bugs and make some updates to the advisor. After the updates, window refreshes won’t cause the banner to reappear, and the advisor bot will send a single message.

If you click “Learn more” and then “Contact us”, the notifications should stop. If they do in fact reappear, let us know—we’ve heard some reports of this but haven’t been able to reproduce the issue. Having server logs will help us debug: when the notification reappears, go to the menu > System Console > Server Logs. Then, in the banner, click “Learn more” and then “Contact us”. If the banner still doesn’t disappear, send us the server logs and we’ll take a look.

**Comment by davebarkerxyz** [comment]
We do understand that clicking "Contact us" would stop the messages but I don't believe this is an appropriate solution for an open source product (with, according to GitHub, 552 contributors).

We chose Mattermost Team Edition precisely because it's open source and free of any commercial pressure. I understand that Mattermost, Inc (who, by far, contribute the most to the project) may need some way to attract sales in order to stay afloat but this sort of nagging has the exact opposite effect and erodes the trust I have for the company and developers. It makes me far less likely to pitch this to our budget holders. If our MySQL servers emailed me daily and the only way to stop it was to share my email address with Oracle in order to invite some sales calls, I'd almost certainly just migrate all of our servers to PostgreSQL.

My organisation uses both Mattermost and Microsoft Teams. My team are staunch advocates of libre software and the open source philosophy and would prefer to promote Mattermost within the department over Teams.

The choice seems to be between sharing my personal data (email address) and ending up in the sales funnel or putting up with nag messages every day. This is terrible.
