### ISSUE TITLE
Github: Release tagged as "latest"

### ISSUE THREAD

**Issue by jangrewe** [mattermost/mattermost-server#15350]
#### Summary
I'm not sure what causes this, but for some reason the "latest" tag of the Github releases (https://github.com/mattermost/mattermost-server/releases) keeps being changed and for a couple of days now doesn't point to the actual latest release.

This might seem trivial to you, but i have automation in place that alerts me on new releases for various Github projects, and i keep getting notified that Mattermost (and only you guys) have a new release, which is actually older than then actual latest release.

#### Steps to reproduce
-

#### Expected behavior
The actually latest release is tagged as "latest"

#### Observed behavior (that appears unintentional) 
The "latest" tag keeps jumping between the latest and some previous release.

#### Possible fixes
Make sure that the latest release is tagged as "latest".

**Comment by amyblais** [comment]
@metanerd / @jaydeland Is this expected / unexpected?

**Comment by jaydeland** [comment]
I don't believe so, we will have to investigate

**Comment by amyblais** [comment]
@jaydeland Would you like me to open a ticket for this, and if yes, which team?

**Comment by jaydeland** [comment]
@amyblais - I was wrong, this is expected according to GitHub: https://developer.github.com/v3/repos/releases/#get-the-latest-release

**Comment by jangrewe** [comment]
But if you cherry-pick into past releases, then, as the name implies, those are still past releases and not the latest release. 
It is also my understanding that by modifying an existing release, that release should get a patch level version increment, as it is not the same version you released under that version number.

**Comment by metanerd** [comment]
@jangrewe what you say is correct. Still the `created_at` date of the commit for the past release is newer than the latest release's `created_at` date. So this is technically correct, but not intended this way. 

Since there will be a revision coming up for our release process, this shouldn't happen anymore afterwards. Please kindly bear with us till then.

**Comment by jangrewe** [comment]
@metanerd Hey Eli, nice to see you at your new job ;-)

Thanks, i'll silence my alerts for this repo and will check manually for now.

**Comment by jangrewe** [comment]
@metanerd Sooo... as i just got notified that the new version v5.37.5 got released, even though i'm already running v6.1.0, i'm guessing that the new release process was either not yet revised, or the revision did not address this issue? 😉

**Comment by metanerd** [comment]
@jangrewe Thank you for coming back to this! The redesign did not address this issue. This is an issue with GitHub promoting the release with the latest git commit time as the latest release. This happens when release branches are patched (cherry-picked) with bug fixes / security fixes. Other projects, namely kubernetes is running into the same behavior (https://github.com/kubernetes/kubernetes/releases). If you wish for different behavior, I suggest opening a GitHub GitHub issue.
