### ISSUE TITLE
GitLab URL is hard coded in translation message

### ISSUE THREAD

**Issue by leipert** [mattermost/mattermost-server#15634]
#### Summary
Mattermost hard codes GitLab.com in error message when it should point to the GitLab Auth server used.

#### Steps to reproduce

1. Use A GitLab that is not gitlab.com for authentication (e.g. http://example.com)
2. Get a Terms of Service error because that instance requires accepting new Terms of Service
3. The error reads:

```
GitLab's Terms of Service have updated. Please go to gitlab.com to accept them and then try logging into Mattermost again.
```

#### Expected behavior

```
GitLab's Terms of Service have updated. Please go to example.com to accept them and then try logging into Mattermost again.
```

#### Observed behavior (that appears unintentional) 

A user confused by this reported it in the GitLab bug tracker: https://gitlab.com/gitlab-org/gitlab/-/issues/212179

#### Possible fixes
Interpolate the URL in Translation key: `oauth.gitlab.tos.error`: https://github.com/mattermost/mattermost-server/blob/50e37068b5f50d365c39bb2508a59aed10a77912/i18n/en.json#L7665-L7668

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-29123

**Comment by haardikdharma10** [comment]
Hey @amyblais, I would like to take up this. Can you assign this to me and add the necessary labels as well, if possible :)

**Comment by haardikdharma10** [comment]
@amyblais, Hi, Sorry for not being able to stay on top of this. Can you tag someone who can help me out here? I just need more clarity about what url we exactly need to interpolate here?

**Comment by amyblais** [comment]
@leipert @grundleborg Perhaps you can help with the question ^

**Comment by leipert** [comment]
@haardikdharma10 I don't know exactly, but looking around, it likely has something to do with the `GitLabSettings`, maybe it is accessible somehow from the sso object?

https://github.com/mattermost/mattermost-server/blob/96f1739f8f9d9a934c815bdf11f06a7e1eaacd09/app/oauth.go#L758-L883

**Comment by umlaeute** [comment]
I can only second this.
We recently added Terms-of-Use to our self-hosted gitlab/mattermost instance, and people are highly confused, resulting in them not being able to log into mattermost any more.

while you are at it: i think the reference to *GitLab* itself (in "GitLab's Terms of Service have updated") is also misleading, as many people will associate "GitLab" with the service (that is: gitlab.com instance) rather than the software (that is running on-premises).

i wouldn't mind having to configure both the URL and the service name in the plugin configuration (gitlab-integration plugin in mattermost).
come to think of if: the plugin configuration already includes a `gitlaburl` field, that looks like a good candidate for getting the URL from.

**Comment by haardikdharma10** [comment]
> I can only second this.
> We recently added Terms-of-Use to our self-hosted gitlab/mattermost instance, and people are highly confused, resulting in them not being able to log into mattermost any more.
> 
> while you are at it: i think the reference to _GitLab_ itself (in "GitLab's Terms of Service have updated") is also misleading, as many people will associate "GitLab" with the service (that is: gitlab.com instance) rather than the software (that is running on-premises).
> 
> i wouldn't mind having to configure both the URL and the service name in the plugin configuration (gitlab-integration plugin in mattermost).
> come to think of if: the plugin configuration already includes a `gitlaburl` field, that looks like a good candidate for getting the URL from.

@leipert thoughts?

**Comment by joshgay** [comment]
We were having this same issue on the IEEE SA Open [mattermost instance](https://opensource-connect.ieee.org opensource.ieee.org) which authenticates to [our gitlab instance](https://opensource.ieee.org). 

My perspective was that it would be nice if gitlab returned in its error message with the correct URL so that mattermost (or any other service using gitlab for authentication) could just pass the error message along to the user. 

I made this change and it recently got [merged into gitlab](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/75082). 

Newer versions of gitlab should now return an oauth error that includes the URL. 

Should the code be updated in such a way that it tries to catch if it is the newer error message for the use case of Terms of Service not accepted and if so, pass along the error message from gitlab and otherwise pass along a friendly message that attempts to guess the correct sign-in URL? If so, I would be happy to attempt to write this code. Please advice.

**Comment by agnivade** [comment]
To anyone looking to pick this up,

**Comment by KushalBeniwal** [comment]
Hi @amyblais, I would like to work on this issue!
