### ISSUE TITLE
[Bleve] massive index size compared to indexed data size

### ISSUE THREAD

**Issue by XANi** [mattermost/mattermost-server#16051]
Our test instance posts table is tiny:
```
    table_schema    |       table_name        | row_estimate |   total    |   index    |   toast    |   table    
--------------------+-------------------------+--------------+------------+------------+------------+------------
 public             | posts                   |  1.09842e+06 | 810 MB     | 489 MB     | 208 kB     | 321 MB
 public             | audits                  |  2.55851e+06 | 560 MB     | 221 MB     | 8192 bytes | 339 MB
```
yet Bleve index blew past 10GB and ran VM out of space:

![image](https://user-images.githubusercontent.com/147394/96721943-1e169b00-13ad-11eb-9c50-d044705254b2.png)

**Comment by mschoch** [comment]
I don't really have any context for this, and only saw it via a google alert, but it seems that indexes are created using the method `bleve.New` here:

https://github.com/mattermost/mattermost-server/blob/master/services/searchengine/bleveengine/bleve.go#L117

And this uses the default indexing scheme, which (due to backwards compatibility issues) is quite old.  If the size of the index is important, we recommend creating indexes with the `scorch` type, and also one of the newer `zap` file format versions.  Some more information can found here (although the latest zap is now 15): https://github.com/blevesearch/bleve/issues/1186#issuecomment-615335353

Obviously this may not be a simple change, as it potentially leads to backwards compatibility issues for this project as well...

**Comment by mgdelacroix** [comment]
Thanks @XANi for the report, and thanks a lot @mschoch for jumping in!

I've created [a ticket to investigate](https://mattermost.atlassian.net/browse/MM-29916) the implications of the migration to scorch indexes. After some quick tests it looks like the code change is minimal and the improvements on index size are huge, so the challenge here will be to decide what do do to migrate existing servers to the new indexes.

**Comment by dpanic** [comment]
Hi @mgdelacroix any update about this? 
I am also facing situation where I have 1.4GB of Posts data and 8GB Bleve indexes

**Comment by mgdelacroix** [comment]
Apologies for the late response @dpanic. I'm currently working on a PR to change the indexing method and update Bleve to v2. You can track the progress in the above ticket
