### ISSUE TITLE
Unread Filtering by Categories Back

### ISSUE THREAD

**Issue by andresbase** [mattermost/mattermost-server#16533]
I have noticed with the latest update on our Mattermost that it went from keeping the grouping of messages to not keeping it.

What I mean is previously when clicking on "Filter by unread" I would obviously only see unread messages but listed and grouped by favourites and other groups I created. This was incredibly useful, specially if you are in an organization large enough that there are many channels. It allows me to quickly check the more relevant channels and not having to scan the whole list to find what I need.

However now it will only list all of the unread messages uncategorized. This might seem like a small change but this has a big impact in easiness of use. 

From the changelog this is put as an improvement "Improved filter control for the new channel sidebar to show unread channels without categories." 

I can't understand why throwing all your unread channels with in one place without categories would be considered an improvement over still offering people to have their categories. I might have missed this discussion before and sorry if it has already been discussed extensively.

Thanks

**Comment by hmhealey** [comment]
Thanks for the feedback. I'll pass it along to our UX team.

I think the intent of the new feature was to just show the user's unreads in a way that prioritized things that were more urgent because they were newer or were mentions. I think it might have also been an attempt to differentiate the filter since previously, it was basically the same as collapsing each category temporarily.

On that note, have you tried collapsing categories you care less about to hide the read channels? I know we've had some discoverability problems there, but it's intended to be a way to let you hide less busy channels without having to leave them. Collapsed categories are also saved on that client, and they'll eventually be synced between devices in the future.

**Comment by andresbase** [comment]
Hi, thanks for the suggestion. I think you are right, collapsing the categories gives me what I needed and filters them by unread. I quite like that. Thanks!

**Comment by hmhealey** [comment]
Awesome, glad that works for you then! I'll leave this open for a few more days to see if anyone else has any other feedback along these lines and then close it if there's no other discussion on it. Thanks again for the feedback though since that was something we were a bit concerned about.
