### ISSUE TITLE
Use boolean values instead of strings in the "client config".

### ISSUE THREAD

**Issue by mkraft** [mattermost/mattermost-server#16802]
#### Summary

The Mattermost "client config" [as defined as a Typescript type named `ClientConfig` in mattermost-redux](https://github.com/mattermost/mattermost-redux/blob/master/src/types/config.ts#L6-L178) contains a lot of values that should be defined as `boolean` but instead are defined as `string`. For example, `CloseUnusedDirectMessages` [is correctly defined as `boolean`](https://github.com/mattermost/mattermost-redux/blob/master/src/types/config.ts#L305) in `ServiceSettings` [but not in `ClientConfig`](https://github.com/mattermost/mattermost-redux/blob/master/src/types/config.ts#L25).

As a result, there's [boolean logic performed against strings in the webapp](https://github.com/mattermost/mattermost-webapp/blob/master/components/user_settings/modal/index.ts#L17).

The goal of this help wanted ticket is to update all of those type definitions in `ClientConfig` and adjust all of the corresponding logic throughout the webapp.

This is the front-end portion of https://github.com/mattermost/mattermost-server/issues/16839.

----
If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

**Comment by haardikdharma10** [comment]
Hi @mkraft, I will try to fix this one:)

**Comment by mkraft** [comment]
> Hi @mkraft, I will try to fix this one:)

Sounds great @haardikdharma10! Please let me know if/how I can help. Thank you! :)

**Comment by haardikdharma10** [comment]
Hi @mkraft, In `src/selectors/entities/preferences.ts` on [Line 259](https://github.com/mattermost/mattermost-redux/blob/master/src/selectors/entities/preferences.ts#L259) when I change it from this:

`if (!config.CloseUnusedDirectMessages || config.CloseUnusedDirectMessages === 'false')`

to this:

`if (!config.CloseUnusedDirectMessages || config.CloseUnusedDirectMessages === false)`

it raises the following error : 

`This condition will always return 'false' since the types 'true' and 'false' have no overlap. `

Do you think it should have been ==='true' instead? To which, I should change it to ===true?

**Comment by xlanor** [comment]
> Hi @mkraft, In `src/selectors/entities/preferences.ts` on [Line 259](https://github.com/mattermost/mattermost-redux/blob/master/src/selectors/entities/preferences.ts#L259) when I change it from this:
> 
> `if (!config.CloseUnusedDirectMessages || config.CloseUnusedDirectMessages === 'false')`
> 
> to this:
> 
> `if (!config.CloseUnusedDirectMessages || config.CloseUnusedDirectMessages === false)`
> 
> it raises the following error :
> 
> `This condition will always return 'false' since the types 'true' and 'false' have no overlap. `
> 
> Do you think it should have been ==='true' instead? To which, I should change it to ===true?

I'm still in the middle of familiarising myself with the code base, but when looking at this isolated line of code, it seems that previously, the config could return either a `boolean` or `string`.

The original code is simply checking for whether it is either a boolean false or a string false. In that case, what I would do here would be to ensure that the type in `CloseUnusedDirectMessages` has been switched to a boolean type, and then simply do `if (!config.CloseUnusedDirectMessages)`.

**Comment by haardikdharma10** [comment]
Hi @xlanor, thanks for taking a look at this. However, when discussed with @mkraft offline, we came to the same conclusion as well :)

**Comment by hmhealey** [comment]
Echoing my comment from https://github.com/mattermost/mattermost-redux/pull/1348 here for visibility:


We discussed this a bit more internally, and there's some bigger issues we discovered since changing the type in the redux state will break all plugins relying on the config only containing strings. We still need to figure out how what parts of mattermost-redux we want accessible by plugins and how we can do that to best ensure backwards compatibility, so we're going to close these tickets for the time being while we sort that all out. We don't have a specific timeline for that yet, but that will likely involve breaking changes, so it would be a good time to break this for as well.
