### ISSUE TITLE
replace AppError return param with error

### ISSUE THREAD

**Issue by mahmud2011** [mattermost/mattermost-server#16936]
`*AppError` implemented `error` interface but in several places explicitly `*AppError` is used as return param instead of `error`.

For instance:

https://github.com/mattermost/mattermost-server/blob/master/model/channel.go#L207

```go
func (o *Channel) IsValid() *AppError
```

Should be
```go
func (o *Channel) IsValid() error
```

**Comment by mahmud2011** [comment]
cc: @agnivade

**Comment by mahmud2011** [comment]
I would like to work on it if everyone agrees with the proposal.

**Comment by jespino** [comment]
@mahmud2011 Thanks for the PR, I really like the approach, the problem is, that is a backward incompatible change, because our `model` package is part of our public API, specially because is used as part of our official go client library.

We have plans to remove that in the future whenever we break the backward compatibility, but for now is not possible.

Actually, we recently did exactly that change in all our `store/` code (what is an internal API), and for some `services/` packages too.

**Comment by agnivade** [comment]
Thank you for taking the time to look through our API and spot these! It's very appreciated @mahmud2011 ! It is exactly what @jespino said. We cannot touch the model packages until we do a major version bump.
