### ISSUE TITLE
URLs entered in chat are missing the * at the end of the URL

### ISSUE THREAD

**Issue by Tragen** [mattermost/mattermost-server#17189]
#### Summary
The URL I enter in the chat window doesn't catch a * at the end.

#### Steps to reproduce
Enter both URLs in a chat
http://www.example.org/?x=a
http://www.example.org/?x=*

This is a real problem in e.g. xwiki where the search text is the last one in the URL.
When you enter * to search for everything, the * is missing when you copy paste this URL
https://www.xwiki.org/xwiki/bin/view/Main/Search?sort=score&sortOrder=desc&highlight=true&facet=true&r=1&f_type=DOCUMENT&f_locale=en&f_locale=&text=*

#### Expected behavior
The * is part of the URL

#### Observed behavior (that appears unintentional) 

![image](https://user-images.githubusercontent.com/1700241/111760895-85bf0c80-889f-11eb-9d59-08171afb47ea.png)

**Comment by Tragen** [comment]
Interesting to see here that Github is missing the * also

**Comment by amyblais** [comment]
@hmhealey Do you if this is a bug or "expected" as the same happens in Github?

**Comment by Tragen** [comment]
For me it's a bug, even when GitHub has the same one.
It's a valid URL

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-34133

**Comment by ThiefMaster** [comment]
Isn't the general solution to wrap such URLs containing weird characters in `<>`? `<http://www.example.org/?x=*>` works fine on both GitHub and Mattermost.

**Comment by hmhealey** [comment]
Generally, I'd defer to GitHub for how to handle cases like this. Capturing asterisks as part of the URL automatically can cause problems since it potentially conflicts with other Markdown. For example, is `*here is http://www.example.org/?x=*` an italicized sentence with a link to `http://www.example.org/?x=` or is the first asterisk a literal?

In this case, I think using an explicit Markdown link either with `[url](link)` or angle brackets would be the proper way to post that link.

**Comment by Tragen** [comment]
`*here is http://www.example.org/?x=*`
looks wrong.
Should be written italicized as
`*here is http://www.example.org/?x=* *`
The * is part of the url. Why stop without a space if it's a URL?

**Comment by hmhealey** [comment]
No, unfortunately, we can't just go until the next space because people could use a URL in a sentence

> Go visit www.example.com.

or in brackets

> Go to our site (www.example.com)

and we don't want to capture the trailing punctuation or brackets for those either. Unfortunately, URLs can contain a lot of characters that can cause conflicts with Markdown parsing if they're not percent-encoded. Even with ones we do support like brackets, we've struggled a lot to handle some difficult cases like properly matching URLs containing brackets inside of brackets (like https://en.wikipedia.org/wiki/Disambiguation_(disambiguation)).

Since automatically detecting links is hard, I think our best bet is to use more explicit linking for those.

**Comment by lieut-data** [comment]
@hmhealey, given GitHub and Mattermost match here (as seen below in the ticket description), should we resolve this as won't fix at this time and potentially revisit this when we overhaul our Markdown support?

<img width="196" alt="image" src="https://user-images.githubusercontent.com/1023171/112990856-e4f10c80-913c-11eb-92d1-54473c812c4e.png">
