### ISSUE TITLE
Froward message !!!

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#17408]
my dear friends
Please resolve the message forwarding item as well
Because we need it so much...
@tbalthazar @lurcio @mauricio @cored

**Comment by tbalthazar** [comment]
@majidit curious why you're pinging me on this?

**Comment by ahmaddanialmohd** [comment]
Hi, @majidit 

While I noticed that you have already brought this up in the [Ask R&D](https://community.mattermost.com/core/pl/z7qmhh4jniy7pbkzqo79pi6pma) channel, I want to know what do you actually mean specifically by message forwarding. Does that mean forwarding posts to other channels while retaining the same post in the original channel or moving the post completely from one channel to another?

**Comment by majidit** [comment]
Hi @ahmaddanialmohd 
Yes ...
forwarding posts to other channels while retaining the same post in the original channel.

**Comment by amyblais** [comment]
We have a Wrangler plugin that you could try out for this: https://github.com/gabrieljackson/mattermost-plugin-wrangler.

**Comment by majidit** [comment]
We have installed this plugin
But it is very difficult to work with

**Comment by ahmaddanialmohd** [comment]
Hi, @majidit 

Got it. While the Wrangler plugin is not something in favor with, may I know what difficulties that you faced while working with it? 

* Is it because it fully wrangles the text to another channel without retaining the original post in the origin channel?
* Any other reasons that you can share here?

Meanwhile, you can raise this up as a suggestion in the [Mattermost Uservoice](https://mattermost.uservoice.com/forums/306457-general) as well to see if the rest of the community have some additional thoughts on this too.

**Comment by majidit** [comment]
When I click On attach to thread ...
in sidebar show attaching message and say ....

But in a thread i can't see dropdown !!!

![Capture1](https://user-images.githubusercontent.com/29058805/115658669-76275d80-a34e-11eb-974a-0d1a477c0805.PNG)

**Comment by majidit** [comment]
Hi @ahmaddanialmohd 


The problem is that we do not know how to deal with it
Please send me a video guide

**Comment by majidit** [comment]
Can this plugin be used to send to a person?
