### ISSUE TITLE
Wrong server upgrade

### ISSUE THREAD

**Issue by tsabi** [mattermost/mattermost-server#17426]
I installed mattermost team edition with the official installation steps.
After i upgraded the server (using the official upgrade insturctions) to the version 5.31.2 the about page shows this:

![image](https://user-images.githubusercontent.com/210099/115037393-b3af6500-9ece-11eb-8d1d-d3db7d91d0f4.png)

When i started the new android client (V1.42) it shows an error message to upgrade to version 5.31.

It is very strange, i tryed to restart the server several times, but it still shows the database version as 5.30..

Please help, what i do wrong.
Thanks in advance!

**Comment by amyblais** [comment]
This is a [known issue listed in v5.31 changelog](https://docs.mattermost.com/administration/changelog.html#id32). It is a visual bug and has been fixed in subsequent releases,

**Comment by tsabi** [comment]
Dear @amyblais !
Ok, but after the android mobile app shows a warning that i use a wrong version of the server, this is not a cosmetic bug anymore.

**Comment by tsabi** [comment]
![Screenshot_20210416-221122_Mattermost](https://user-images.githubusercontent.com/210099/115079102-f38f4000-9f00-11eb-8c7c-5e72bbc52dcb.png)

**Comment by amyblais** [comment]
@tsabi What Mattermost server version does your mobile app show in "About Mattermost"?

**Comment by tsabi** [comment]
@amyblais yes it shows every time i start the app.

This is what the app shows:

![Screenshot_20210416-233548_Mattermost](https://user-images.githubusercontent.com/210099/115086482-9ef1c200-9f0c-11eb-9594-07dc8725d23b.png)

**Comment by amyblais** [comment]
@migbot @enahum @josephbaylon This may need a dot release if it's a bug ^

The reporter's server version is correct (v5.31) because there is a [known (visual) bug in v5.31 where the database schema in About Mattermost modal shows as v5.30](https://docs.mattermost.com/administration/changelog.html#id32).

**Comment by enahum** [comment]
@amyblais the bug is not the mobile app is the server reporting the wrong version!

As a work around you could update the schema version in the database I think.

**Comment by cooperfellows** [comment]
We are seeing the same warning on our end in the Android App:

**Desktop About Screen**
![image](https://user-images.githubusercontent.com/6798541/115239509-d4ed9c80-a0ec-11eb-844f-8a344eb19408.png)

**Mobile About Screen**
![image](https://user-images.githubusercontent.com/6798541/115239729-0c5c4900-a0ed-11eb-85c8-9a62e72f3c4e.png)

**Comment by amyblais** [comment]
Servers need to be on v5.31.3 because [v5.31.3 fixes an issue where the server version was reported as v5.30.0](https://docs.mattermost.com/administration/changelog.html#release-v5-31-esr).

Mobile app changelog has been updated with the details https://docs.mattermost.com/administration/mobile-changelog.html, and we have pushed a v1.42.1 dot release to the app stores that clarifies the minimum supported version in the in-app notice. It should be available for download soon.
