### ISSUE TITLE
Mattermost RTL plugin

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#17438]
Hello to all dear friends
We use the Mattermost RTL plugin
Because we use Persian language
This plugin is very good
But how nice it would be if the user image was also displayed on the right

![Image Pasted at 2021-4-18 08-43](https://user-images.githubusercontent.com/29058805/115192229-c78ddd80-a0ff-11eb-8d32-8c15a1842a66.png)

**Comment by jasonblais** [comment]
Hi @majidyazdani, welcome to the Mattermost community!

I noticed you've recently engaged with the community by opening issues for bug reports and feature ideas - that is great!

I recommend reviewing our community systems for bugs, feature ideas and troubleshooting to get the right help in the right place: https://docs.mattermost.com/process/community-systems.html

Moreover, when filing a new issue for a bug report, please make sure to include the following:
- Summary: Issue in one concise sentence
- Steps to reproduce: How can we reproduce the issue (what version are you using?)
- Expected behavior: Describe your issue in detail
- Observed behavior: What did you see happen? Please include relevant error messages and/or screenshots
- Possible fixes: If you can, link to the line of code that might be responsible for the problem

Thanks again for joining the community! If you have any questions, don't hesitate to let us know :)
