### ISSUE TITLE
"Unsupported server version" warning appearing erroneously on mobile app startup

### ISSUE THREAD

**Issue by WorLord** [mattermost/mattermost-server#17436]
#### Summary
A recent upgrade to the iOS and Android clients make the client display the "Unsupported server version" warning on startup, requesting at least server 5.31.  We are using server 5.31.2.  

#### Steps to reproduce
Use server version 5.31.2, and upgrade your mobile app to the latest.  

#### Expected behavior
App starts up and does not display this warning.

#### Observed behavior (that appears unintentional) 
Warning is shown every startup of the mobile app

#### Possible fixes
Haven't looked at the code.

**Comment by amyblais** [comment]
@WorLord It seems that the server reporting the wrong version. Are you able to update the schema version in the database?

**Comment by amyblais** [comment]
@WorLord @tsabi There was a build automation issue in v5.31.0 that caused the server to report a wrong version, but this was later fixed in v5.31.3 (I will update the changelog). Does upgrading to v5.31.3 resolve the issue?

**Comment by Djinada** [comment]
> Does upgrading to v5.31.3 resolve the issue?

Hi, we are currently experiencing the same issue with iOS and Android. Updating the server to version v5.31.3 did fix the DB Schema version but not the issue with the mobile application. Any other suggestions? By the way, non-admin accounts receive the Unsupported server version error while I receive a JSON Parse Error: Unexpected identifier "undefined".

**Comment by amyblais** [comment]
Servers need to be on v5.31.3 because [v5.31.3 fixes an issue where the server version was reported as v5.30.0](https://docs.mattermost.com/administration/changelog.html#release-v5-31-esr).

Mobile app changelog has been updated with the details https://docs.mattermost.com/administration/mobile-changelog.html, and we have pushed a v1.42.1 dot release to the app stores that clarifies the minimum supported version in the in-app notice. It should be available for download soon.
