### ISSUE TITLE
Empty block space under Favorites

### ISSUE THREAD

**Issue by camaer** [mattermost/mattermost-server#17648]
#### Summary
Since 5.33 or 5.32, I can't remember exactly, an empty block (space ?) appeared underneath my Favorites Channel section. I can move the block around but there is no option to delete it.

#### Steps to reproduce
Don't know how to reproduce exactly unfortunately. Appeared in 5.33 or 5.32 update. We are currently running the latest version 5.35.1

#### Expected behavior
No empty space

#### Observed behavior (that appears unintentional) 
Here's a gif that shows what I'm talking about. Appears in MM Desktop client (Mac) and web version. Its fine on Mobile
![empty-space-mm](https://user-images.githubusercontent.com/35572989/118872294-69971600-b8b6-11eb-981b-37c09e38f363.gif)

#### Possible fixes
No idea unfortunately

**Comment by amyblais** [comment]
@hmhealey Have you seen a report like this before, or do you have thoughts on this?

**Comment by hmhealey** [comment]
No, we haven't seen anything like this before. That's really strange. I'm not even sure what that line might be.

In a web browser, could you use the dev tools to show us what the HTML for that space might be? If you could right click on it, click Inspect Element, and send us a screenshot of that like
![Screen Shot 2021-05-21 at 10 12 36 AM](https://user-images.githubusercontent.com/3277310/119151255-38852580-ba1d-11eb-91b6-e22cc1860a43.png)
that'd be really helpful for us to understand what might be going on there.

**Comment by camaer** [comment]
Here's the inspect element. Seems to be a Channel but without a name or anything.

![Screen Shot 2021-05-21 at 10 15 55 AM](https://user-images.githubusercontent.com/35572989/119151837-c19c5c80-ba1d-11eb-88df-af5522fb73fe.png)

Could it be perhaps an old channel that was deleted incorrectly ?

**Comment by hmhealey** [comment]
Yeah, that might be the case since the draggable-id attribute looks like a real channel ID. If you have access to the DB, you could confirm whether or not a channel with that "s6cbh..." ID exists.

Either that or there's an error in the library we use for drag and drop. If that were the case, I'd expect to see an error in the browser's console.

**Comment by camaer** [comment]
Seems like I do have a channel `s6cbh1poabdwmbt5yxgd7k1h5e`

![Screen Shot 2021-05-21 at 10 51 07 AM](https://user-images.githubusercontent.com/35572989/119156854-9cf6b380-ba22-11eb-8f03-f551f0f29299.png)

Should I juste delete the row in the channels table ?

**Comment by hmhealey** [comment]
I wouldn't recommend deleting it since that could leave some orphaned data that could cause other problems, but you could try deleting the row in `SidebarChannels` with that ChannelId and your UserId (only needed if there's multiple rows that match that). That'll remove it from the Favorites category in your sidebar since that table keeps track of where channels appear in the sidebar.

**Comment by camaer** [comment]
That worked ! Thanks for the help. Not sure exactly what happened but at least it's fixed.

**Comment by hmhealey** [comment]
Glad that helped! Let us know if that comes up again.

The new sidebar is definitely more complicated than the old one, so stuff like that one can pop up occasionally, but since that's the first time this particular issue has come up, I don't think there's much to investigate on it for now. We can always reopen this if it reappears though.
