### ISSUE TITLE
Ordered list should not trigger for numbers greater than 1

### ISSUE THREAD

**Issue by Michael-E-Rose** [mattermost/mattermost-server#17781]
In many languages, such as German, it's customary to use dots to denote ranks: 5. instead of 5th. Starting a sentence with 5. triggers the ordered list formatting. That's just ugly, least because of the wide margins.

I propose to switch of automatic ordered list when the number isn't 1.
That's also how Slack does it. Because, seriously, how often do people want to start an ordered list with a number that's not 1?

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @Michael-E-Rose,  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by Michael-E-Rose** [comment]
I will gladly do this, but is this really a feature idea? I'm not proposing something new, after all. I want a current formatting feature (feature might be the wrong word) fixed.

Unfortunately, I know only Python but not Go, so will be unable to fix this myself :/

**Comment by amyblais** [comment]
Ok, I've opened a ticket here: https://mattermost.atlassian.net/browse/MM-36476

**Comment by hmhealey** [comment]
Thanks for the suggestion, @Michael-E-Rose!

Unfortunately, this isn't something we're planning on doing. We usually try to match the Markdown/CommonMark specs for things like this since it makes it easier to ensure everything is working correctly. While it's sometimes inconvenient or a bit ugly like this case, it makes it easier for people familiar with Markdown from other places to use it here. Looking back, it might've been better to not commit to fully supporting Markdown to begin with so we could deviate a bit easier, but since we've had it for so long now, it's not really something we can change right now. Maybe we can do it when we're focused more on improving our Markdown features, but I don't know when that would be at the moment.

**Comment by Michael-E-Rose** [comment]
Strange choice indeed. I will propose a change to the definition of ordered lists to the CommonMark guys. In my mind it's not an ordered list if it doesn't start with "1.".

**Comment by Michael-E-Rose** [comment]
I inquired with the CommonMark folks. My proposal to only trigger ordered list not just on any digit but on "1. " only (similar to Slack's definition of an ordered list, or GitHub Flavored Markdown) isn't popular, but there is a solution: One can simply escape the dot if the sentence starts with "\d. ". Example: `5\. Klasse`.
