### ISSUE TITLE
Failed to alter column type","error":"pq: default for column \"timezone\" cannot be cast automatically to type jsonb

### ISSUE THREAD

**Issue by karoolpl** [mattermost/mattermost-server#18038]
#### Summary
Hi, error upgrading mm version, postgresql version 13.2

#### Steps to reproduce
docker image, using community ediiton, tag master

#### Expected behavior
Automaticcly upgrade, don't work

#### Observed behavior (that appears unintentional) 

ALTER TABLE users ALTER COLUMN timezone TYPE jsonb USING timezone::jsonb

reuot:
ERROR:  default for column "timezone" cannot be cast automatically to type jsonb

#### Possible fixes
Upgrade procedure fix

**Comment by agnivade** [comment]
It seems like you have non JSON data in that column. That's why the migration is failing.

I'm afraid you will need to look into the column for which row is bad and manually fix that.

@streamer45 - perhaps something to add in the release notes for cases like these.

**Comment by karoolpl** [comment]
ye i know it's error with conversion, but it's auto, so I think that a lot of people will have this problem, trying to update to latest version. My postgresql db was made with mattermost 5.X version, to this point, new version went automaticly, cuz i set policy for my kubernetes cluster, to download always never image, and now i needed to fallback to 5.38 which works fine

**Comment by streamer45** [comment]
We were hoping this wouldn't affect many users given the application should always insert valid JSON. If the db data has been manipulated by external processes (e.g. plugins) then I can see this being an issue. There are also cases (especially in MySQL) where improper input data could get silently truncated due to varchar limits.

Unfortunately there isn't a good way to fix this automatically without potentially losing data. It makes perfect sense to add an important upgrade note so that users are advised before performing the upgrade.

cc @amyblais

**Comment by amyblais** [comment]
Closing as release notes was updated and a PR was merged,
