### ISSUE TITLE
5.37.x server can't show System Console

### ISSUE THREAD

**Issue by mzch** [mattermost/mattermost-server#18065]
#### Summary
Mattermost 5.37.x can't show System Console.

#### Steps to reproduce
1. Start Mattermost Server.
2. Login
3. Select `System Console` from menu.

#### Expected behavior
System Console will be shown.

#### Observed behavior (that appears unintentional) 
<img width="1494" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/128317830-a72b89ac-6fcd-4188-91d2-1b847817f4dd.png">

**Comment by amyblais** [comment]
@mzch Would you be open to sharing more details about your environment from here https://docs.mattermost.com/process/support.html#general-questions-for-any-issues? Specifically your OS and version, Mattermost server version, and any Mattermost logs.

**Comment by mzch** [comment]
Sorry,

OS: `Debian 10.10`
Mattermost Server: 5.37.0, 5.37.1
Browser: Chrome 92.0.4515.107
Mattermost Desktop: 4.7.0 on Mac
mattermost.log:
[mattermost.log](https://github.com/mattermost/mattermost-server/files/6939013/mattermost.log)

**Comment by amyblais** [comment]
Would you be open to posting about this either on our [Peer-to-peer Help channel on our community server here](https://community.mattermost.com/core/channels/peer-to-peer-help) or on our [troubleshooting forum here](https://forum.mattermost.org/)? This issue is likely something that would need some troubleshooting and our community and/or support team may be able to help with this!

**Comment by mzch** [comment]
I have posted the same issue in mattermost forum. Thanks.
