### ISSUE TITLE
Server hangs for 2-5 minutes on channels with a lot of links and larger images and history is loaded

### ISSUE THREAD

**Issue by ylluminate** [mattermost/mattermost-server#18342]
#### Summary
When loading a channel with many links or larger images linked therein the server hangs for all users for several minutes and clients show the top alert error message:
```
Please check connection, Mattermost unreachable. If issue persists, ask administrator to check WebSocket port.
```

The further back a user scrolls the longer the hang endures.

#### Steps to reproduce
Put a bunch of image links and URLs into a channel and then load it up. Scroll back through the previous messages.

#### Expected behavior
It should not hang the system but rather have some kind of background thread that handles things more effectively where there is heavy content loading perhaps? Not sure what the right way to handle this would be, but it's a problem.

#### Observed behavior (that appears unintentional) 
The noted error above. The server becomes entirely unresponsive and no one is able to use Mattermost until the server stops hanging.

**Comment by streamer45** [comment]
Hi @ylluminate,

would you be able to answer a couple of questions:

- What Mattermost server version are you running?
- What are the specifications of the instance running Mattermost? (Operating system version, CPUs and RAM)
- How many concurrent users do you usually have connected when this happens?

**Comment by hmhealey** [comment]
@ylluminate Is that behaviour repeatable after loading a channel once? There will be some work done to determine what you're linking to, but that should just be done once when the post is created (assuming these posts weren't created a couple years ago before that code was added) and then it should be quick.

---

@elandorr How big of an image are you talking about, and do you have an example link we could test with? It should just load enough to get the image's dimensions which I wouldn't expect too take too long.

I'd also echo @streamer45's questions here as well since knowing the size of the server would help as well.

**Comment by elandorr** [comment]
@hmhealey 

He is talking about image links, not images uploaded to MM, which would be a one-off CPU cost as they're stored locally. (Forever, with no maintenance possible in the 'open source' edition..)

There is no meaning in specifying an image, it of course depends on the server. If you have a Jeff Bezos level server you may try some astrophotography with hundreds of MBs. Resize cost explodes with size, no way around that. MM version also does not matter, it had this behaviour for at least a year. This should not be solved by throwing more money at it, since users can just throw bigger files at it ad infinitum.

If you monitor the server cpu load and traffic you can easily tell it loads and resizes over and over. With tiny images like thumbnails it's not a drain, but with big ones this escalates quickly.

1. There is no caching included. 
2. The optional cache in settings refers to a 3rd party repo that has been archived a long time ago and isn't a solution to this problem.
3. MM should simply not resize (or even download in the first place, check the header) images beyond a user defined size. Nothing stops users from posting some 1000MB image if they wanted, and good luck finding out who did that while on 100% CPU usage, then proceeding to explain to users how they shouldn't post big image links.
4. MM could have a basic cache with user defined total size. But again, this would be nice, but doesn't solve the loop of it being easily exploited via bigger and bigger files.

The only current solution to this is to disable image previews altogether. We told users to keep images small, but good luck teaching that to non-techies. They won't check. And frankly, neither will I casually unless I can notice a slowdown on my own PC.

**Comment by elandorr** [comment]
Have a random 'medium' sized image that is big enough to not show instantly in nomacs even on our i7: https://www48.zippyshare.com/v/lP0YSFaD/file.html

**Comment by hmhealey** [comment]
Do you perhaps have the local image proxy enabled? That's the only thing I could think that of on the server that would be impacted by this every time a post is loaded. As far as I know, that doesn't resize images at all, but it's possible that it's streaming all of the image data to the client each time and that might not be caching correctly for whatever reason.

Without that enabled though, the MM server only works on external images the first time a link is posted to them because the server is trying to get some metadata about the image. It requests the contents of any posted link to identify if it's an image and, if it is, to determine a few things about it like its size. It only reads the first 50MB of data while doing this, and it streams the data so that it's not holding the whole thing in memory. Once that's read, it caches that metadata on the server.

**Comment by elandorr** [comment]
Yes, of course, otherwise we expose user data to anyone posting a link. I'd rather turn off previews before allowing that.

If it's not resizing server side, then I don't know where the CPU usage stems from. 
Not resizing at all makes little sense as well, why would you send the full file only to have the client resize it down to a small preview anyway? Just needs a way to limit filesize and a customizable cache.

This with just 2 users seeing it, instant spike + respective bandwith:
![resss](https://user-images.githubusercontent.com/56206745/133589650-f7b5c83b-d553-476a-b16f-d8ef3ca263ee.png)

**Comment by streamer45** [comment]
@elandorr Are you able to record and share a CPU profile when this happens? That should hopefully point us to the underlying issue you are experiencing. You can do that by enabling performance monitoring on your instance (`admin_console/environment/performance_monitoring`). Then you can generate a profile with:

```sh
curl http://localhost:8067/debug/pprof/profile?seconds=10 -o cpu.prof
```

**Comment by elandorr** [comment]
I don't have time for that right now, maybe the initial reporter will do it. Easy to reproduce on a fresh setup as well.

**Comment by streamer45** [comment]
Fair enough. I've created https://mattermost.atlassian.net/browse/MM-38634 to track this and will let teams prioritize accordingly.

**Comment by agnivade** [comment]
@ylluminate , @elandorr - Just for us to debug this issue better, could you let us know what Mattermost version are you using? I realize you have mentioned that it has been like this for a year, but having a specific version allows us to pin point this to a specific release and work from there. Any help on that would be much appreciated. Thanks!

**Comment by agnivade** [comment]
I just tried to reproduce this issue on latest master with `LinkPreviews` and `LocalImageProxy` enabled. While loading a channel for the first time, there is an expected lag to populate the cache with the opengraph data. But once it's loaded, for any subsequent loads, there is no lag.

From the reported issue here, it seems that we are somehow triggering image transformations in the local image proxy. This can only happen if we are specifying image opts in the request URL fragment:

https://github.com/mattermost/mattermost-server/blob/9dcd61c1248f72f85ed390e3b132d1c4c8eef9f8/vendor/willnorris.com/go/imageproxy/imageproxy.go#L496-L500

e.g.:

```
// Examples
//
// 	0x0         - no resizing
// 	200x        - 200 pixels wide, proportional height
// 	x0.15       - 15% original height, proportional width
// 	100x150     - 100 by 150 pixels, cropping as needed
// 	100         - 100 pixels square, cropping as needed
// 	150,fit     - scale to fit 150 pixels square, no cropping
// 	100,r90     - 100 pixels square, rotated 90 degrees
// 	100,fv,fh   - 100 pixels square, flipped horizontal and vertical
```

But our webapp does not do anything like that. @hmhealey - Do you know of any case where we apply transformations like these to 3rd party image links? OP hasn't specified any MM version so we cannot really look into any specific branch.

Here is what I am seeing: `https://localhost:8065/api/v4/image?url=https%3A%2F%2Fwww.collinsdictionary.com%2Fimages%2Ffull%2Fsnow_306991961.jpg%3Fversion%3D4.0.223`

**Comment by elandorr** [comment]
> @ylluminate , @elandorr - Just for us to debug this issue better, could you let us know what Mattermost version are you using? I realize you have mentioned that it has been like this for a year, but having a specific version allows us to pin point this to a specific release and work from there. Any help on that would be much appreciated. Thanks!

In September when I posted my test file I was using whatever was latest then, but I just tried again and can tell you exactly how to reproduce:

- v6.3.3
- previews on, proxy on
- open (h)top
- post this url https://filesamples.com/samples/image/png/sample_5184%C3%973456.png
- watch the server explode

Now if you have a more expensive server than we do you might still not notice, this is on some cheap-ish Xeon. My previous image was 50MiB and that even chokes my 2y old i7 laptop. I tried finding a high-res space image for you, but seriously couldn't find any. There used to be a NASA site with original files. You could generate a plain noise test image via python if this one isn't enough to break yours.

**Comment by agnivade** [comment]
Thanks for the update @elandorr. Unfortunately, I tried with the exact same steps, but could not reproduce anything. I even tried with https://effigis.com/wp-content/uploads/2015/02/Airbus_Pleiades_50cm_8bit_RGB_Yogyakarta.jpg, which is a 50MB image. The proxy timed out while sending the image, but that's a separate issue. Other than that, I did not see any CPU/Memory issue.

> My original reply in here is about the fact that MM has no limit. You can throw a 100MiB file at it and it will kill the server for a while. If someone wants to abuse he can just generate a 10GiB file and really wreck you.

I think this is the difference that we are seeing. From what I can see, Mattermost does not do any processing of the image. It just streams the image from the server to the client, instead of the client requesting the image. So it doesn't really matter whether it's a 100MB or 10GB image, there is no extra overhead on Mattermost. It purely acts as a proxy.

Unless ... the client specifies any transformation opts. In that case, the proxy will try to apply that transformation and load the image.

Since you are able to reproduce this, I'd need a bit more help from you to understand how you are running into this. Could you paste the URL that tries to load the image from MM? It should look something like `https://localhost:8065/api/v4/image?url=https%3A%2F%2Fwww.collinsdictionary.com%2Fimages%2Ffull%2Fsnow_306991961.jpg%3Fversion%3D4.0.223`

Also, when the server is experiencing high CPU, would you be able to record a CPU profile and share that with us. Please see [here](https://github.com/mattermost/mattermost-server/issues/18342#issuecomment-920808028) on how to do that.

Sorry for asking you to do all of this. But I haven't been able to reproduce this by myself. :(

**Comment by agnivade** [comment]
Great! Can you please attach the profile here? It is a standard Go profile containing only application specific data. Please see documentation here: https://pkg.go.dev/net/http/pprof, https://go.dev/blog/pprof.

**Comment by hmhealey** [comment]
> @hmhealey - Do you know of any case where we apply transformations like these to 3rd party image links? OP hasn't specified any MM version so we cannot really look into any specific branch.

No, we don't use the image proxy for any transformations at this point. It's something we could do, but we're not doing it at all right now.

**Comment by elandorr** [comment]
https://safenote.co/r/620cd4783641f1@22008851
I looked at it and can't make sense of it, but you're the go devs.

**Comment by agnivade** [comment]
Thanks for the profile @elandorr ! I can see the issue now. I am consulting internally on the best way to proceed. I'll keep you posted. Thanks for your patience with this!

**Comment by elandorr** [comment]
@agnivade Would you mind sharing what the issue was now? I'm not experienced with pprof, I only saw memmove being on top.

**Comment by agnivade** [comment]
This was in the end an issue with unnecessary memory allocations in our imageproxy library. We ended up bypassing the dependency entirely and copying the parts that we were actually using into our own source tree. A lot of complexity was removed by getting rid of unused features.

In the meantime, we're also working with the upstream author to resolve the issues there, although we don't have any plans to migrate back to using the dependency again. I'll close the issue now that it is fixed on master. Thank you for your patience with this!

**Comment by elandorr** [comment]
@agnivade Interesting to see how it played out! Thanks for the follow up.

Do you have a comment on the other 
implications, i.e. the traffic explosion? Given our relatively fast connection it's not noticeable as no one has tried to abuse it, but downloading and multiplying every single image regardless of size is kinda like an amplification attack against yourself.

I was thinking of the `content-length` header, but that's not always sent. Maybe there is a way to read the metadata from an image before fully downloading, but I haven't found a library for this doing a quick search.
