### ISSUE TITLE
Migrate from gorp to sqlx in store/sqlstore/compliance_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18500]
Mattermost is migrating from using `gorp` as a sql library to using `sqlx`.

This ticket is about migrating all usages of gorp in `store/sqlstore/compliance_store.go` to sqlx.

The way to proceed would be as follows:

All SQL queries are usually executed from `GetMaster()` or `GetReplica()` calls which return the gorp instance for the DB. We have a corresponding method `GetMasterX`/`GetReplicaX` which return the sqlx instance instead.

All named params in SQL query strings should be replaced with `?` and then a list of args should be passed to the method. Here is a quick cheat sheet of the methods to replace with:

```
GetReplica().SelectOne() -> GetReplicaX().Get()
GetReplica().Get() -> GetReplicaX().Get()
GetReplica().Select() -> GetReplicaX().Select()
GetMaster().Insert() -> GetMasterX().NamedExec()
GetMaster().Update() -> GetMasterX().NamedExec()
GetMaster().Exec() -> GetMasterX().Exec()
```

For some practical examples of migrations, please feel free to take a look at:
https://github.com/mattermost/mattermost-server/pull/18302
https://github.com/mattermost/mattermost-server/pull/18301

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-38996

**Comment by penthaapatel** [comment]
Hi! I would like to work on this.

**Comment by agnivade** [comment]
All yours @penthaapatel !

**Comment by penthaapatel** [comment]
I have a few questions on handling the named params in SQL query strings. 
In the file `store/sqlstore/compliance_store.go`, the `channelsQuery` string contains nested queries like `emailQuery` and `keywordQuery` ref - https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/compliance_store.go#L125-L167

The args for the SQL query are read from the `props` map which is populated according to the number of `keywords` and `emails` (and hence can vary). Since the number of args to be passed to the SQL query can vary, what should be the correct way of handling such queries when replacing the named params with `?` symbol?

I referred to the previously merged PRs that migrated from gorp to sqlx but could not find any examples of nested queries with variable number of named parameters. Please guide me on how to proceed further.

**Comment by agnivade** [comment]
Excellent question @penthaapatel !

You can take a look here: https://github.com/mattermost/mattermost-server/pull/18300/files#diff-dd10adea091a6ea3cb5b9239d16743fb877678371485f290557f51cce92ee935L107 for a similar use-case.

Essentially, have a slice `var args []interface{}` and you would want to append to the slice every time you set the `props` map. And then pass `args...` in the `Select` method.

**Comment by penthaapatel** [comment]
@agnivade The order in which the elements are appended to the slice `args []interface{}` should be same as the order of `?` (for the named parameters) that appear in the SQL query, so that in the resultant SQL query, the correct `args` are correctly substituted in place of all `?` symbols that should hold the named values. Is that correct?

**Comment by agnivade** [comment]
That is correct.

**Comment by penthaapatel** [comment]
@agnivade The func `ComplianceExport` contains 2 `SELECT` SQL queries - `channelsQuery` and `directMessagesQuery`.
After`channelsQuery` is executed using the slice `args`, for the next SELECT query, that is the `directMessagesQuery`, the `args` may change for the parameters `LastPostCreateAt`, `LastPostId` and `Limit` ref - https://github.com/mattermost/mattermost-server/blob/master/store/sqlstore/compliance_store.go#L184-L186.

So what should be the correct way of modifying the slice `args`? I was thinking of erasing the said parameters that were set for `channelsQuery` from the slice `args` and then again inserting the new parameters to the same slice for the `directMessagesQuery ` but I am afraid it may cause memory leaks and it also does not look neat.

I want to modify the same slice `args` because it already has the `emails` and `keywords` parameters set. These parameters are common to both `channelsQuery` and `directMessagesQuery`.

Should I create a Draft Pull Request so that is easier to review the changes I am working on?

**Comment by agnivade** [comment]
Having 2 separate slices sounds like a clean solution to me. It's also easy to modify one without interfering with the other query in the future.
