### ISSUE TITLE
Migrate from gorp to sqlx in store/sqlstore/thread_store.go

### ISSUE THREAD

**Issue by agnivade** [mattermost/mattermost-server#18867]
Mattermost is migrating from using `gorp` as a sql library to using `sqlx`.

This ticket is about migrating all usages of gorp in `store/sqlstore/thread_store.go` to sqlx.

The way to proceed would be as follows:

All SQL queries are usually executed from `GetMaster()` or `GetReplica()` calls which return the gorp instance for the DB. We have a corresponding method `GetMasterX`/`GetReplicaX` which return the sqlx instance instead.

All named params in SQL query strings should be replaced with `?` and then a list of args should be passed to the method. Here is a quick cheat sheet of the methods to replace with:

```
GetReplica().SelectOne() -> GetReplicaX().Get()
GetReplica().Get() -> GetReplicaX().Get()
GetReplica().Select() -> GetReplicaX().Select()
GetMaster().Insert() -> GetMasterX().NamedExec()
GetMaster().Update() -> GetMasterX().NamedExec()
GetMaster().Exec() -> GetMasterX().Exec()
```

For some practical examples of migrations, please feel free to take a look at:
https://github.com/mattermost/mattermost-server/pull/18302
https://github.com/mattermost/mattermost-server/pull/18301

If you have questions about the ticket or you need any help, feel free to contact `agniva.de.sarker` in https://community.mattermost.com/

----------------------------------

If you're interested please comment here and come [join our "Contributors" community channel](https://community.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please [join our "Developers" community channel](https://community.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

JIRA: https://mattermost.atlassian.net/browse/MM-39629

**Comment by agnivade** [comment]
@penthaapatel - Wondering if you would be interested in taking this one too? :)

**Comment by penthaapatel** [comment]
@agnivade Absolutely yes!

**Comment by penthaapatel** [comment]
@agnivade Can this be written as a single exported function `Update()` instead of having `Update()` calling the `update()` function? Am I missing out something here? Same question for other functions like `Get()`,`SaveMembership()` in `thread_store.go`
https://github.com/mattermost/mattermost-server/blob/0da249c6517f24946f5bc7b6062b98fd3628c712/store/sqlstore/thread_store.go#L92-L94

**Comment by agnivade** [comment]
@penthaapatel - Yes that sounds good. `s.update` and `s.get` were actually being called from other methods, but now they are removed following some refactoring work. It's good to be moved back to the main method now. :+1:

**Comment by penthaapatel** [comment]
@agnivade I was wondering if it is a good idea to have an interface in `store/sqlstore/sqlx_wrapper.go` similar to the `SqlExecutor` interface in `gorp` so that it is easier to enable some internal store methods to that accept both transactions `*sqlxTxWrapper` and common db handlers `*sqlxDbWrapper`? Because there are a few methods in `thread_store.go` like `s.saveMembership`, `s.updateMembership`,and `s.getMembershipForUser` where it can be used. Or the other workaround is to have an interface within `thread_store.go` like this:
```
// sqlxExecutor is an interface used to enable some internal store methods to
// accept both transactions (*sqlxTxWrapper) and common db handlers (*sqlxDbWrapper).
type sqlxExecutor interface {
	Exec(query string, args ...interface{}) (sql.Result, error)
	Get(i interface{}, query string, keys ...interface{}) error
}
```

**Comment by agnivade** [comment]
Yep, sounds fine to me @penthaapatel.
