### ISSUE TITLE
Allow disabling/Removing default channels

### ISSUE THREAD

**Issue by KlavsKlavsen** [mattermost/mattermost-server#18883]
When you create a new Team in Mattermost - they ALL have their own off-topic/Town Square channels - which cannot be disabled :(

I would very  much like to be able to f.ex. ONLY have private channels in primary/common Team - and thus removing or atleast disabling the 2 default channels, would be a very nice feature.

**Comment by cheluskin** [comment]
Any solution? no way to do it via plugins? I am trying to do this now, but I see no methos to intercept the team create.

**Comment by amyblais** [comment]
Thank you for upvoting the feature request!

Some comments from a dev at https://community.mattermost.com/core/pl/comjw5m8upgemjyiubid7buqmc:
Off-Topic could probably be made optional. It has a workaround as people have made integrations to automatically delete the Off-Topic channel when a team is created so that people aren't added to it. Town Square is harder unfortunately. A lot of the app uses Town Square as a fallback when it doesn't know where else to send people, so it requires a lot of changes to the routing code and maybe requires some new default landing page be created for that.
