### ISSUE TITLE
Anyone can access the Invite Members Link !!

### ISSUE THREAD

**Issue by majidit** [mattermost/mattermost-server#18900]
Hello friends

## It is not good at all that anyone can access the invitation link
Because this link may be provided to someone outside the organization and can easily become a member and access information from the organization, however insignificant.
We had to block registration by email!
And if necessary, we will activate it to register!
And after registering, we will deactivate it again!
:neutral_face:

@tbalthazar @MerlinDMC @lurcio @mauricio @cored

**Comment by amyblais** [comment]
We've opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-39780

**Comment by jasonblais** [comment]
@majidit Thanks for your report.

In the future, to help the community troubleshoot the issues faster, are you open to following the issue report template which appears when [opening a new GitHub issue](https://github.com/mattermost/mattermost-server/issues/new), specifically
 - Summary
 - Steps to reproduce
 - Expected behaviour
 - Observed behaviour

Please also refrain from at-mentioning individuals as they may not be subject matter experts for the reported issue. Our community of users, contributors and staff regularly review new issues opened in GitHub

Thanks again for your report! The above two steps will help create a smooth community experience for everyone.

**Comment by adsche** [comment]
Hi there, is there any progress on this?
The linked issue is "unassigned".

To clarify, there is currently no way on a closed server to prevent people from sending email invites? The setting in systems console does nothing, and there is no warning about it!

We can only completely deactivate user account creation (so that the email invites just appear to not work at the last step) and temporarily enable this when we actually want to allow a user to be invited?

**Comment by amyblais** [comment]
> Hi there, is there any progress on this? The linked issue is "unassigned".
> 
> To clarify, there is currently no way on a closed server to prevent people from sending email invites? The setting in systems console does nothing, and there is no warning about it!
> 
> We can only completely deactivate user account creation (so that the email invites just appear to not work at the last step) and temporarily enable this when we actually want to allow a user to be invited?

Adding @laneycs and @mkraft to help with details.
