### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by tuxity** [mattermost/mattermost-server#19123]
#### Summary
From time to time the server crash in my Docker container, I have to restart it to get it running.

#### Steps to reproduce
No idea, it appears to be random

MM Server 6.1.0 team edition (Docker container running on Linux Debian 10.11)
Postgres 13

#### Expected behavior
Running without crash

#### Observed behavior (that appears unintentional) 
Crash logs https://gist.github.com/tuxity/82e8fc2cec4f4adbcc72420b8b08bfda

#### Possible fixes
No idea

**Comment by agnivade** [comment]
The error message is `runtime/cgo: pthread_create failed: Resource temporarily unavailable` - which means it is not related to Mattermost but likely caused due to resource constraints imposed by your docker container.

Have a look at: https://unix.stackexchange.com/questions/253903/creating-threads-fails-with-resource-temporarily-unavailable-with-4-3-kernel for possible solutions.

**Comment by tuxity** [comment]
I will check that today, thanks for the info. I will post update on docker-mattermost too if needed

**Comment by tuxity** [comment]
I was at 169 PIDs (with `docker stats`) right now and in `docker-compose.yml` there is [line](https://github.com/mattermost/docker/blob/main/docker-compose.yml#L36) to set PIDs limit to 200 and I increased it.

It was the reason surely. Thanks for the tip!
