### ISSUE TITLE
Channel header elements pushed out of the way by code block

### ISSUE THREAD

**Issue by dipak-demansol** [mattermost/mattermost-server#19213]
#### Summary
**#Channel heade UI issue (same for the direct message header section)**
1) User Should not able to Save the Channel header by adding only space.
2) when user add the random text + same then UI is not good and its effecting to the Header other element, pls see the video.
3) in the channel header comment box, i select all the text then from the keyboard i press the delete button then click on the save then in the channel i can see the bracket "**)**" at the end of the post, pls see the video.

#### Steps to reproduce
See the video and perform the same steps in 
```  
Mattermost Version: cloud-2021-12-08-1
Database Schema Version: 6.3.0
 ```
#### Expected behavior
no matter what i add in the channel header, the UI issue should not generate and should not effect on the other elements.

https://user-images.githubusercontent.com/89907719/146821754-9df18737-abaf-4711-974c-0dd41834d8b5.mp4

**Comment by amyblais** [comment]
Thanks, opened a ticket: https://mattermost.atlassian.net/browse/MM-40736.

**Comment by hmhealey** [comment]
This behaviour is a bit odd, but what's happening here is that the first four spaces as the start of the line are triggering a code block in Markdown similar to if you wrapped the text in backquotes. Since we support all Markdown in the header, we're unfortunately stuck with code blocks looking weird when placed in there.

I'll open this up to the community to see if anyone has any ideas for how to fix the elements on the left getting messed up by the code block
