### ISSUE TITLE
Some plug-ins GUI icons stopped working after 6.3.0 update

### ISSUE THREAD

**Issue by DummyThatMatters** [mattermost/mattermost-server#19395]
#### Summary
Some plugins that previously were called via button click on right upper panel are no longer callable using that way (the button click causes no action whatsoever, although slash-command which trigger the very same action works well)

#### Steps to reproduce

Mattermost 6.3.0 or 6.3.1 Team Edition
Using DB postgres (PostgreSQL) 12.1

1. Install some random plug-in, that uses button in right upper panel
2. Activate plug-in? enter all necessary plug-in data
3. Click on activation button in mattermost GUI

#### Expected behavior
Plugin starts to working after a button click on right-side pannel of MM GUI

#### Observed behavior (that appears unintentional) 
No action whatsoever. If developer mode activated it throws error in upper part of the screen `DEVELOPER MODE: A JavaScript error has occurred. Please use the JavaScript console to capture and report the error (row: 2 col: 5566068).`
![изображение](https://user-images.githubusercontent.com/51426114/150563494-a3a8e26b-7afc-4dff-8c59-820f116cc35a.png)

The console and network requests:
![изображение](https://user-images.githubusercontent.com/51426114/150564094-a85b9b41-25ce-4501-a23b-23703107eff8.png)

It seems that AJAX is no longer working by default
this peace of plugin webapp code is no longer executing:
`){$.ajax({url:a+"choice_button",type:"POST",headers:{"Content-Type":"application/json"},data:JSON.stringify(t)}).done((t=>{const e=JSON.parse(t).meeting_link;e&&window.open(e,"_blank")})).fail(((t,e)=>{alert`

**Comment by amyblais** [comment]
@levb @hanzei @mickmister Do the console errors indicate a bug?

**Comment by mickmister** [comment]
@amyblais Yes this seems like an issue that should be solved asap. I'll look into this cc @DHaussermann

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-41210.

**Comment by mickmister** [comment]
Hi @DummyThatMatters, thanks for reporting this!

Based on your screenshot, it looks like the `com.mattermost.iva.c...` plugin running is using jquery. In 6.3.0, jquery was removed as a dependency from the web application. Any plugins relying on jquery that do not import the library themselves will experience issues like you reported.

Is it possible for me to view the `com.mattermost.iva.c...` plugin's source code? I have a feeling that running the slash command is working because it may be a server-side slash command in the plugin, rather than a slash command created by the plugin's frontend.

Do you have other error messages you can share for this issue, e.g. the skype4business plugin?

**Comment by DummyThatMatters** [comment]
@mickmister Sorry for misinformating you, S4B appear to work well. Is seems truly, that we have issues only with jquery-based plug-ins.
