### ISSUE TITLE
Trailing slash being stripped from SiteURL

### ISSUE THREAD

**Issue by nwl** [mattermost/mattermost-server#19504]
#### Summary
The SiteURL configuration has the trailing slashed removed after saving in the UI or setting on the CLI and restarting the service.

#### Steps to reproduce
1. Clean install of Mattermost on Ubuntu 20.04.3 with mattermost-6.3.3
2. Edit config.json and set a URL with a relative path ("https://domain.com/mattermost/")
3. Start service.
4. Read config file and URL is now "https://domain.com/mattermost"

#### Expected behavior
The SiteURL should retain the trailing slash which is necessary for configuring a reverse proxy with Apache2. 

#### Observed behavior (that appears unintentional) 
SiteURL is being reformatted.

**Comment by amyblais** [comment]
@streamer45 @agnivade Would this be a bug?

**Comment by agnivade** [comment]
This is an intentional part of the code: https://github.com/mattermost/mattermost-server/blob/d2cabaebaba25657f052458de2ce6639b24ab4e8/config/utils.go#L99-L102.

@nwl - Could you explain a bit into how is this affecting you? I haven't worked with Apache a lot, so maybe there's something we need to change.

We have some documentation for using Apache as a reverse proxy here: https://docs.mattermost.com/configure/config-proxy-apache2.html?highlight=apache.

**Comment by nwl** [comment]
I've moved to NGINX now so the issue is resolved but I believe when using setting up a reverse proxy on Apache that uses a subdirectory in the URL, you need to add a trailing slash to ensure that all rewritten links stay relative. In other words, it's fine to strip the trailing slash from the config if you are hosting at mattermost.domain.com but not domain.com/mattermost

**Comment by agnivade** [comment]
Glad to hear it's resolved @nwl. I am not entirely sure why it should not work on Apache as well. I am going to close this for now. If someone with Apache runs into this, it'll be good to run some tests and understand exactly what's wrong.
