### ISSUE TITLE
Scrolling problem

### ISSUE THREAD

**Issue by majidys** [mattermost/mattermost-server#19611]
Hello friends
When I scroll through a channel or anywhere else, 
I am **_immediately moved to the middle of previous messages_**!!
@amyblais

**Comment by amyblais** [comment]
We have a few tickets related to scrolling issues
 - https://mattermost.atlassian.net/browse/MM-40043
 - https://mattermost.atlassian.net/browse/MM-40056

**Comment by BenLloydPearson** [comment]
Hi @majidys,

Please review our [contributor guide for reporting bugs in Mattermost](https://handbook.mattermost.com/contributors/contributors/ways-to-contribute#report-a-bug). it's important that you follow this process and provide all of the necessary details when reporting issues like these so we can accurately debug and fix them. It also helps us reduce the number of duplicate issues we have.

I'm going to close this issue since it appears to be a duplicate. In the future, please search our existing issues and fill out all of the requested information in the Issue template when creating new issues on Mattermost GitHub repositories.

**Comment by majidys** [comment]
Fixed issue after updating to the latest version

![image](https://user-images.githubusercontent.com/99164978/155277451-41da925c-f0d6-4817-baa5-e8dfcf37d745.png)
