### ISSUE TITLE
Failed to parse SVG - unable to extract SVG dimensions

### ISSUE THREAD

**Issue by chfxr** [mattermost/mattermost-server#19719]
#### Summary
Uploaded SVGs are not shown as thumbnail / preview
Mattermost Version: 6.2.1

#### Steps to reproduce
1. Go into a channel or chat
2. Upload SVG
3. SVG is not shown

Info: Enable SVGs is true.

#### Expected behavior
SVG should be displayed and rendered in a thumbnail / preview

#### Observed behavior (that appears unintentional) 
Error logs:
"Failed to parse SVG","caller":"app/file.go:791","error":"unable to extract SVG dimensions"
![image](https://user-images.githubusercontent.com/64739555/157036391-48b09ba0-d2a7-46ba-861d-c58517936812.png)

#### Possible fixes
Provide a standard resolution for SVGs ?

**Comment by amyblais** [comment]
We have a related ticket open here: https://mattermost.atlassian.net/browse/MM-40450.

**Comment by RadauKakao** [comment]
Just noticed this on our instance too. According to our logfiles this issue first appeared Dec 2020. This agrees with the comment of @hmhealey that the code hasn't been changed recently and that this might has been broken for years.

**Comment by hmhealey** [comment]
MM-40450 is a different issue. That one's about what happens when someone makes a post containing Markdown that looks like `![an svg](https://example.com/image.svg)` since that's not handled properly by the image proxy, but this issue is about an error that happens when uploading an SVG as a file attachment
