### ISSUE TITLE
POST APIs are not working after deploying to our domain/server

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [mattermost/mattermost-server#19948]
#### Summary
All POST APIs are working fine in a local machine while we are developing the application. Once deployed to the server POST APIs are not working, but other APIs are working fine.
<img width="632" alt="Screenshot 2022-04-08 at 2 33 52 PM" src="https://user-images.githubusercontent.com/9896335/162403509-db17de8f-7f46-4aa3-8d10-7aec9fc32b1d.png">

I am getting the below response

`{"id":"api.context.session_expired.app_error","message":"Invalid or expired session, please login again.","detailed_error":"","request_id":"xao73nqj6b8h9pxxxxxxxxxxxxxx","status_code":401}`

#### Steps to reproduce
Use any POST APIs on the server

#### Expected behavior
POST APIs should also work fine on the server

#### Observed behavior (that appears unintentional) 
POSt APIs are not working after deploying to the server

#### Possible fixes
NA

Please help in fixing this issue on server

**Comment by amyblais** [comment]
@rajeshwarpatlolla Would you be open to posting this troubleshooting question either on our [Peer-to-peer Help channel here](https://community.mattermost.com/core/channels/peer-to-peer-help) or on our [troubleshooting forum here](https://forum.mattermost.com/)? Someone on our community or one of our devs will likely be able to help with this.

**Comment by rajeshwarpatlolla** [comment]
I posted in [forum](https://forum.mattermost.com/t/post-apis-are-not-working-after-deploying-to-our-domain-server/13188), but no response yet. Does anyone have any idea on this issue?

**Comment by ashishbhate** [comment]
Could you share more details about this redirection change? 

Do you have a proxy (possibly an nginx reverse proxy) in front of your app server? If yes, are you sure the request headers are being forwarded correctly for POST requests?

**Comment by rajeshwarpatlolla** [comment]
We have the nginx reverse proxy. The headers are sent properly from frontend application.

**Comment by ashishbhate** [comment]
@rajeshwarpatiolla 

Since I can't reproduce this issue, we're going to need more information about your changes and setup to debug this issue. Could you please post the following.

1. The changes you've made for the redirection
2. Server logs that correspond to the POST request
3. An outline of your production server environment and deployment process, especially the services you're using in production that aren't in your local dev environment. 
4. Config settings for these services - e.g. the nginx reverse proxy, any firewall you may be running.
5. Your Mattermost server configuration

If you're uncomfortable sharing this in public, feel free to reach out to me on the Mattermost community server - https://community.mattermost.com. I'm "ashishbhate" on that server.

**Comment by sanju2010** [comment]
Hi,

Sorry to get back a little late. In fact, our application is running on IIS and MM deployed on nginx on another server. We have written a rewrite rule in IIS to proxy to the nginx server (where mattermost server is running). 
Sometime back our post calls were working in dev environment and we believe after we upgraded to 6.3.1 version, the POST calls are failing in dev environment. When we connect from localhost(react app), those POST calls are working fine.

Please let us know if you need any further information as we really need to resolve this issue as soon as possible. 

Appreciate all your help.

Thanks

**Comment by ashishbhate** [comment]
@sanju2010 Please see my previous post for information I'd need to begin debugging this. 

>we believe after we upgraded to 6.3.1 version

Which version did you upgrade from?

**Comment by sunilkolluru** [comment]
@ashishbhate , I have provided all the information you requested in community.mattermost.com 

Appreciate all your help and pls let know if you need any further information.

Thanks

**Comment by sunilkolluru** [comment]
@ashishbhate @amyblais 
I submitted all the information and logs requested in the https://community.mattermost.com/ last week. When i tried to check for updates I don't see any of my msgs in the DIRECT MESSAGES section. Could you pls let me know if I need to submit the information again or do you have access to that information.

We are stuck at this issue for quite sometime now and greatly appreciate any help to resolve it.

Thanks
Sunil

**Comment by ashishbhate** [comment]
@sunilkolluru I've responded to your DM. We're still missing a lot of the information that I requested in my previous post.

**Comment by sunilkolluru** [comment]
@ashishbhate 

sent an update in community site. Please review and help us resolve the issue.

Thanks
Sunil

**Comment by sunilkolluru** [comment]
@ashishbhate 

did you get a chance to review our update.

**Comment by sunilkolluru** [comment]
@ashishbhate @amyblais 
 
We have noticed the below change in the request headers for cookie for the same api call from our mattermost integration in our react application to the admin mattermost site - 

cookie value for ids API call from our react application - 
![image](https://user-images.githubusercontent.com/75263980/169292304-ea27dfee-2e6b-4d85-9d23-e52150b6e866.png)

cookie value for ids API call from mattermost admin site - 
![image](https://user-images.githubusercontent.com/75263980/169292418-d8159128-7cdc-479d-a7d7-13d6a05c03f4.png)

Pls confirm if we need to add MMUSERID and MMCSRF to the cookies to make the apis work in our react application. If so, how do we get the MMCSRF value? Is it part of any login response or do we need to call any API to get that value. 

Any help in this issue is greatly appreciated.

Thanks,
Sunil

**Comment by BenLloydPearson** [comment]
@sunilkolluru Can you share a direct link to the messages you shared in community.mattermost.com? I'm having a hard time finding them.
