### ISSUE TITLE
Unnecessary S3 multipart upload

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/mattermost-server#20066]
#### Summary
Don't use S3 multipart upload for small files

#### Steps to reproduce
1. Setup to use S3
2. Upload a small file

#### Expected behavior
File should be uploaded to S3 without using MPU

#### Observed behavior (that appears unintentional) 
File is uploaded using MPU

#### Possible fixes
Don't use MPU for files <5MB

S3 even recommends not using it for files smaller than 100 MB: https://docs.aws.amazon.com/AmazonS3/latest/userguide/mpuoverview.html

MPU adds extra server load and makes troubleshooting S3 issues more complex than it needs to be for small files.

**Comment by amyblais** [comment]
@bbodenmiller What Mattermost server version are you on? Do you see any errors in Mattermost logs?

**Comment by bbodenmiller** [comment]
@amyblais 6.2.1. There are not errors in the logs but our object storage provider is complaining that we are using MPU when not necessary.

**Comment by agnivade** [comment]
Our minPartSize is set to 5MB. Are you seeing MPU for files smaller than 5MB?

https://github.com/mattermost/mattermost-server/blob/52ac449012a0ac48b0c0c58b42de2abe31f31279/shared/filestore/s3store.go#L460

**Comment by agnivade** [comment]
That's interesting. This may be a bug in the [minio](https://github.com/minio/minio-go) library that we use.

**Comment by amyblais** [comment]
> That's interesting. This may be a bug in the [minio](https://github.com/minio/minio-go) library that we use.

Do we create a ticket or report to Minio?

**Comment by agnivade** [comment]
I can take care of it @amyblais.

**Comment by agnivade** [comment]
Hey @bbodenmiller - I looked into this. It is indeed doing a multi-part upload, but the min part size is still respected. So for files smaller than 5MB, it does not make multiple PUT requests. The `partNumber=1` is just added only once.

But the upload session creation does indeed take extra overhead.

We discussed this further internally, and we traced it back to this [PR](https://github.com/mattermost/mattermost-server/pull/15252). This started to happen when we passed `-1` as the objectSize instead of the length. We did this to:
1. Avoid unnecessary memory allocation.
2. Support chunked uploads via proxies which don't have the Content-length header set.

So technically speaking, we can avoid MPU for all requests with a `Content-Length` header set. However, our experience with S3 uploads has been very poor and we would want a gradual path forward. We decided that a safe compromise can be to pass the lengths for the thumbnail and preview images which get generated and uploaded as well. Since these images are in our control, there is nothing to worry about and the code change is also small.

Avoiding MPU globally is a slightly larger effort, and once the first change settles down in production for a few versions, we will look into making the next step.

Thank you for bringing this up!

**Comment by bbodenmiller** [comment]
@agnivade it sounds like https://github.com/mattermost/mattermost-server/pull/20711 only partially fixes this?

**Comment by agnivade** [comment]
Correct. We can never fix this fully due to reasons mentioned above. #20711 was the safest set of optimizations we can do without drastic code changes. If, even after this optimization, your server runs into heavy load, I'd suggest to perhaps increase the server capacity to handle more requests.

**Comment by agnivade** [comment]
Reopening because the fix was reverted, due to an unrelated failure.
