### ISSUE TITLE
no gender neutral doctor emoji

### ISSUE THREAD

**Issue by hairmare** [mattermost/mattermost-server#20318]
#### Summary
For :man_health_worker: we have `:male-doctor:` and `:man_health_worker:` and for :woman_health_worker: we can use `:female-doctor:` and `:woman_health_worker:`. For :health_worker: there is no `:doctor:`, only `:health_worker:`. 

#### Steps to reproduce
Search for "doctor" in emojis and see these:

![image](https://user-images.githubusercontent.com/116588/171026989-83a860c3-fe06-40ac-8844-d514f039a0dc.png)

Search for "health" and a gender neutral emojii shows up as well:

![image](https://user-images.githubusercontent.com/116588/171027098-d1f7c2ea-70ad-4796-a00d-6207c3bfe2cb.png)

#### Expected behavior

A search for "doctor" should also display the gender neutral emoji, after all gender isn't a requirement for the title.

#### Observed behavior (that appears unintentional) 

See above in steps to reproduce.

Please note that other emojis might be affected as well, i'm reporting doctor since it's the only one i found with a cursory search.

#### Possible fixes
I'm assuming the fix would be in `model/emoji_data.go`.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-44691.

**Comment by hmhealey** [comment]
Thanks for the report!

Interestingly, it looks like `male-doctor` and `female-doctor` are non-standard names for those emojis supported currently only by Slack according to Emojipedia. `health_worker` and its variants are the standard names. We have some non-standard emoji aliases, but most of those are from GitHub since we were using their emoji list previously, so I'm not sure how we ended up with ones from Slack. I’d rather not deviate from the standard too much more, but I think we can make an exception for this.

The fix actually involves updating https://github.com/mattermost/mattermost-webapp/blob/master/build/emoji/additional_shortnames.json and using that to regenerate the emoji data files. I can queue that up for us to work on at some point, but if you'd be interested in helping, I can give you some pointers on how to do that

**Comment by Haliax** [comment]
I am pretty sure that additional pull request for the Mobile and Gekidou are needed as well.

But someone with more experience in mobile development needs to check that.

**Comment by hmhealey** [comment]
Maybe @avinashlng1080 can confirm since it looks like he's the last one that worked in this area, but I think they just need to have their copies of `emoji.json` updated. I hope it's just as simple as copying that over, but there's a chance that it might need some more work since neither mobile branch seems to have been updated to use the most recent version of emoji.json before this
