### ISSUE TITLE
Typing event is not generating in mattermost websockets

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [mattermost/mattermost-server#20347]
#### Summary
Typing event is not showing in WebSocket messages. We are broadcasting an event when there is a typing event, but the incoming typing events are still not showing. We are able to see other events, like posted, status changes, etc.

<img width="1344" alt="Screenshot 2022-06-02 at 7 29 17 PM" src="https://user-images.githubusercontent.com/9896335/171646469-f2240866-b3b9-49d5-8dd3-1cedca92e251.png">

When there is another WebSocket (Open Vidu) it's shown as the typing event broadcasting as failed.

<img width="1680" alt="Screenshot 2022-06-02 at 7 26 15 PM" src="https://user-images.githubusercontent.com/9896335/171646291-fd6d7a2e-a4df-4ba8-949a-8b644a698fae.png">

#### Steps to reproduce
Type messages in the matter most channels or one to one messages

#### Expected behavior
Incoming typing events should come properly

#### Observed behavior (that appears unintentional) 
NA

#### Possible fixes
NA

Please help in fixing this issue

**Comment by rajeshwarpatlolla** [comment]
Thanks @amyblais

**Comment by rajeshwarpatlolla** [comment]
Any update on this issue? Anyone has some information about why it's not generating the event?

**Comment by hmhealey** [comment]
Hi @rajeshwarpatlolla. If this is only happening with OpenVidu enabled, it's possible that that's interfering with the websocket handling somehow. Is that coming from a plugin of some sort, or is it a browser addon that's adding that to Mattermost?

Seeing a null channel_id like in the second screenshot is very odd since we default it to the empty string when we're outside of a channel
