### ISSUE TITLE
display who read the message in the channel

### ISSUE THREAD

**Issue by stillya** [mattermost/mattermost-server#20510]
In Telegram you can see who read the message in channel.
I think it's good feature, because right now I gotta set reaction on message to let know user who mentioned me that I read it and he doesn't need to repeat it me in DM.
![Screenshot 2022-06-21 at 03 05 37](https://user-images.githubusercontent.com/39978392/174677716-9bb6b3f0-d270-4be1-a641-eb8988df4831.png)

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @stillya!

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please let us know.

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by stillya** [comment]
I started exploring project to implement this feature, am I right that functionality to mark message as readed implemented on front, and backend just update last activity? If it's true this feature is gonna be hard to implement.

**Comment by ramdash1985** [comment]
Awesome Feature It is.

**Comment by nuclear868** [comment]
Hello,
As I can see, looking at the Mattermost API, there is already something similar:
In the response for 'Get channel members' request, for each channel member, the 'last_viewed_at' field is set to the timestamp of the last message that the user has seen in the channel. It seems to work for group channels and private channels.

The only issue is, that there is no websocket packet sent when the 'last_viewed_at' time has changed for particular channel member, but the client (frontend) needs to request it. But if I'm not wrong, the server already has the information, for every channel member, the last message that he has seen.

I have found this, because I'm developing a QT mattermost client, and I'm looking what the API provides.
