### ISSUE TITLE
Hotkeys steal/override more global hotkeys, and are not configurable, changable or deactivatable (in the client)

### ISSUE THREAD

**Issue by Gaibhne** [mattermost/mattermost-server#20530]
#### Summary
When the Mattermost web client is focused, it hijacks already assigned hotkeys, with no way to opt out other than to close the client.

#### Steps to reproduce
1. Assign a hotkey to something else (Ferdium Team switching in my case)
2. Open Mattermost web client
3. Hotkeys assigned in 1. no longer work if Mattermost assigned the same ones

#### Expected behavior
Mattermost to either ask before overwriting the assignment, or at least allowing me to configure or disable its own hotkeys.

#### Observed behavior (that appears unintentional) 
Hotkeys assigned to other apps no longer work if Mattermost assigned the same ones and is focused.

#### Possible fixes
Check hotkey assignment at start, allow us to configure hotkeys or allow us to disable hotkeys altogether.

**Comment by amyblais** [comment]
Opened: https://mattermost.atlassian.net/browse/MM-45292.

**Comment by hmhealey** [comment]
Thanks for the report! It's intended that we override certain hotkeys (like ctrl+u overriding show source in the browser), but I can definitely see situations you'd want to turn those off.

Normally, we'd direct you to file a feature request, but I see you've already done that, so thanks for that. Hopefully, we can get some more community support on that which'd let us prioritize it. I'd personally be interested in making our hotkeys configurable, and I'm not the only one on the team interested in improving that, but it hasn't been something that we've been able to get to quite yet.

I'm going to close this for now since that's our usual process for things that aren't bugs, but I'll keep the corresponding Jira ticket around since it's definitely a good feature that we should be looking into at some point.
