### ISSUE TITLE
Performance monitoring: Metrics endpoint /metrics returns 404 page not found

### ISSUE THREAD

**Issue by skraus-dev** [mattermost/mattermost-server#20570]
#### Summary

/metrics endpoint is advertised in root-url path `/` but `/metrics` returns `404 page not found`

#### Steps to reproduce

1. Enable perfomance monitoring in Mattermost System Console (see: https://docs.mattermost.com/scale/performance-monitoring.html)
2. Restart mattermost
3. Test the root endpoint via curl: `curl -v http://<ip>:<port>/`
4. Test the advertised metrics endpoint `curl -v http://<ip>:<port>/metrics`

##### Sysinfo

OS: Linux (kernel 5.18.8)
Docker version 20.10.16, build aa7e414fdc
Running deployment from: https://github.com/mattermost/docker
Mattermost version: Tested 6.3 and 7.0
License: None / Test setup

Only thing changed from the `env.sample` -> `.env`:

#### Expected behavior

`/metrics` endpoint returning actual prometheus metrics.

#### Observed behavior (that appears unintentional) 

Working root path on performance monitoring http port::

```
$ curl -v http://172.20.0.3:8067/
*   Trying 172.20.0.3:8067...
* Connected to 172.20.0.3 (172.20.0.3) port 8067 (#0)
> GET / HTTP/1.1
> Host: 172.20.0.3:8067
> User-Agent: curl/7.83.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 29 Jun 2022 20:54:41 GMT
< Content-Length: 714
< Content-Type: text/html; charset=utf-8
< 

			<html>
				<body>
					<div><a href="/metrics">Metrics</a></div>
					<div><a href="/debug/pprof/">Profiling Root</a></div>
					<div><a href="/debug/pprof/cmdline">Profiling Command Line</a></div>
					<div><a href="/debug/pprof/symbol">Profiling Symbols</a></div>
					<div><a href="/debug/pprof/goroutine">Profiling Goroutines</a></div>
					<div><a href="/debug/pprof/heap">Profiling Heap</a></div>
					<div><a href="/debug/pprof/threadcreate">Profiling Threads</a></div>
					<div><a href="/debug/pprof/block">Profiling Blocking</a></div>
					<div><a href="/debug/pprof/trace">Profiling Execution Trace</a></div>
					<div><a href="/debug/pprof/profile">Profiling CPU</a></div>
				</body>
			</html>
* Connection #0 to host 172.20.0.3 left intact
```

/metrics endpoint not working

```
$ curl -v http://172.20.0.3:8067/metrics
*   Trying 172.20.0.3:8067...
* Connected to 172.20.0.3 (172.20.0.3) port 8067 (#0)
> GET /metrics HTTP/1.1
> Host: 172.20.0.3:8067
> User-Agent: curl/7.83.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Wed, 29 Jun 2022 20:55:26 GMT
< Content-Length: 19
< 
404 page not found
* Connection #0 to host 172.20.0.3 left intact
```

#### Possible fixes

Unsure if this is relevant...

Root-path response is assembled:

https://github.com/mattermost/mattermost-server/blob/7e4024665c2f300bd9a3e147bcb78d4dc33dbf62/app/server.go#L1644-L1659

Endpoints get registered (no handler func for `/metrics` to be seen):

https://github.com/mattermost/mattermost-server/blob/7e4024665c2f300bd9a3e147bcb78d4dc33dbf62/app/server.go#L1668-L1684

**Comment by amyblais** [comment]
Opened https://mattermost.atlassian.net/browse/MM-45467.

**Comment by agnivade** [comment]
HI @skraus-dev - Do you have an enterprise license? Metrics are only available on licensed versions.

**Comment by agnivade** [comment]
Self-hosted and enterprise are not a disjoint set. You can self-host Mattermost using an enterprise license.

Performance monitoring in team edition will just return your CPU/Mem profile endpoints. In enterprise, it will return the metrics endpoints as well.

Initially, this was _entirely_ an enterprise feature, but then we included the profile endpoints in the team edition because they are something that is available be default in Go applications.

**Comment by ltning** [comment]
Requiring an enterprise license for the metrics endpoint is detrimental to our ability to contribute to the Mattermost project. We cannot purchase an enterprise license because we are prohibited from running binaries from 3rd parties (not compiled from publicly-available source code).
We, like many others, are experiencing serious performance issues with recent MM releases but without metrics it's much harder to diagnose and provide useful feedback to the project.
I really don't think being able to scrape metrics should be an enterprise feature - but for the sake of this discussion, our inability to have/use an enterprise license leads to an inability to support the project.
