### ISSUE TITLE
Patching plugin configuration replace all plugins configs

### ISSUE THREAD

**Issue by remyj38** [mattermost/mattermost-server#20584]
#### Summary
The API Patch configuration endpoint (PUT on config/patch) doesn't patch the PluginSettings.Plugin object but replace it.

#### Steps to reproduce
1. Add a configuration for a plugin :
    ```shell
    curl --request PUT \
      --url https://you_mattermost_server/api/v4/config/patch \
      --header 'Authorization: Bearer your_token' \
      --header 'Content-Type: application/json' \
      --data '{
    	"PluginSettings": {
    		"Plugins": {
    			"com.mattermost.plugin1": {
    				"my_param": true
    			}
    		}
    	}
    }'
    ```
2. Add a configuration for another plugin:
   ```shell
    curl --request PUT \
      --url https://you_mattermost_server/api/v4/config/patch \
      --header 'Authorization: Bearer your_token' \
      --header 'Content-Type: application/json' \
      --data '{
    	"PluginSettings": {
        		"Plugins": {
    			"com.mattermost.plugin2": {
    				"my_param": true
    			}
    		}
    	}
    }'
    ```
3. Get the configuration and see that the configuration for plugin1 is missing:
   ```shell
    curl --url https://you_mattermost_server/api/v4/config \
      --header 'Authorization: Bearer your_token'  | jq '.PluginSettings.Plugins'
    ```
#### Expected behavior
The endpoint should patch the configuration recursively and don't remove some configuration keys

#### Observed behavior (that appears unintentional) 
PluginSettings.Plugins kept only the last data sent to the patch endpoint and loses all other plugins settings

**Comment by streamer45** [comment]
@agarciamontoro Could you help to verify this and open a ticket if necessary?

**Comment by agarciamontoro** [comment]
Thanks for the report, @remyj38. I can indeed reproduce this, and created a ticket to track it: https://mattermost.atlassian.net/browse/MM-45515 We need to investigate this well, because this behaviour does not technically go against the PUT semantics (it may be actually too flexible when preserving the other fields of that plugin configuration).

**Comment by agnivade** [comment]
Hi @remyj38 - we discussed this internally. The issue is that since the Plugins are stored as a map, individual fields of a map aren't patched, because you can recursively go down to any depth of a map. Trying to support patch on a map will incur additional complexity which we would like to avoid. As a workaround, I'd suggest using the update config (PUT api/v4/config) endpoint rather than patch config.

Would you be interested in sending a PR in https://github.com/mattermost/mattermost-api-reference/ to document this behavior?

**Comment by Clash-ion** [comment]
Hey, I am willing to take this just tell me what will be a good place to document this part...

**Comment by amyblais** [comment]
> Hey, I am willing to take this just tell me what will be a good place to document this part...

@agnivade Do you have an idea?

**Comment by agnivade** [comment]
> Would you be interested in sending a PR in https://github.com/mattermost/mattermost-api-reference/ to document this behavior?

You need to send a PR to this repo. Please check the API endpoint in the yaml file and update the description.
