### ISSUE TITLE
sql - collation

### ISSUE THREAD

**Issue by kullrich** [mattermost/mattermost-server#20636]
Dear Mattermost,

after upgrading from Ubuntu16 to Ubuntu20 and after the OS upgrade from Mattermost v5.37 to 7.0.1 we still have some problems with the sql.

The first problem was:

```
Illegal mix of collations (utf8mb4_general_ci,IMPLICIT) and (utf8mb4_0900_ai_ci,IMPLICIT)
```

Than we changed the sql database accordingly into `utf8mb4_general_ci`

and now still have the following errors:

```
51562:{"timestamp":"2022-07-12 13:58:46.388 +02:00","level":"warn","msg":"Table collation mismatch","caller":"sqlstore/store.go:1142","table_name":"incomingwebhooks","expected":"utf8_general_ci","found":"utf8mb4_general_ci"}
51563:{"timestamp":"2022-07-12 13:58:46.391 +02:00","level":"warn","msg":"Table collation mismatch","caller":"sqlstore/store.go:1142","table_name":"preferences","expected":"utf8_general_ci","found":"utf8mb4_general_ci"}
51564:{"timestamp":"2022-07-12 13:58:46.393 +02:00","level":"warn","msg":"Table collation mismatch","caller":"sqlstore/store.go:1142","table_name":"users","expected":"utf8_general_ci","found":"utf8mb4_general_ci"}
51565:{"timestamp":"2022-07-12 13:58:46.395 +02:00","level":"warn","msg":"Table collation mismatch","caller":"sqlstore/store.go:1142","table_name":"uploadsessions","expected":"utf8_general_ci","found":"utf8mb4_general_ci"}
51566:{"timestamp":"2022-07-12 13:58:46.398 +02:00","level":"warn","msg":"Table collation mismatch","caller":"sqlstore/store.go:1142","table_name":"channels","expected":"utf8_general_ci","found":"utf8mb4_general_ci"}
51567:{"timestamp":"2022-07-12 13:58:46.400 +02:00","level":"warn","msg":"Table collation mismatch","caller":"sqlstore/store.go:1142","table_name":"publicchannels","expected":"utf8_general_ci","found":"utf8mb4_general_ci"}
51587:{"timestamp":"2022-07-12 13:59:24.607 +02:00","level":"warn","msg":"Failed to write link metadata","caller":"app/post_metadata.go:688","request_url":"https://twitter.com/,"error":"could not save link metadata: Error 3988: Conversion from collation utf8_general_ci into utf8mb4_bin impossible for parameter"}
```

Could you please in the next upgrade round of Mattermost include a small sql check and automatic upgrade for that problem?

Thank you in anticipation

Best regards

Kristian

**Comment by agnivade** [comment]
HI @kullrich - which small check and automatic upgrade are you referring to?

**Comment by kullrich** [comment]
I guess, you should check this problem for any sql scheme upgrade.

**Comment by agnivade** [comment]
@kullrich - This issue can happen if your connection collation and table collations are different. We already detect that for some tables (as you can see from the log above), but we have avoided doing that for all tables to prevent any false positives.

The solution is to set the same collation for both connection and the table. There are different collations at different levels - connection, database, table, column. And due to various reasons, DB administrators can choose to set different collation levels for different objects. Depending on the situation, it may be right or wrong.

At best, we can detect and flag cases where we are 100% sure it won't work. And we leave it to the administrators to fix it themselves.

Adding the steps to the documentation sounds like a good first step. Would you be interested in sending a PR?

**Comment by Clash-ion** [comment]
Hey, I am willing to take this issue, can you point me to the file where I can document these changes?

**Comment by agnivade** [comment]
@cwarnermm - could you help point to the right place here?

**Comment by cwarnermm** [comment]
Hello, @kullrich, and thank you for helping update the Mattermost product documentation! 

The [Prepare to upgrade Mattermost](https://docs.mattermost.com/upgrade/prepare-to-upgrade-mattermost.html) page feels like a natural fit for the information you're looking to add. I'm happy to help with any questions you have about working in ReStructured Text (RST) format.
