### ISSUE TITLE
link_metadata.go: undefined: opengraph.Image

### ISSUE THREAD

**Issue by scriptdealer** [mattermost/mattermost-server#21169]
#### Summary
While writing a plugin, I have troubles compiling it. 

#### Steps to reproduce
Make `github.com/mattermost/mattermost-server/v6/model` import in .go file  
then `go build` it

#### Expected behavior
Plugin should compile

#### Observed behavior (that appears unintentional) 
Build fails with:  
`../../pkg/mod/github.com/mattermost/mattermost-server/v6@v6.7.2/model/link_metadata.go:53:39: undefined: opengraph.Image`  

#### Possible fixes
Looks like you need to update go.mod with `github.com/dyatlov/go-opengraph v1.0.1` and skip that `exclude` hack.

**Comment by scriptdealer** [comment]
I can see that present model/link_metadata.go has `"github.com/dyatlov/go-opengraph/opengraph/types/image"` import, but what I get in my ~\go\pkg has no such line. This is true for 6.7.2, 6.3.0, 6.2.1. And this is strangely enough, as my previous plugin compiled successfully with 6.3.0

**Comment by amyblais** [comment]
@scriptdealer Would you be open to posting about this on our [Peer-to-peer Help channel](https://community.mattermost.com/core/channels/peer-to-peer-help) or at https://forum.mattermost.com/? One of our devs or community members will likely be able to help troubleshoot this question.

**Comment by ITCDEK** [comment]
Thanks Amy, I'll try p2p and report back then

**Comment by scriptdealer** [comment]
Deleting go.mod and initing again did not help, but when I deleted again and added /m/v2 to the plugin's module path, it miraculously starts compiling.  What da hell was that ?

**Comment by dylanrichards** [comment]
There was a complete rewrite of go-opengraph which caused incompatibilities.
(v1.0.0 https://github.com/dyatlov/go-opengraph/commit/3e69469c7ac3948a5ca3043725374d0719584f2e) (v1.0.1 https://github.com/dyatlov/go-opengraph/commit/606d7b1e5f8a10c668c20bba5001b8a2ebbb594b)

In your go.mod file replace the new version of go-opengraph
`github.com/dyatlov/go-opengraph/opengraph v0.0.0-20220524092352-606d7b1e5f8a`
with `github.com/dyatlov/go-opengraph v0.0.0-20210112100619-dae8665a5b09`

In mattermost-server, this was fixed in v7.3.0 by https://github.com/mattermost/mattermost-server/pull/20701

**Comment by whereMyCleanCode** [comment]
Hi @scriptdealer ! What exactly did you delete? Just im collision with same problem(
