### ISSUE TITLE
s3 upload CRC32C error

### ISSUE THREAD

**Issue by baek-sang** [mattermost/mattermost-server#22221]
#### Summary
Mattermost Version: 7.7.1
Upload fail s3 strage(cloudflare r2)

#### Steps to reproduce
Try upload file.

#### Expected behavior
Upload success.

#### Observed behavior (that appears unintentional) 
<img width="718" alt="mm-s3-error" src="https://user-images.githubusercontent.com/69100154/216241763-9c9a4075-550f-4a50-a3e4-ba9edac97584.png">
Test successful

but
```
{"timestamp":"2023-02-02 05:33:16.623 Z","level":"error","msg":"Unable to write the file.","caller":"web/context.go:117","path":"/api/v4/files","request_id":"~","ip_addr":"1.2.3.4","user_id":"~","method":"POST","err_where":"WriteFile","http_code":500,"error":"WriteFile: Unable to write the file., unable write the data in the file 20230202/teams/noteam/channels/~~/users/~~/~~/test-image.png: Header 'x-amz-checksum-algorithm' with value 'CRC32C' not implemented"}
```

**Comment by agnivade** [comment]
Hi, I believe you already created https://github.com/mattermost/mattermost-server/issues/20582 in the past. This time, it looks like a different error, but I think the core issue is still that Cloudflare R2 doesn't support minio client. There is not much we can do here since our primary target is AWS S3 and other minio compatible targets.

If you want, you can raise an issue over at https://github.com/minio/minio-go to check if there's something that can be done with minio.

**Comment by lahdekorpi** [comment]
@agnivade [There is now an option in minio](https://github.com/thanos-io/objstore/pull/85/files) for setting `SendContentMd5` in the `minio.PutObjectOptions`.

Could this be implemented in [s3PutOptions](https://github.com/mattermost/mattermost/blob/master/server/platform/shared/filestore/s3store.go#L750) similarly to the signV2 or encryption?

I'm new to the project so apologies for my ignorance; not sure how hard setting up a dev environment for Mattermost would be, but if not, I would like to test this out. Well, if this is something that would even be accepted.
I'm familiar with go, Cloudflare R2 and Backblaze B2, and have access to test with both to make their S3 implementations compatible as well.

**Comment by agnivade** [comment]
I'm sorry I don't understand the relation with MD5 to the checksum parameter. 

As I mentioned earlier, CloudFlare R2 doesn't have 100% compatibility with AWS S3 as mentioned here: https://developers.cloudflare.com/r2/api/s3/api/. (Search for `x-amz-checksum-algorithm`) And that's why it's failing when MM client sends that header.

The part about MD5 is a separate [header](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#checking-object-integrity-md5), but it doesn't do anything about the checksum header which will still get passed.

**Comment by lahdekorpi** [comment]
> I'm sorry I don't understand the relation with MD5 to the checksum parameter.
> 
> As I mentioned earlier, CloudFlare R2 doesn't have 100% compatibility with AWS S3 as mentioned here: https://developers.cloudflare.com/r2/api/s3/api/. (Search for `x-amz-checksum-algorithm`) And that's why it's failing when MM client sends that header.
> 
> The part about MD5 is a separate [header](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#checking-object-integrity-md5), but it doesn't do anything about the checksum header which will still get passed.

Maybe I misunderstood something but from what I can see from here https://github.com/minio/minio/discussions/18324#discussioncomment-7393791 the CRC32C is not sent if the MD5 is used for the checksum.

**Comment by lahdekorpi** [comment]
As a POC, I tested the minio-go library with my Cloudflare R2 bucket and sent a file using `SendContentMd5 = true`.
I may still be missing something. Or maybe the error coming from somewhere other than the `PutObject`?

```go
package main

import (
	"context"
	"fmt"
	"log"
	"strings"

	s3 "github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	// Initialize minio client object.
	s3Client, err := s3.New("REDACTED.eu.r2.cloudflarestorage.com", &s3.Options{
		Creds:  credentials.NewStaticV4("REDACTED", "REDACTED", ""),
		Secure: true,
	})
	if err != nil {
		log.Fatalln(err)
	}

	ctx := context.Background()

	bucketName := "mattermost"

	content := strings.Repeat("A", 10*1024*1024) // 10MB of 'A's
	reader := strings.NewReader(content)
	objectName := "10MB-dummy-file"
	contentType := "application/octet-stream"

	info, err := s3Client.PutObject(ctx, bucketName, objectName, reader, int64(reader.Len()), s3PutOptions(true, contentType, 5*1024*1024))
	if err != nil {
		log.Fatalln(err)
	}

	fmt.Printf("Successfully uploaded %s of size %d\n", objectName, info.Size)
}

func s3PutOptions(encrypted bool, contentType string, uploadPartSize int64) s3.PutObjectOptions {
	options := s3.PutObjectOptions{}
	log.Println("encrypted", encrypted)
	log.Println("uploadPartSize", uploadPartSize)
	log.Println("contentType", contentType)

	options.ContentType = contentType
	options.PartSize = uint64(uploadPartSize)
	options.SendContentMd5 = true

	return options
}
```

```bash
go run main.go
2024/05/28 22:25:02 encrypted true
2024/05/28 22:25:02 uploadPartSize 5242880
2024/05/28 22:25:02 contentType application/octet-stream
Successfully uploaded 10MB-dummy-file of size 10485760
```

<img width="790" alt="image" src="https://github.com/mattermost/mattermost/assets/570545/a0b91efe-cd2c-47bf-9943-45cdb6d5be82">

**Comment by agnivade** [comment]
> Maybe I misunderstood something but from what I can see from here https://github.com/minio/minio/discussions/18324#discussioncomment-7393791 the CRC32C is not sent if the MD5 is used for the checksum.

Ah okay. Then I probably made a mistake in reading the code. 

In any case, it seems like a workaround trying to support Cloudflare R2. I think it would fall on Cloudflare's side to support the S3 API more closely rather than the consumer side trying to add workarounds to make it work. 

In any case, we only officially support Minio and S3. So even if it works with R2, I wouldn't recommend using that with Mattermost.
