### ISSUE TITLE
Adding member to DM group shouldn't create a fresh group

### ISSUE THREAD

**Issue by borngraced** [mattermost/mattermost-server#22492]
Currently when adding a member to a DM group, Mattermost creates a new group which I consider to be not very good UX. New member should be able to view all previous messages/discussion in DM group.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @borngraced,

Would you like to [contribute this in the feature idea forum](https://portal.productboard.com/mattermost/33-what-matters-to-you)? Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by anx-ag** [comment]
I don't think that this is how this feature is supposed to work. If you want to dynamically change participants, you will have to create channels (private or public) or convert a group message to a channel in order to be able to use the dynamic extension of such channels then. Group messages are always eactly only for the people used during creation and the members may not be changed.

**Comment by borngraced** [comment]
@anx-ag  I disagree with this, I think the better UX is allowing new member to DM to see previous messages/discussion.

for an example, discord works this way.
