### ISSUE TITLE
[Help Wanted] Create scripts to verify that every localization string is in en.json

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#6090]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-3436)

Create a script to verify that every string that needs to be localized is in `en.json` for platform and webapp and use that as a validation during the build process

**Comment by saturninoabril** [comment]
I thought about this and came up with the following suggestions on how to parse/process each localization from code files and make it maintainable in the future.
- change format of all localization ids with reference to `platform/i18n/`, e.g.:
  from `"id": "api.channel.add_member.added",` 
  to `"id": "i18n.server.api.channel.add_member.added",`
- change format of all localization ids with reference to `platform/webapp/i18n/`, e.g.:
  from `"i18n.client.add_command.autocomplete": "Autocomplete",` 
  to `"i18n.client.add_command.autocomplete": "Autocomplete",`
- add localization [style guide](https://docs.mattermost.com/developer/style-guide.html) for reference.

If it sounds interesting, I'll create PR with updates of all localization ids of all files and localization test script added at `Makefile`.

**Comment by enahum** [comment]
Hey @saturninoabril thanks for having a look into this.

I really don't think changing the keys (id's) of the localization strings is the issue here nor it will help resolve it, in reality changing those keys will result in the localization community to go through every "new" key and "re-translate" and I don't think that is what we want to accomplish here.

In the beginning I was thinking along the lines of:
* Run a golang parser that will look for any string that is the second parameter of `model.NewLocAppError` and any other function that is used for translations and creates a temp file with those keys and then is compared agains the `i18n/en.json` file
* Run a JS parser that looks for `FormattedMessage`, `FormattedHTMLMessage`, `defineMessages`, `utils.localize` and so on to accomplish the same functionality as the one described for golang.

does it make sense to you?

**Comment by kaakaa** [comment]
Hi all.
I had written golang script for checking mm messages.
[kaakaa/mattermost-missing-message-checker](https://github.com/kaakaa/mattermost-missing-message-checker)

But I know that my script don't do the check perfectly because of wrong [regexp](https://github.com/kaakaa/mattermost-missing-message-checker/blob/master/parser.go#L14).
So manual work was needed.

I hope this would  be helpful.

**Comment by saturninoabril** [comment]
@enahum thanks for sharing. I also thought about such parsing patterns initially and I found it easy for those functions that used localization id as parameter directly, e.g.:
	`c.Err = model.NewLocAppError("", "api.context.missing_teamid.app_error", nil, "TeamIdRequired")`

However, I find it difficult when such localization id is initially declared in a variable (immediately used in succeeding line or referenced somewhere else), e.g.:

at https://github.com/mattermost/platform/blob/master/model/user.go#L137
```
	id := fmt.Sprintf("model.user.is_valid.%s.app_error", fieldName)
	details := ""
	if userId != "" {
		details = "user_id=" + userId
	}
	return NewAppError("User.IsValid", id, nil, details, http.StatusBadRequest)
```

at https://github.com/mattermost/platform/blob/master/model/authorization.go#L82
```
	PERMISSION_INVITE_USER = &Permission{
		"invite_user",
		"authentication.permissions.team_invite_user.name",
		"authentication.permissions.team_invite_user.description",
```

at https://github.com/mattermost/platform/blob/master/app/command_shortcuts.go#L40
```
func (me *ShortcutsProvider) DoCommand(args *model.CommandArgs, message string) *model.CommandResponse {
	shortcutIds := [28]string{
		"api.command_shortcuts.header",
		// Nav shortcuts
		"api.command_shortcuts.nav.header",
		"api.command_shortcuts.nav.prev",
...
```

at https://github.com/mattermost/platform/blob/master/store/sql_channel_store.go#L21
```
const (
	MISSING_CHANNEL_ERROR        = "store.sql_channel.get_by_name.missing.app_error"
	MISSING_CHANNEL_MEMBER_ERROR = "store.sql_channel.get_member.missing.app_error"
	CHANNEL_EXISTS_ERROR         = "store.sql_channel.save_channel.exists.app_error"
	...
)
```

Variation might increase in the future with introduction of new functions/variables. (In effect, the localization test script should be updated as well.)
That's why I step back and suggest for this major change to have standard prefix format for localization id. I don't know how the localization community works but I don't think changing the localization id requires re-translation.

@kaakaa nice work! Does it work with the localization id declared in a variable like I mentioned above? Or would you like to update your script so we can solve this issue? thanks

**Comment by kaakaa** [comment]
@saturninoabril 
No, it's impossible to check the message id declared in variable by my script...
My script checks only arguments in functions for i18n like `FormattedMessage`(js), `model.NewLocAppError`(go) and so on.

If we would like to check all message ids, I think it may need not only to parse text by regexp but to analyze runtime. But still I don't know if it would be perfect.
Or we have to discuss another ways.

**Comment by rodcorsi** [comment]
Some time ago I worked on a change in [goi18n](https://github.com/nicksnyder/go-i18n/issues/50), I think this could help in this case.

**Comment by simon0191** [comment]
Hey! What do you think about registering each call to a translation function in both backend and frontend of the pre-release instance and then use the list of registries to check which translations are missing.

For example, "register" the translation key inside NewLocAppError like this:
```
func NewLocAppError(where string, id string, params map[string]interface{}, details string) {
   if app.RegisterTranslationKeysEnabled() {
      RegisterTranslationKey(id)
   }
   ...
}
```

`RegisterTranslationKey`may log the key with some prefix so it can be easily searchable later in the logs or it can register it in a Set in Redis or whatever you prefer.

Then, after 1 week or so you can download the registries (from the logs or the redis) and check wich ones are missing in the translation files.

*Pros:* Easy to implement since it only requires to add a function call to all the translation functions.

*Cons:* It won't register the translation keys that were not used during the week. But the whole process is repeatable and eventually all the translation keys will be registered or at least the ones that are actually used.

**Comment by ccbrown** [comment]
My instincts say that attempting this statically, without changing existing code, is actually a variation of the halting problem, and is mathematically impossible.

As for a dynamic approach, @simon0191's suggestion is doable, but I think the con is far too great. A feedback loop of 1 week is far too long, and the coverage will likely be very low since many of our localized strings aren't regularly used in typical usage (e.g. error strings, which are very important, but hopefully rarely displayed).

In my opinion, using the approach @rodcorsi implemented in https://github.com/nicksnyder/go-i18n/issues/50 is the best way for Go. It's a definite way to ensure that every localization string is in en.json, and you'll find out if you've forgotten something as soon as you attempt to compile.

**Comment by rodcorsi** [comment]
Similar approach we have for React is [react-intl-translations-manager](https://github.com/GertjanReynaert/react-intl-translations-manager), but in both cases we need to change the existing code.

**Comment by meilon** [comment]
I started with a script and I added it to the cmd/platform as a hidden command. Currently it only checks *.jsx under /webapp/components for FormattedMessage and searches for the id in the en.json. In this implementation alone I found 21 missing strings. The script ignores message ids via variables, because finding all of them by parsing is close to impossible. If you want 100% failsafe coverage, you have to code it in and not use a parser.

I was pointed to this issue by @jasonblais after I showed him the first results. I didn't look for an open issue, so I started from scratch. It works a little bit like @kaakaa's script, but I ignore the defaultMessage and don't generate a new, or add to the existing, en.json. This should be done manually in my opinion.

Before I make the first push and continue to add more parsing to my fork I'd like to know if this would be the right place to add the script or if the code should be added somewhere else. I think it should be a core part, but having installed separate developer tools is just as fine with me.

**Comment by ccbrown** [comment]
@meilon I don't think it should be part of our distribution. And keep in mind we'll be separating this repo into two in a few weeks. The front-end linting should live with the front-end code. The back-end linting should live with the back-end code.

I would probably just make a scripts directory inside of webapp and put it there. There might be other things you could move there too like the emoji script.

**Comment by meilon** [comment]
Okay, then I'll wait for the split and refine my code a little before making the first PR

**Comment by hanzei** [comment]
@jespino Is this something which could or should be done with https://github.com/mattermost/mattermost-utilities?

**Comment by jespino** [comment]
Yes, is already done through  https://github.com/mattermost/mattermost-utilities

**Comment by jasonblais** [comment]
Thanks Hanzei and Jesús! Closing given this ticket is covered by https://github.com/mattermost/mattermost-utilities
