### ISSUE TITLE
[Help Wanted] [PLT-6050] Add a prompt when user leaves System Console page with unsaved changes

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6230]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6050)

Repro

1) Go to System Console > Configuration
2) Change a bunch of settings
3) Go to another System Console tab or switch back to team site.

Observed: System Console page changes. All changes from step 2 are lost

![image](https://cloud.githubusercontent.com/assets/13119842/25412876/f96d8bc0-29f3-11e7-882c-8cc01dde846a.png)

Expected: Admin gets a prompt with title "Discard Changes?" and text "You have unsaved changes, are you sure you want to discard them?"

**Comment by emptyarray** [comment]
I can take this issue. Here is what I'm running into when planning it:

The trick part is going to be notifying `AdminConsole` from `AdminSettings` of unsaved changes. One possibility is to use prop callbacks, but this would have to go through `ReactRouter`, which looks complicated. 

The alternative would be to have `AdminSettings` fire an action whether a panel is changed or saved, and use the Redux store. `AdminSettings` is already importing from actions/admin_actions.jsx. I can add my own "unsaved" and "saved actions" in there to toggle some state in the store (`connect` would be better, but can you do connect on `AdminSettings` given that it's a base class and things are inheriting from it?). Does this mean changing both actions/admin_actions.jsx and stuff in the mattermost-redux project?

Other ideas welcome for getting the architecture right.

**Comment by hmhealey** [comment]
Using the redux store sounds like the right idea. You don't need to change mattermost-redux for that though since this'll be specific to the web app. If you take a look at `webapp/reducers` in the platform repo, you'll see some other webapp-specific code that's added to the redux store.

Now for connecting to the store, the inheritance definitely makes things tricky, but I think we can work around it for now. I think we can have the `AdminConsole` connect to the redux store and have it pass the action as a prop into the various `AdminSettings` pages like how it passes them the `config`. This is unless you want to try to reorganize the system console so that it doesn't use inheritance, but that's a whole different task :)

**Comment by emptyarray** [comment]
@hmhealey, sounds good. Made my own reducer in views and action creator.

Looks like I'm going to need a selector. Should that go in mattermost-redux, or should I make a new directory for selectors for views?

I did a little experiment to see what it would take to refactor the inheritance of the settings components, because component inheritance is evil. I made a higher order component like `AdminSettings` which can wrap the settings components. Instead of `ConfigurationSettings` calling superclass methods, it calls methods passed as props for handling changes. The HOC can be connected to the store. `ConfigurationSettings` would become a pure component (though that would take a bit more work because it calls other actions already which would also need to be passed as props).

This approach does work. Of course it would take a while to refactor all the settings components like this, and additional testing burden. If I go with your approach of passing actions around from `AdminConsole`, then I think I don't have to touch all the settings components because I can do everything from `AdminSettings`. Let me know which way would make more sense for this ticket.

**Comment by hmhealey** [comment]
The selector only needs to go in `mattermost-redux` if it doesn't use webapp-specific state and it's something we're likely to reuse. I wouldn't bother if it's something super specific to the webapp.

And if I understand correctly, you're meaning making something like Redux's `connect` that wraps the component and passes in the extra props? I'm fine with doing it either way. We'll want to do something like what you're suggesting eventually anyway, but don't feel the need to do that all right now. We could split that into a separate ticket for later, if that makes things easier

**Comment by emptyarray** [comment]
@hmhealey Mostly done. Going to hold off on refactoring `AdminSettings` as a higher order component, because this PR is already going to be big enough.

Question: When the user confirms discarding changes, I need to use `browserHistory.push` to send them wherever they were trying to go. Any guidelines for where I should be calling that from? From a component, or an action? Action creators aren't supposed to have side effects, but if we started using redux-thunk then we could do side effects. Noticed redux-thunk in mattermost-redux being used already.

**Comment by jasonblais** [comment]
Submitted and scheduled for v4.3 release: https://github.com/mattermost/mattermost-webapp/pull/62
