### ISSUE TITLE
[Help Wanted] [PLT-6823] Edge: Remove Mattermost Notification sound options in Account Settings

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6771]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-6823)

Repro steps:
1) Enable desktop notifications for Edge
2) Have another user send you a message

Observed: The system notification sound plays at the same time as the Mattermost one
Expected: Remove the option for Mattermost notification sound in Account settings (similar to what we do on firefox)
"Please configure notification sounds in your browser settings"

Repro steps:
1) Enable desktop notifications for Edge
2) Have another user send you a message

Observed: The system notification sound plays at the same time as the Mattermost one
Expected: Remove the option for Mattermost notification sound in Account settings (similar to what we do on firefox)
"Please configure notification sounds in your browser settings"

**Comment by Whiteaj36** [comment]
I'd like to work on this one! Few questions that I can take to Contributors as well.

1. Localization process: I only know English, and need to remove Edge from the list of browsers that would support sound in notifications. I can remove it from the default and from the english I18N string file. But is there anything I need to do to flag this for re-translation?

2. I need to edit some string IDs since 
`user.settings.notifications.desktop.allFirefoxTimed`
isn't accurate if Edge is included in this list as well now.
I was thinking
`user.settings.notifications.desktop.allSansSoundTimed` 
in order to differentiate it with 
`user.settings.notifications.desktop.allNoSoundTimed`

But again, what is needed to be done in the I18N files. Should I update all the string IDs or should I just edit the english ones?

**Comment by jasonblais** [comment]
This issue has been resolved: https://mattermost.atlassian.net/browse/PLT-6823
