### ISSUE TITLE
[Help Wanted] [PLT-959] Improve unsupported browser page

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#6841]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-959)

We want to make the following improvements to the error page displayed for users of an incompatible browser
1. Remove the "Go back to team site" link from the incompatible browser page
2. Add a list of compatible browsers, with hyperlinks to download the browsers as per below:
Your current browser is not supported. Please upgrade to one of the following browsers:

- [Google Chrome 43+](https://www.google.com/chrome/browser/desktop/index.html)
- [Firefox 52+](https://www.mozilla.org/en-US/firefox/new/)
- [Internet Explorer 11](https://www.microsoft.com/en-ca/download/internet-explorer.aspx)
- [Edge](https://www.microsoft.com/en-ca/download/details.aspx?id=48126)
- [Safari 9+](https://support.apple.com/en-us/HT204416)

To do this, you can redirect the user to <mattermost>/error?type=unsupported_browser and update the ErrorPage component (in webapp/components/error_page.jsx) to display the help text from above

**Comment by moonmeister** [comment]
I can take this but I need some clarification. Are we modifying the `LOCAL_STORAGE` error or is this a new error state we are testing for and handling?

**Comment by hmhealey** [comment]
We want a new error type like `LOCAL_STORAGE`, but we can treat it similarly where we just check it to override the contents of the page. There's also the small problem that `web/web.go` is currently preventing that error page from being loaded, but it shouldn't be too hard to stop it from doing that

**Comment by moonmeister** [comment]
@hmhealey So, is there already code detecting the incompatibility somewhere or do I need to implement the detection aspect of this as well?

**Comment by hmhealey** [comment]
Yes, it's [here](https://github.com/mattermost/platform/blob/master/web/web.go#L69) in `web/web.go`, but it currently just responds with a static string instead of the actual HTML bundle. What we might be able to do is:
1. Skip the compatibility check if viewing the error page
2. When they fail the compatibility check, redirect them to the error page instead of sending them the bad request error

**Comment by moonmeister** [comment]
@hmhealey Okay. This is making more sense now. I'll see what I can do. Thanks.

**Comment by moonmeister** [comment]
@hmhealey Okay, so looking at the code this all seem convoluted:

1. It seems like there several methods to get text into this template. One by passing a predefined type. Two by passing values through the url. Three, by passing nothing you get the "default" values.

2. The predefined "LOCAL_STORAGE" text is saved in `webapp/i18n/*.json` while the `error.generic.title` is saved in the `i18n/*.json` file. This is probably cause react is handling localization for the "local_storage" type through the `<FormattedMessage>` tag (I think). But then JS is handling localization for the "generic" type via the `Utils.localizeMessage()` function. 

Maybe this is all beyond the scope of this HW but it seems like some serious simplification could be made here. Is there a reason for two different localization methods? Is there a reason for the two different methods of passing data into the error page (template and url), can one of these be eliminated in favor of the other? 

I hope these questions make sense, maybe I'm just not understanding something. Thanks.

**Comment by hmhealey** [comment]
Passing through the URL is the older way of handling this page. The way we handle LOCAL_STORAGE is the newest addition because I didn't like the idea of passing down Markdown in a query parameter, although I just realized [we do that elsewhere](https://mattermost.atlassian.net/browse/PLT-7026). I'd be fine with switching any other client-generated errors to work like LOCAL_STORAGE, but we still need the query parameters for when the server sends back an error page (see `RenderWebError` in `utils/api.go`.

In terms of `Utils.localizeMessage` vs `FormattedMessage`, `FormattedMessage` is preferred wherever possible, but it only differs in that it supports additional templating and that it outputs a React component instead of a raw string. What you found with `error.generic.title` only existing in the serverside translation files (`i18n` instead of `webapp/i18n`) is actually a bug, but that just shows you how many people see that page 😛

**Comment by moonmeister** [comment]
@hmhealey Thanks for the explanations.  So, error.generic.title should only exist in `webapp/i18n`? or in both? If it should be in both, why is that? Seems like it only gets referenced from the webapp and not from the server.

**Comment by hmhealey** [comment]
I can't find any uses of it on the server either, so yes, it should only exist in `webapp/i18n`. It's very rare that we need a to share a string between both places.

**Comment by moonmeister** [comment]
@hmhealey  Thanks. 

So, I've been thinking about how to do this. It seems quite verbose to define bullet points explicitly for every error type we want to create. Maybe be it's the best way, but I was thinking if we could dynamically generate the bullet points it'd simplify things. Given I don't actually have access to the value of `error.error_state.help#` it makes it difficult to do anything with the data. Should we statically define this data or is there a good way we could make this more flexible for future error states?
