### ISSUE TITLE
[Help Wanted] [PLT-7298] Add "Edit Account Settings" link to bottom of your own profile popover

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7113]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7298)

Add "Edit Account" link to bottom of your own profile popover.

![image](https://user-images.githubusercontent.com/13119842/28933762-5794985a-784c-11e7-88db-df7b38b673a2.png)

Clicking the link opens the Mattermost Account Settings, performing the same action as CTRL/CMD+SHIFT+A.

NOTE: This link should only appear for your own account.

**Comment by santos22** [comment]
I can take this one 😄

**Comment by jasonblais** [comment]
Yay, awesome! Thanks @santos22!

**Comment by santos22** [comment]
Hi Jason, I'm really excited to be working on this issue! I've made some progress and it can be found [here](https://github.com/santos22/platform/commit/312ac4bef260d0602252b2eaa5be09e0c18e9d52).

I've noticed that after I edit and save account information either by clicking on the profile popover link or by doing it through the sidebar, the **Edit Account Settings** link disappears. I've attached some images to this comment to show what I mean. What I am doing is not much different from how the email link is added and displayed on the profile popover, yet the email link never disappears. I've joined the "Contributors" community channel but I'm not sure what public channel to pose my problem/question in!

![screen shot 2017-08-07 at 8 40 05 pm](https://user-images.githubusercontent.com/7004949/29055423-57f3dde8-7bb1-11e7-993e-da37f17369a5.png)

![screen shot 2017-08-07 at 8 40 37 pm](https://user-images.githubusercontent.com/7004949/29055427-5c73d1fc-7bb1-11e7-8353-3dba66c239ab.png)

![screen shot 2017-08-07 at 8 40 46 pm](https://user-images.githubusercontent.com/7004949/29055430-5fe3e1a6-7bb1-11e7-89f0-313bec391bb6.png)

**Comment by jasonblais** [comment]
Thanks @santos22! Much appreciated, glad you're finding it interesting.

Good place to ask questions is actually in a channel called ["Contributors"](https://pre-release.mattermost.com/core/channels/tickets)

I realize that's not necessarily the most obvious, since we have a team called "Contributors" and a channel called "Contributors"..but if you find you way there, don't hesitate to pop up a question and someone in the community or the core committers can help you out.

PS: Most of us work in the North American timezone, so it might not be until a few hours from now when someone sees your question,

**Comment by jasonblais** [comment]
Thanks @santos22!

**Comment by santos22** [comment]
Hi @jasonblais,

I was checking out [pre-release](https://pre-release.mattermost.com/core/channels/town-square#) and noticed that **Edit Account Settings** doesn't show up on the profile popover. Is this expected behavior? I ran the app locally with the latest code and I do see **Edit Account Settings** on the profile popover.

<img width="1552" alt="screen shot 2018-02-10 at 7 55 41 pm" src="https://user-images.githubusercontent.com/7004949/36069346-addd4194-0e9c-11e8-85e0-b7aa1e037b38.png">

**Comment by jasonblais** [comment]
@santos22 We actually have a custom plugin uploaded on pre-release which overwrites the profile popover. This is for testing purposes.

On a standard Mattermost install, you should be able to see the "Edit Account Settings" option, just as you do locally :)
