### ISSUE TITLE
[Help Wanted] Change URLs of Direct Messages to usernames 

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7186]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. 

For technical advice or questions, please [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

---

**Difficulty**: Intermediate

**Details**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-91)

This PR (https://github.com/mattermost/platform/pull/6310) added support for URLs of direct message channels in the form 

```
https://servername.com/teamname/messages/@username
https://servername.com/teamname/messages/user_id
https://servername.com/teamname/messages/email
```

and for group message channels in the form

```
https://servername.com/teamname/messages/generated_id
```

**Proposed change:**

For direct message channels, propose all URLs to redirect to ```https://servername.com/teamname/messages/@username```. That is

 - `.../messages/user_id`
 - `.../messages/email`
 - `.../channels/userid1_userid2`

should all redirect to `.../messages/@username`.

Similarly, for group message channels, propose 

 - `.../channels/generated_id` redirecting to `.../messages/generated_id`

NOTE: Each of these URLs are already supported. This help wanted ticket simply changes the redirections to `.../messages/@username` or `.../messages/generated_id`

**Comment by wget** [comment]
:+1: this is really needed, because for now, if we want to search something in a direct message channel (a direct message with someone in particular), the GUI doesn't directly allow it.

We have to copy the ID from the URL e.g.: from `https://pre-release.mattermost.com/core/channels/5mqo3tzqntfh88pnazertyuiop__beqkgo4wzbn98kjz12345578`
we need to take `5mqo3tzqntfh88pnazertyuiop__beqkgo4wzbn98kjz12345578` and paste it in the search field as `in:5mqo3tzqntfh88pnazertyuiop__beqkgo4wzbn98kjz12345578 YOUR SEARCH HERE`. This is far from being intuitive. And I doubt much users know this trick (thanks to @jasonblais for letting me know it btw).

**Comment by CometKim** [comment]
I just started working on this.

**Comment by jasonblais** [comment]
Awesome, thanks @CometKim!

**Comment by CometKim** [comment]
@jasonblais Here is PR: https://github.com/mattermost/mattermost-webapp/pull/189
