### ISSUE TITLE
[Help Wanted] Do not send notification emails to addresses that have not been verified

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7260]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**:

When **System Console** > **Security** > **Require Email Verification** is set to `true`, do not send email notifications for `@-mention`, `@-all`, `@-channel` or `@-here` for email addresses that have not been verified. Print a log message for each unverified address where the email was not sent:

`[YYYY/MM/DD HH:MM:SS UTC] [EROR] Skipped sending notification email to test@test.com, address not verified. [details: user_id=nnnnnnnnnnnnnnnnnn]`

**Comment by moonmeister** [comment]
@esethna I can take this. I do have question. IF a server changes from being unverified to verified, what's the status of all current users? Are their emails set to verified already or not verified? If they aren't already considered verified what's the process for getting those emails verified?

**Comment by moonmeister** [comment]
@esethna I've tested the current master branch and this is already true. A couple scenarios:

**Scenario 1:**  If the server is "closed" and thus is invite only the email verification is automatic/impplicit. The user receiving the invite is never explicitly asked to verify. They are implicitly verifying by accepting the invite.

**Scenario 2:** If the server is "open" and thus anyone can create an account the verification is explicit. Upon account creation the user is required to verify email. There is no way past this. You have zero access till the email is verified. In fact the logs show an error saying the login failed because the email is not verified. With the account unable to login and not verified I tried mentioning it in all the ways above. Despite not even showing on the autocomplete list, you can still mention the user. But under no circumstances did if ever even execute the Send Notification function for this user. I could not get it to send a new unverified user an email.

**Scenario 3:** When a user changes their email it has to be verified, but they are still give access to the web app and they can still be mentioned at their new email address pre-verification. If they logout, then upon logon they meet the same wall given to new users on an open server and are required to verify before being given access. But like I said, they can still be mentioned. 

**Thoughts:** Seems this ticket is mostly done. There must be some code already checking something that is keeping the new user from receiving an email. 

**Questions:** Where is that code and what is checking? On email change can we reset that for the existing user so the existing code applies to them as well as new users?

**Comment by moonmeister** [comment]
My initial assumption is that it's cause the new user who has never verified their email and never used MM is not part of any team (confirmed in Admin console) but further testing showed that mentioning an active user in a channel they have not joined is still different then mentioning the new user who has never verified. 

<img width="745" alt="screen shot 2017-08-22 at 10 27 56 pm" src="https://user-images.githubusercontent.com/2730871/29600213-78e1a31c-8789-11e7-8d35-9a22f69c089d.png">

As you can see test1 I was told why a notification wasn't sent. For test3 there was no reason given.

**Comment by moonmeister** [comment]
Ah I just realized my mistake, teams and channels are different things. No team means no email it seems. Well then I guess that's not a viable option for existing users. I'll get back to the code.

**Comment by moonmeister** [comment]
This can be closed

**Comment by jasonblais** [comment]
Thanks @moonmeister!
