### ISSUE TITLE
Don't play Gif automatically; trigger animation when mouse is over instead

### ISSUE THREAD

**Issue by bbenoist** [mattermost/mattermost-server#7355]
#### Steps to reproduce
Include a Gif file with markdown in a conversation.

#### Expected behavior
Gif shows the first frame but doesn't plays.
A semi-transparent white `GIF` watermark and play icon are hovering the image to indicates users that its an animated picture.

#### Observed behavior (that appears unintentional) 
Gif is played in loop. Giving our users nausea when reading some text surrounding the image 🤢 

#### Possible fixes
See expected behavior.

**Comment by lindy65** [comment]
Hi @bbenoist,

### Please help us share your proposal in the feature proposal forum? 

Thank you for making an effort to contribute to the Mattermost open source project. Your time is valuable, and we highly appreciate your investment. 

Hundreds of engineers from around the world have contributed to this project through [community processes](https://about.mattermost.com/help/) that are openly documented. 

In the context of the [issue template](https://github.com/mattermost/platform/blob/master/ISSUE_TEMPLATE.md) presented when you created this issue, it seems this report is more a **feature proposal** (a change in the software's design) than a **bug report** (obviously unintentional behavior). 

Per the [issue template](https://github.com/mattermost/platform/blob/master/ISSUE_TEMPLATE.md), GitHub issues are used for [filing bug reports](https://www.mattermost.org/filing-issues/). 

We request your help to: 

- Consider closing this issue, because it does not meet the issue template requirements. 

You are welcome to continue discussion on this ticket after it is closed. 

We also welcome you to [open a feature proposal](https://www.mattermost.org/feature-ideas/) in the feature proposal forum where your idea can be discussed and upvoted by the community, 

Alternatively, if a similar proposal already exists, please consider upvoting and commenting?

Over [100 feature proposals](https://mattermost.uservoice.com/forums/306457-general/status/1588363) from the community have been added to the Mattermost open source project.

**Comment by bbenoist** [comment]
@lindy65 Since it provokes [motion sickness](https://en.wikipedia.org/wiki/Motion_sickness), I would consider it as a bug rather than a feature request.

I mean, this is an actual accessibility *issue*, not a minor visual change request.

A [feature request with the solution I proposed](https://mattermost.uservoice.com/forums/306457-general/suggestions/19057645-loop-gifs-on-mouseover) have already been submitted but doesn't have enough votes to be considered seriously...

Feel free to close this issue by yourself if you want to, but, given the nature of the problem I mentioned  ( ♿️ ), don't expect me to agree with your appreciation of it.

**Comment by lindy65** [comment]
Hi @bbenoist 

Thank you for your feedback,

I'll post your suggestion to the team and ask them for feedback.

**Comment by bbenoist** [comment]
Hi @lindy65 !

Thank you very much for having reconsidered the seriousness of this issue 👍 

FYI, we had to forbid usage of GIFs on a team of 250+ people because of this problem: every time a gif appeared, it provoked complaints from our teammates...

Let's hope that the Mattermost team will find a quick-win solution which would make everyone enjoy Gif again.

**Comment by esethna** [comment]
Hi @bbenoist, has your team considered using the `/collapse` command? If the GIFs become too heavy in a channel you can simply type `/collapse` which causes all GIFs and image previews to collapse by default. You can then use `/expand` to reverse the effect.

**Comment by prixone** [comment]
@esethna while I love the collapse / expand feature, it needs to filter formatting as using GIFs with:

```
![test](http://i.imgur.com/A3pSzxm.gif)
```

Will bypass the collapse/expand altogether.

**Comment by esethna** [comment]
Thanks @bbenoist @prixone, I have [posted in the UX Design](https://pre-release.mattermost.com/core/pl/1gmip19ko3nfmrqo17e8war9fa) channel to discuss this. I think this would be a nice improvement.

**Comment by bbenoist** [comment]
Cool! Thank you guys /°

**Comment by lindy65** [comment]
Thanks @bbenoist, we can track the discussion in the UX Design channel linked above.  I'll close this issue off here for now.

**Comment by fionnb** [comment]
Well, apparently that solution did not quite work out as expected ...

**Comment by fionnb** [comment]
Well, apparently that solution did not quite work out as expected ...
