### ISSUE TITLE
After opening a mattermost client which loads existing unread messages, the timestamps are inaccurate

### ISSUE THREAD

**Issue by gtcode** [mattermost/mattermost-server#7406]
If I am not using a client and log in to view new messages that were created by another user in my absence, the timestamp for their message does *not* reflect when they sent the message, but when I finally opened and viewed the message.  The default behavior should be to show the time for when the user sent the message.

**Comment by lindy65** [comment]
Hi @gtcode 

Thank you for your feedback,

Could you share which server version you are using and whether you're on the Desktop App or browser?  If browser, which one?

We had a bug with timestamps that was fixed in a previous release so perhaps upgrading to the [latest version](https://about.mattermost.com/download/) will fix the issue for you.

**Comment by gtcode** [comment]
Hello @lindy65,

Sorry for the hasty bug report.  

Upgrading worked!  My mistake, it's a non-issue.

**Comment by lindy65** [comment]
No worries @gtcode,

Pleased your issue is resolved!
