### ISSUE TITLE
Don't linkify any `foo:bar` strings

### ISSUE THREAD

**Issue by ThiefMaster** [mattermost/mattermost-server#7657]
#### Summary
Any `foo:bar` string is linkified

#### Steps to reproduce
Write `foo:bar` in a message

#### Expected behavior
Only common protocols (http, https, possibly other well-known ones such as ftp, ed2k, etc. too) should be linkified.

#### Observed behavior (that appears unintentional) 
`foo:bar` is converted to a link.

#### Possible fixes
Use a protocol whitelist - ideally configurable by the admin - to determine what can be linkified.

**Comment by lindy65** [comment]
Hi @ThiefMaster,

Thanks for your feedback,

Our devs mentioned that this is intentional as some links don't need the slashes like mailto:test@example.com or tel:5551234557.

Is there a specific use case you're needing?

**Comment by ThiefMaster** [comment]
My usecase is simply to not get linkification for *random strings*. For example, I noticed it when I copied a status message containing `status:failed` which is clearly nothing that should be linkified.

Using a whitelist would avoid such cases while still linkifying anything that makes sense (useful defaults with common protocols like http, https, ftp, tel, mailto - and whatever the admin  wants to add).

**Comment by hmhealey** [comment]
I think it's fine to be permissive as we are right now since it allows for organizations using whatever software they want. I know at least one customer is using some internal software that uses a custom protocol, so I agree that a whitelist would be the right way to go with this.

Would you mind filing a suggestion on [our Feature Ideas forum](https://mattermost.uservoice.com/forums/306457-general) so we can gather any other community input and prioritize accordingly?

**Comment by ThiefMaster** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/32004130-add-a-whitelist-which-protocols-should-be-linkifie

**Comment by hmhealey** [comment]
Awesome, thanks

**Comment by lindy65** [comment]
Thanks @ThiefMaster and @hmhealey 

I'll close this issue off for now and we can track via the feature suggestion linked above.
