### ISSUE TITLE
[Help Wanted] Migrate removed_from_channel_modal.jsx to be pure and use Redux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/mattermost-server#7676]
If you're interested please comment here and come [join our "Redux" community channel](https://pre-release.mattermost.com/core/channels/redux) on our daily build server, where you can discuss questions with community members and the Mattermost core team.

New contributors please see our [Redux contribution process](https://docs.mattermost.com/developer/webapp-to-redux.html#component-migration-steps) to help get you started.

----

**Difficulty**: Intermediate

**Details**: [Mattermost is moving their webapp to Redux over the next months](https://forum.mattermost.org/t/migrating-mattermost-webapp-to-redux/3281) and we're looking for contributors to help with that effort. This Help Wanted issue is to move [`components/removed_from_channel_modal.jsx`](https://github.com/mattermost/mattermost-webapp/blob/master/components/removed_from_channel_modal.jsx) to Redux. 

Before submitting the pull request, make sure it has proper component testing [as described here](https://grundleborg.github.io/posts/react-component-testing-in-mattermost/). 

For a sample pull request for migrating a component to use Redux, see https://github.com/mattermost/platform/pull/6416

**Comment by KishoreFartiyal** [comment]
I will work on this issue.

**Comment by avasconcelos114** [comment]
I'd like to take on this one (tbh I already started), got a couple of questions to make sure I get things right:
1. This component doesn't seem to be using the modal from `react-bootstrap`, is this intentional? would you like me to also change the components to use `react-bootstrap` instead?
2. This component is using `BrowserStore` to receive a `channel-removed-state` event with information regarding the `remover` and `channelName`. I noticed that this is the only component that is still using the `BrowserStore`, is there a need for me to remove this method and add a different implementation instead? (alterations to the [websocket actions](https://github.com/mattermost/mattermost-webapp/blob/616e94ade4588e1d3ce8cdadf977d14beeab91e6/actions/websocket_actions.jsx#L569) will have to be made. 

I personally think that changes in #2 might be better off in a separate PR as these changes aren't directly related to migrating this component to Redux, however I'd be happy to help out should you decide that this is better :)

**Comment by jasonblais** [comment]
Thanks! @jwilander Would you be able to help with the questions above?

**Comment by jwilander** [comment]
1. Yes, if you could change that to match the other modals to use `react-bootstrap` that would be great 👍 
2. I'd say if it's easy to re-implement using a more Redux-like pattern then it's fine in the same PR but if it starts to look more complex, then yeah it would probably be better in a separate PR

**Comment by avasconcelos114** [comment]
Ah got it, but sadly as it turns out, it seems like there was a reason behind leaving the modal as pure `div`s with bootstrap classes on them, as having the modal pre-rendered (but hidden), made it possible to trigger an action to display it from `websocket_actions.jsx` using jquery. 

Using normal bootstrap components seem to require a change in how the `USER_REMOVED` websocket event is processed (using Redux to trigger actions and communicate with the component instead of relying on jquery for it).

Totally a possible thing but it will require changes to `mattermost-redux` to accommodate the new actions and additions to the store. Wondering if all these changes are still valid in this PR, or if I should just migrate this component/add unit tests, and then make other PRs to address modal and BrowserStore usage

**Comment by jwilander** [comment]
Actually @avasconcelos114 you should be able to do that without any changes to mattermost-redux. Many of our modals are triggered using webap-specific actions, e.g.:

https://github.com/mattermost/mattermost-webapp/blob/master/components/channel_header/channel_header.jsx#L322

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-webapp/pull/1839
