### ISSUE TITLE
Search in direct messages

### ISSUE THREAD

**Issue by jackm** [mattermost/mattermost-server#7762]
Is there not a way to perform a search that only searches in a specific direct message channel?

Using the `in:` search modifier only seems to work for public and private channels, but not direct messages. I would like to be able to do a search for a keyword but have it only look at one direct message channel.

Using the `from:` modifier is close, but that only looks at one user's messages and not both users in the direct message channel; I'd like to be able to search for both users.

My reported Mattermost version is `Version: 4.3.0  (4.3.1)` according to the About Mattermost window.

**Comment by jasonblais** [comment]
@jackm Not easily because the URL for direct messages is in the form `../channels/userid1_userid2`. 

However, once https://github.com/mattermost/mattermost-webapp/pull/189 is reviewed and merged, the URL will be displayed with `.../messages/username`, which will allow us to more easily support searching in direct messages via `in:username`.

**Comment by jackm** [comment]
Good to know. I'll subscribe to that PR.

**Comment by lindy65** [comment]
Thanks @jackm @jasonblais 

I'll close this off for now and we can track via the PR.
