### ISSUE TITLE
[Help Wanted] [PLT-8087] Optimize file attachment memory usage where possible

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7801]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-8087)

Customer use case: The default max file size upload is 50MB. However, people in a large prospect often collaborate on much larger files (could be up to 1GB).

In our hardware requirements doc, we cite attachment size as a large factory for memory requirements. In many cases, we can optimize our attachment handling by streaming the attachment to S3 or disk without holding the entire file in memory.

Further conversation in pre-release: https://pre-release.mattermost.com/core/pl/huod3abtmpgoxyp4uatmkyrhyc

**Comment by lieut-data** [comment]
Hey @levb -- looping @crspeller into the conversation given the plugin connection. I'm less concerned by the loss of image processing for larger files, but one of the "real-world" cases for plugins intercepting file uploads is to perform virus scanning.

For files larger than the limit, might we stream directly to the file store and then circle back and process them through the plugin API but wiring up the backing storage instead?

**Comment by crspeller** [comment]
That's probably not acceptable for some plugin use cases around compliance. We wouldn't want to write the file to the backing store if the plugin was going to reject it. 

Any solution here should include the ability for plugins to process files.

**Comment by lieut-data** [comment]
@crspeller, don't most of the compliance cases fall over once the bits are transferred through the network to the server anyway? If we're not allowed to write to the backing store, we're going to be permanently memory gated for all file uploads. Is there a compromise where we allow the larger file uploads unless a plugin has registered one of the hooks in question?

**Comment by crspeller** [comment]
It depends on how people want to nitpick. But there have been some cases where in memory is OK but writing it to a backing store is not.

We could have it switched on if a plugin has registered those hooks.

> If we're not allowed to write to the backing store, we're going to be permanently memory gated for all file uploads.

Why?

**Comment by lieut-data** [comment]
If I'm understanding it correctly, the crux of this (and related) tickets is to enable larger file uploads. The primary reason we don't support larger uploads today is because we effectively copy them around in memory a few times and risk running out of memory. There's probably some performance gains to be had too, but I don't think the product is gated by file uploads at present, so I'm assuming the focus is on reducing memory usage.

If we're forbidden to write to the backing store for some reason, I don't see an alternative to fitting the file in memory at least once. Am I misunderstanding?

**Comment by levb** [comment]
@lieut-data @crspeller Thanks for the comments. The requirement to run plugins on all files regardless of the size makes sense and is understood. I do not believe this to be easily accomplishable, without a material change to the plugin implementation and maybe even the API. Going there seems like opening another can of worms, so I'd like to see what improvements I can make without such changes.

The gist of the problem with plugins is here, https://github.com/mattermost/mattermost-server/blob/master/app/file.go#L447. Each plugin has a stream interface, but the current implementation executes the plugins sequentially, and waits to capture each one's output before starting the next. It assumes the data pre-buffered, and re-buffers any changes to it.

If we were allowed temp files, we could buffer (tee-write) every unique version of the bits, once. We could then do some trickery like starting each plugin in a goroutine, capturing its output, and waiting for it to either (a) return or (b) start writing to its output. In case of (a) we invoke the next plugin with the original data, in the case of (b) (tee-)pipe the output to the next plugin; repeat.

If we were to have a conversation about the file plugins interface improvements, I'd argue for passing around file names/URLs rather than streams; in the distributed (out-of-process) plugin architecture that seems to make more sense. Also, I would advocate that the plugins chain with each other directly, avoiding re-uploading every change to the central server.

**Comment by levb** [comment]
@lieut-data @crspeller @coreyhulen I filed the above PR as a sort of progress report. See the notes there for what's accomplished and what's still to be done. I have _not_ yet implemented large upload passthrough via temp files, and in general haven't really done much with plugins yet. I have accomplished a material memory footprint reduction while processing uploads.

Please note that the PR is in my own fork, and is a squashed WIP draft bundle. I intend to file a more structured PR to mattermost separately, as a set of more meaningful commits.

**Comment by jasonblais** [comment]
Thank you @levb! It is a Canadian holiday on Monday (for crspeller and lieut-data) - just wanted to mention in case you don't hear back until Tuesday :)

**Comment by levb** [comment]
@lieut-data @crspeller ping. I haven't had a lot of time to work on it this week, have been adding tests and almost done fixing up several issues I mentioned and found since, including making the API backward compatible wrt `channel_id`. Was planning to commit all that to my branch and work on benchmarking streaming vs files for plugins, and maybe switching to temp files as discussed over the weekend. I'd much appreciate at least a cursory look to see if I am on a good path from your POV.

**Comment by hanzei** [comment]
@levb Can this be closed as https://github.com/mattermost/mattermost-server/pull/9835 got merged?

**Comment by levb** [comment]
Yes I was just filing related tickets last night.
- Updated https://mattermost.atlassian.net/browse/MM-10188 to be the ticket for XL file upload, as there's still an issue with plugins to work out.
- Logged https://mattermost.atlassian.net/browse/MM-13519 to improve the handling of excessive http payloads

**Comment by hanzei** [comment]
mattermost.atlassian.net/browse/MM-13519 isn't public. Is this intended?

**Comment by levb** [comment]
@hanzei let's discuss in the JIRA ticket, more appropriate there?
