### ISSUE TITLE
OAuth state parameter invalid if its length >  128

### ISSUE THREAD

**Issue by polskikh** [mattermost/mattermost-server#7808]
Hi there! 

Why is valid **state** parameter length less or equal 128 symbols ([this code](https://github.com/mattermost/mattermost-server/blob/master/model/authorize.go#L65))? I can't find **state** parameter limitation by a length in RFC.

We use mattermost as OAuth authorization server for Concourse CI. Concourse CI can send a request with **state** parameter length greater 128 symbols. Because of this, we have problems with authorization.

Could you increase the valid length of **state** parameter in the nearest release?

**Comment by jwilander** [comment]
It's currently limited to that because that's what the database has as the max column size for the state. It is completely arbitrary and I can understand it causing issues with other services so I've created a ticket here to increase the limit https://mattermost.atlassian.net/browse/PLT-8114

**Comment by lindy65** [comment]
I'll close this issue off here for now and we can track via the Jira ticket linked above.

**Comment by polskikh** [comment]
Hey @jwilander!
 
Do you have any information about my issue? Why did it not get into 4.6 version?

We really suffer from this limitation...

**Comment by ccbrown** [comment]
@polskikh Thanks for poking us on this one. :) We'll get the fix into 4.7: https://github.com/mattermost/mattermost-server/pull/8218

**Comment by mikroskeem** [comment]
I think this issue is still not fixed, because AuthorizeRequest has still [128 char limit](https://github.com/mattermost/mattermost-server/blob/570c52b4cc88d7d0864511b9a4cb6318a07a6dbb/model/authorize.go#L93) (checked in [/oauth/authorize](https://github.com/mattermost/mattermost-server/blob/d81a61398d01d839e70e2345da787e7ef89c0832/api4/oauth.go#L320)).

I tried to set up Wekan OAuth2 login, Wekan puts base64 encoded json into state and it's usually larger than 128 characters.
