### ISSUE TITLE
[Help Wanted] [PLT-7536] Post a system message when a team is changed from public private.

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#7877]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/PLT-7536)

There is a CLI command to modify channels from public to private and vice-versa. This ticket is to post a System message to the affected channel:

Private > Public:
"This channel has been converted to a Public Channel and can be joined by any team member."

Public > Private:
"This channel has been converted to a Private Channel."

**Comment by gig177** [comment]
Should [command](https://docs.mattermost.com/administration/command-line-tools.html#platform-channel-modify) options be extended to receive `--username` value? The `UserId` [is required](/mattermost/mattermost-server/blob/v4.4.2/model/post.go#L137) for post message.

**Comment by gig177** [comment]
I'm working on it.

**Comment by jasonblais** [comment]
@gig177 Big thanks for your interest! 

Sorry I missed your original question. The command shouldn't expect a username value, given it converts a channel.

I think a system message gets posted when using the `platform channel add` and `platform channel create` commands, so maybe you can compare against them.

**Comment by gig177** [comment]
>I think a system message gets posted when using the platform channel add and platform channel create commands, so maybe you can compare against them.

The command `$ platform channel create` just create channel without any user [membership](https://github.com/mattermost/mattermost-server/blob/5358b9c42cc99f72e7844062f28b2ddc3642a339/cmd/platform/channel.go#L169).

The command `$ platform channel add {channel} {users}` gets username from `{users}` arguments. Example from the doc: `$ platform channel add myteam:mychannel username1`. The `username1` further will be grabbed by `getUsersFromUserArgs(a *app.App, userArgs []string)` function. In the end the `system post message` will not be created at all. The call chain may looks like: `getUsersFromUserArgs() -> AddUserToChannel()`. But [AddUserToChannel()](https://github.com/mattermost/mattermost-server/blob/375c0632fab03e3fb54865e320585888499c076d/app/channel.go#L555) does not create `system post message` because the function body has no appropriate `postJoinChannelMessage(user, channel)` call.

The command `$ platform channel modify myteam:mychannel --private` has no `username` option/argument either. But the`UserId` is required for the `system post message` as I described above.

So, my question is: Where can I get `username` value from?

**Comment by jasonblais** [comment]
Hey @gig177 - this has been queued for Wednesday's developers meeting to discuss: https://pre-release.mattermost.com/core/pl/93bwqew3n7yr3m73yqfs9hysgc

**Comment by jasonblais** [comment]
Thanks @gig177!
