### ISSUE TITLE
Mentioning @toString breaks channel

### ISSUE THREAD

**Issue by TobiX** [mattermost/mattermost-server#7944]
#### Summary
Typing a mention of `@toString` breaks the current channel (Mattermost 4.3.2)

#### Steps to reproduce
1. Type `@toString` into the private chat with somebody
2. Be really sad you cannot communicate with them anymore

#### Expected behavior
Mentioning JavaScript method names should not break a channel

#### Observed behavior (that appears unintentional) 
The console throws many JS errors of this kind:
`Uncaught TypeError: Cannot read property 'length' of undefined`

#### Possible fixes
Well, replacing the `@toString` with something else in the database fixed the issue for me...

**Comment by TobiX** [comment]
Updated after another test.

**Comment by lindy65** [comment]
Hi @TobiX,

Thanks for your feedback, 

A fix for this issue has been submitted and will be available in the next version on December, 15th.

**Comment by hmhealey** [comment]
Hey @TobiX,

Since this can be used to take down a channel for other users as well, we're treating this as a security issue, and we're going to be backporting it to earlier releases. I've edited your post as best as possible to remove the repro steps while we fix this.

Also, another workaround for any users that find this would be to go into User Settings > Advanced, disable post formatting, and then switch to the channel and edit/delete the offending post.
