### ISSUE TITLE
Error while developer machine setup

### ISSUE THREAD

**Issue by danedavid** [mattermost/mattermost-server#7967]
I'm doing developer set up on my Ubuntu 16.04 according to https://docs.mattermost.com/developer/dev-setup-ubuntu-1604.html

Then, when I run `make` I get the following error:

![image](https://user-images.githubusercontent.com/19928280/33868239-d227742e-df27-11e7-8593-355714991c6b.png)

**Comment by grundleborg** [comment]
@danedavid the Mattermost Makefile spins up docker containers for all of Mattermost's dependencies, including PostgreSQL, to conveniently provide a fully functional development environment. The issue here is that you already have PostgreSQL running on your computer, so the port it requires - 5432 - is already in use. You will need to shut down PostgreSQL on your computer before working on Mattermost (`sudo systemctl stop postgres` should do it), or alternatively alter the Makefile to not start up a PostgreSQL docker container.

**Comment by danedavid** [comment]
@grundleborg Thanks for reaching out! When I run `sudo systemctl stop postgres` I get the following output:  
`Failed to stop postgres.service: Unit postgres.service not loaded.`

What should I do ?

**Comment by lindy65** [comment]
Hi @danedavid,

Did `grundleborg's` post help resolve your issue?

**Comment by danedavid** [comment]
@grundleborg thanks! though the service was `postgresql` and not `postgres`. I set up the server, and to view the application, do you have to signup, or is there any default login ?

**Comment by grundleborg** [comment]
When you first go to the application in a web browser, you get a sign up page. Create an account there and it will be the system admin account.

**Comment by danedavid** [comment]
@grundleborg Thanks a lot! I'm closing this issue!
