### ISSUE TITLE
embed <iframe> in Messages <-- possible in any way? 

### ISSUE THREAD

**Issue by petrich** [mattermost/mattermost-server#7972]
Dear All

we are using Mattermost in a 100% trusted Environment... (small team, only-technical members) 

and we need to send messages with `<iframe>` support . 
(like `<img>` which mattermost allready supports via markups)

In other words: We want embed `<iframe>`'s in our messages.  

Is there any way to configure (or by plugin)  Mattermost to allow this?

Thank you for any tips/help.
Greetings

**Comment by hmhealey** [comment]
Hi @petrich,

The only way to do that would be to use a [post type plugin](https://developers.mattermost.com/extend/plugins/webapp/reference/#posttypeplugin) to override the entire contents of a given post to add an iframe. That would however require you to make some sort of integration that would make posts of that type since you can't do that from the app on its own.

If that's what you're wanting to do, you can take a look at [the source for our Zoom plugin](https://github.com/mattermost/mattermost-plugin-zoom) to see how the server-side code creates a post and how the client-side code overrides it's rendering. I can also give you some more pointers for where to look if that would help

**Comment by petrich** [comment]
Thank you for your help.
I will try it via the "post type plugin" as you suggested.

Thank you again
Greetings

**Comment by lindy65** [comment]
Thanks @petrich,

I'll close this issue off here for now but feel free to come back if it doesn't work as expected for you!
