### ISSUE TITLE
[Feature Request] close the websocket connection when revoke the user access token

### ISSUE THREAD

**Issue by zj8487** [mattermost/mattermost-server#7981]
Hi all, 

I noticed that when I revoke the access token of a user. and the websocket connection of this access token is not closed or disconnected.

is it posssible to close the websocket connection when revoke the access token or session?

mattermost server version: 4.2

thanks a lot

**Comment by lindy65** [comment]
Hi @zj8487,

Thanks for your feedback,

There have been a number of improvements and updates since Mattermost 4.2 so perhaps [updating to the latest version](https://about.mattermost.com/download/) will fix the issue for you.

If not, could we have your help adding a feature request to our [forum](https://mattermost.uservoice.com/forums/306457-general) where it can be upvoted by you, and others, up to 10 times.

Thanks!

**Comment by zj8487** [comment]
@lindy65 thanks a lot!

 i tested it on 4.5.0 version, and it appears to be same question.
also i have create [vote](https://mattermost.uservoice.com/forums/306457-general/suggestions/32668549--feature-request-close-the-websocket-connection-w) here

**Comment by lindy65** [comment]
Perfect, thanks @zj8487 :)

I'll close this issue off here and we can track via the forum post linked above...
