### ISSUE TITLE
Default mention triggers not appearing in mention sidebar

### ISSUE THREAD

**Issue by alasalle42** [mattermost/mattermost-server#8012]
#### Summary
Default mention triggers - @channel, @all, @here - do not bring up a mention in the sidebar. 

#### Steps to reproduce
Version: 4.4.0  (4.4.2)
Build Hash: ba9237628e0e4d02f20ec87449ec003ba7287fb2
Build Date: Wed Nov 22 22:43:49 UTC 2017
Accesses in Chrome, macOS 10.12.6 Sierra

> Create channel
> Tag self or other user with @channel, @here, or @all 
> Check recent mentions sidebar
> Despair

#### Expected behavior
All mentions in the list of triggers should appear in sidebar.

#### Observed behavior (that appears unintentional) 
It didn't do anything, even though it was expected to do something.

**Comment by lindy65** [comment]
Hi @alasalle42,

Thanks for your feedback,

I'll check with one of our product managers because I'm actually not sure why `@channel` and `@all` are not shown in the search results in the right-hand-side if you click on the recent mentions `@` icon. I can see why people would want to search for these because, for example, you could have email and/or push notifications turned off so you would not receive notifications at all unless you searched for them by clicking the `@` icon.

I think it would be very difficult to show `@here` in the search results because, if selected, this would trigger mentions only if you are online.

This being said, I believe because `@all` and `@channel` are in the same group as `@here` in the Hamburger Menu > Account Settings > Words that trigger mentions setting selection, the behavior for all three is the same (i.e. they are not returned in `@` search results in the right-hand-side).

**Comment by lindy65** [comment]
Hi @alasalle42,

If you'd like to follow, we have a conversation open in the [UX Design channel](https://pre-release.mattermost.com/core/pl/75qyj8f77tgrzr5wyynpj4m8no) on our nightly build server.

**Comment by alasalle42** [comment]
Thanks, @lindy65!

**Comment by lindy65** [comment]
We've created [this ticket](https://mattermost.atlassian.net/browse/UX-89) to improve the behavior / design of mention triggers so I'll close this issue off for now and we can track via the ticket.
