### ISSUE TITLE
Grammarly icon overlaps the Smiley button 

### ISSUE THREAD

**Issue by alapanme** [mattermost/mattermost-server#8057]
#### Summary
Grammarly icon overlaps the Smiley button in default mode.

#### Steps to reproduce
1. Launch the Website.
2. Go to any channel.
3. Observe the Smiley button, next to the textbox post text box.

#### Expected behavior
Both Smiley icon and Grammarly icon should be distinctly visible.

#### Observed behavior (that appears unintentional) 
Grammarly icon is overlapping the Smiley icon.

![smiley_grammarly](https://user-images.githubusercontent.com/25705483/34650119-70705178-f3e1-11e7-8d5b-453e86fbbbda.PNG)

**Comment by lindy65** [comment]
Hi @alapanme,

Thanks for your feedback,

Grammarly is an add-on, correct?  I'm not sure about the expected here so have asked one of the product managers to give feedback.

**Comment by alapanme** [comment]
Hi @lindy65,

Yes, Grammarly is an add-on. Saw this behavior for both Chrome and Firefox.

**Comment by lfbrock** [comment]
Hi @alapanme, 

Can you clarify more on the expected behaviour? Would you expect the text box to have a different design if the Grammarly add-on is there? 

I'm not sure if this is something we would support ourselves since it's a special use case, but you might be able to look into making the change yourself by modifying the webapp (instructions [here](https://docs.mattermost.com/deployment/customize-mattermost.html#mattermost-webapp)).

**Comment by lindy65** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid.  If you still experience the same problem, try upgrading to the latest version.  If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
