### ISSUE TITLE
Slack Import Missing Emails

### ISSUE THREAD

**Issue by ronaldreagan4prez** [mattermost/mattermost-server#8081]
Slack exports don't include email addresses anymore, but you are able to export a full list of users including emails via the manage members page.  Can we include this CSV as a way to import users?

**Comment by lindy65** [comment]
Hi @ronaldreagan4prez,

Thanks for your feedback,

Can we have your help adding your request to our [feature suggestions forum](https://mattermost.uservoice.com/forums/306457-general) where it can be upvoted by you and others to increase it's popularity?

Please link the request back to this issue for continuity?  Thanks!

**Comment by WGH-** [comment]
Since the code that tries to extract e-mail from JSON is [still here](https://github.com/mattermost/mattermost-server/blob/c5e8cb25caa39ed018ede5270e1566e8f7448396/app/slackimport.go#L158), it might make sense to hack the support into grundleborg/slack-advanced-exporter (which official Mattermost documentation already refers to as a tool that helps export attached files) for the time being. I'll try to work on that next week grundleborg/slack-advanced-exporter#4
