### ISSUE TITLE
Picture Thumbnails Are Not Resizable

### ISSUE THREAD

**Issue by kylegoch** [mattermost/mattermost-server#8087]
We started experimenting with a montioring service that sends graphs to MatterMost. However the images are crazy small by default. And have a huge white box with info next to them thats the same size as the image.

I would rather just see a large preview of the picutre a la Slack with the option to make it bigger by clicking on it. Right now, any image sent to MatterMost requires you actually click the image to see it rather than seeing a decent size preview.

We would love to be able to resize image thumbnails/previews on our own (and remove the info box) but it appears those options were removed.

According to this PR the options to handle images were removed: https://github.com/mattermost/mattermost-server/pull/6688

Any chance we could get those back? Would love to be able to control our image previews to be actually readable/viewable inline.

**Comment by lfbrock** [comment]
Hi @kylegoch - the old config settings were just removed because they didn't actually change the size of the thumbnail, they just changed how much of the image was rendered within the thumbnail so it was a little strange. 

We have an in progress pull request here to improve the file thumbnails - feel free to log into the test server to try it out, open to any feedback you have on the new design and size:

https://github.com/mattermost/mattermost-webapp/pull/357#issuecomment-355066132

**Comment by kylegoch** [comment]
Awesome thanks @lfbrock ! took the test server for a spin and left some feedback.

Will close this issue.
