### ISSUE TITLE
gifv files do not display

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8302]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9584)

Repro:
Post "![](http://somewebsite.gifv)"  in a channel

Observed:
Nothing is displayed

Expected:
Picture is displayed in webapp and mobile app

**Comment by jasonblais** [comment]
Awesome, thanks @jkurian! I'd start with the developer's guide linked in the issue description above.

If you have any questions, please let us know! We're more than happy to help

**Comment by jkurian** [comment]
Hey @jasonblais, I have made some progress in resolving this issue and want some advice if I am going in the right direction. Its no where near complete but the general route I plan on taking to solve the .gifv files not displaying should be understandable by looking at the changes I have made. Could you let me know if I am headed in the right direction or I need to change the way I am thinking about this problem completely. Thanks! 

https://github.com/jkurian/mattermost-webapp

**Comment by jasonblais** [comment]
Great! @jkurian Are the changes in the `master` branch of your fork?

**Comment by jkurian** [comment]
@jasonblais They are on a branch - PLT-8302! The commit I made can be found on the link attached below.

https://github.com/jkurian/mattermost-webapp/commit/f3e086597e5fe4931274b9358829fef4f16e4ca7

**Comment by jasonblais** [comment]
@jkurian Thanks! I'll ping one of our engineers to help with an initial review.

**Comment by lieut-data** [comment]
Hi @jkurian! I'm just now coming up to speed on .gifv files to help give you some direction. I started with [Imgur's announcement about this format](https://blog.imgur.com//2014/10/09/introducing-gifv/), as well as [this article](http://fileformats.archiveteam.org/wiki/GIFV) describing their format.

On the surface, it looks like you're on the right track: detect the .gifv extension, rewrite using the .mp4 extension, and embed as a video instead. Interestingly, Imgur seems to detect loading inside a <video> component vs. loading the URL in a browser tab, since http://i.imgur.com/zvATqgs.mp4, for example, redirects back to the `.gifv` extension and renders a lightweight HTML page with the embedded <video> element pointing back to the `.mp4`. That generated page is good reference to use for the properties to ensure the video loops as expected.

It looks like Instagram supports a `.webm` version as well, which might be a more efficient option if you're running in a supported browser. Also we do have an existing `AudioVideoPreview` component that you may also want to investigate.

Do you know if .gifv is in use outside Imgur? Does everyone support the .mp4 rename approach as such?

**Comment by lieut-data** [comment]
Looks like .gifv are in use on sites like gfycat.com, e.g. http://gfycat.com/AcceptableWebbedBedbug, where the `.mp4` is extended to the bare link vs. replacing an existing `.gifv` extension. Supporting that might be trickier, but also might not be "expected" since it's not obvious that you're embedding anything.

**Comment by jkurian** [comment]
@lieut-data @jasonblais Thanks (to both of you)! That is a great help. I will reach out if I have any more questions :)

**Comment by KuSh** [comment]
Is that still relevant ? Imgur seems to use mp4 nowadays

**Comment by esethna** [comment]
@KuSh thanks this is no longer valid
