### ISSUE TITLE
Stop using the search.results reducer in mattermost-redux for flagged and pinned posts

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8464]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-9793)

Right now when the webapp requests flagged or pinned posts from the server, it stores the returned post IDs in the `entities.search.results` reducer which is also used for search results from posts.

What we should do instead is create two new reducers, either in `reducer/entities/search.js` or `reducer/entities/posts.js`. One called `flagged`  for flagged post IDs and the other called `pinned` for pinned post IDs. Flagged posts are team-wide so just an array is fine for `flagged` but `pinned` is channel-specific so it might be worth turning that into an object mapping channel IDs to arrays of post IDs.

Note that some of the actions to get flagged or pinned posts exist in mattermost-webapp when they really should be in mattermost-redux. We should move these over as part of this ticket as well and create new actions as necessary.

Some links to code referenced above:
- https://github.com/mattermost/mattermost-redux/blob/master/src/reducers/entities/search.js#L7
- https://github.com/mattermost/mattermost-webapp/blob/master/actions/views/rhs.js#L127

**Comment by hanzei** [comment]
Nice, thanks @harenlewis! Let us know if you have any question.

**Comment by harenlewis** [comment]
Great @hanzei, will definitely need some help, especially in machine setup since I'm a new contributor.
Okay, to start off I have a few doubts and just to check if I have figured things out correctly:

1) Fork the main repo mattermost-server
2) I need to fork the mattermost-redux repo for working on reducers,
3) For working on actions I need to fork the  mattermost-webapp repo

Is this correct?

**Comment by harenlewis** [comment]
Thanks, @hanzei, definitely will need some help, especially in machine setup, since I'm a new contributor. Will let you'll know if I face any hurdle.

**Comment by hanzei** [comment]
Sure. Feel free to DM me on the [Mattermost Community Server](https://community.mattermost.com) or ask your question in the `Developers` channel.

**Comment by hanzei** [comment]
Making this one available for the public again due to inactivity.

**Comment by valentijnnieman** [comment]
I'd like to take a look at this!

**Comment by jasonblais** [comment]
Thanks @valentijnnieman! 🚀

**Comment by valentijnnieman** [comment]
Is this issue still relevant? I'm looking through the code and find there are already reducers in place for `flagged` and `pinned`, see [here](https://github.com/mattermost/mattermost-redux/blob/3bb89a5450b94da564d3a286fefb5945a1c3fca8/src/reducers/entities/search.js#L60). I also found a test that confirms it works [here](https://github.com/mattermost/mattermost-redux/blob/3bb89a5450b94da564d3a286fefb5945a1c3fca8/src/reducers/entities/search.test.js#L270). One thing I find strange is that there's no `flagged` or `pinned` members in the `SearchState` object [here](https://github.com/mattermost/mattermost-redux/blob/3bb89a5450b94da564d3a286fefb5945a1c3fca8/src/types/search.js#L10) but I suppose that wouldn't necessarily cause issues since it's just Flow types (although I can't be sure, I've little experience using Flow). I'm trying to investigate this further - I'm also having a little bit of trouble trying to get the `redux-dev-tools` up and running, so I can take a look at the state object. Thought I'd check first if this issue is still relevant and not out of date, since it's been a while! Thanks :-)

**Comment by jasonblais** [comment]
Good question.

@jwilander wondering if you'd know whether this ticket still applies? (pinging you as the original ticket creator, feel free to nudge someone else)

**Comment by hanzei** [comment]
@jwilander Gentle reminder about this topic

**Comment by jasonblais** [comment]
Added a comment in the Jira ticket and asked Platform team to either clarify for the ticket or close if it's no longer relevant. Closing this for now.
