### ISSUE TITLE
[Help Wanted] [MM-8860] Bulk loading: Support every 15 minutes and every 1 hour intervals for email notification preferences

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8498]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-8860)

Mattermost supports a bulk import tool feature for migrating data from an existing messaging system, or for pre-populating a new installation with data. https://docs.mattermost.com/deployment/bulk-loading.html

The import tool lets one specify a user's notification preferences, including email: https://docs.mattermost.com/deployment/bulk-loading.html#fields-of-the-usernotifyprops-object

Currently, the import tool only supports the "Immediately" and "Never" email notification preference options. However, when [email batching is enabled](https://docs.mattermost.com/administration/config-settings.html#enable-email-batching), Mattermost also supports sending email notifications every 15 minutes and every 1 hour intervals.

Proposed change: Allow the bulk import tool to support the following options:
 - When email batching isn't enabled: Immediately; Never
 - When email batching is enabled: Immediately; Every 15 minutes; Every 1 hour; Never

Speak to @jason on [pre-release](https://pre-release.mattermost.com) (@jasonblais on GitHub) for help if needed.

**Comment by santos22** [comment]
Hey @jasonblais! Does this also involve changes to the following UI?
<img width="1552" alt="screen shot 2018-03-24 at 10 38 11 pm" src="https://user-images.githubusercontent.com/7004949/37872081-5cd2f832-2fb4-11e8-9baa-852ede9c4c7c.png">

**Comment by jasonblais** [comment]
Hey @santos22! No changes needed on the UI - there are two different settings based on what `EnableEmailBatching` is set to in config.json:

1) `EnableEmailBatching` = false:

![image](https://user-images.githubusercontent.com/13119842/37903761-1094cd92-30c7-11e8-8bd5-2115e2b59ab2.png)

2) `EnableEmailBatching` = true

![image](https://user-images.githubusercontent.com/13119842/37903779-2d9350da-30c7-11e8-8465-e07e42894511.png)

**Comment by jasonblais** [comment]
Thanks @santos22 for looking into it!

One worry with changing existing values is that if someone is already using the script to pre-populate new users with an email notification preference, this would result in a breaking change.

Any thoughts on how we'd handle that case?

And for the values, those would make sense. Another option would be to use `15` and `60` to specify the batching interval, since we use numbers for `desktop_duration`. I'm not sure how "Immediately" and "Never" options would be represented as numbers though.

**Comment by vringar** [comment]
@jasonblais for numerical values how about 0 for "Immediately" and -1 for "Never"

**Comment by frahman5** [comment]
Hey @jasonblais is this update still wanted?

**Comment by jasonblais** [comment]
Hey @frahman5! It is indeed. Would you be interested tackling it?

**Comment by dos1701** [comment]
@jasonblais I would be interested in trying to fix this.

**Comment by dos1701** [comment]
Hey @jasonblais how about adding an optional field into the import jsonl with the email interval? to preserve backward compatibility of the original email field

**Comment by jasonblais** [comment]
@grundleborg or @jespino would you have thoughts on the above proposal?

**Comment by dos1701** [comment]
Hi guys,

please forgive any mistake since I'm a novice and if I'm missing something obvious, my proposal would be the following:
Add an optional field to the user json object called like email_interval.
The field will support the immediately, fifteen and hour strings, the import_types and import functions will be modified accordingly, so that we'll store the user preference as number of seconds.
This will preserve the backward compatibility.
I don't understand how i can then export that data using the bulk export command.
I might be missing something, but to me it seems the user export function is not querying the preference store at all, so it might be needed an export converter to do that.

Any thoughts? Suggestions?

**Comment by jespino** [comment]
@dos1701 The current "export" feature is under development yet. This ticket is for the "import" part, for test it you can use a "hand-made" export or for example, generate a `bulk.json` file with the `mattermost sampledata` command with the `-b` flag. And then modify the content of the `bulk.json`.

About the new email_interval, looks a good solution. Two small considerations:

1. When you disable email notifications the email interval will be 0.
2. "inmediately" will be 30 seconds.

**Comment by dos1701** [comment]
@jespino thanks for your reply!
The method you proposed to do the manual testing is actually the one I used while working on this issue, I'm sorry I thought I had to work also on the export part, so is it safe to leave it at that for now since it's in active development?

About your considerations, sorry, I'm starting for the second one:
I'm actually using: ```model.PREFERENCE_EMAIL_INTERVAL_NO_BATCHING_SECONDS```

I don't fully understand the first one though.
Why setting the interval to 0 if email notifications are disabled?
Is it to keep a consistent state/values or does it have a functional meaning? Is it needed by the UI?
Because i thought that with the emails disabled the checking made at line 171 in notifications.go:
```userAllowsEmails := profileMap[id].NotifyProps[model.EMAIL_NOTIFY_PROP] != "false"```
should suffice to effectively inhibit the batching part and therefore the preference.

Please let me know if I'm missing something!

**Comment by jespino** [comment]
You don't need to implement the export here, actually, I saw that you found the other Help Wanted ticket to do that and assign it to you :)

Yes that would be enough, but I would like to preserve the consistency with the current interface behavior, to avoid future subtle bugs.

**Comment by dos1701** [comment]
> You don't need to implement the export here, actually, I saw that you found the other Help Wanted ticket to do that and assign it to you :)

Yep! :) 

> Yes that would be enough, but I would like to preserve the consistency with the current interface behavior, to avoid future subtle bugs.

Fair enough, very well I'll submit the PR shortly for review.

Thank you!

**Comment by dos1701** [comment]
@jespino quick question:

I'd like to use the import validator, where should I put it? into the user.go file or preference.go? (or somewhere else)

**Comment by jespino** [comment]
If you want to write your own import validator, you simply add it to the `app/import_validators.go` if you want to validate during the import are normally used in the `app/import_functions.go`.

**Comment by dos1701** [comment]
Yep that’s what I did, but I saw that you have sone kind of generic validators like isvalidtrueorfalsestring ecc ecc

I want to create something like isvalidbulkemailinterval but I was thinking about the moat suitable location to put that function.

**Comment by jasonblais** [comment]
Thank you @dos1701!
