### ISSUE TITLE
[Help Wanted] [MM-10193] Words that trigger mentions does not support Chinese

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8642]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10193)

Original GitHub issue: https://github.com/mattermost/mattermost-server/issues/8590

**Summary**
If I set my first name to 萌, or other non-case sensitive words, such as 番茄
I cannot receive a mention notification, when I typed 萌 or 番茄

**Environment**
Version: 4.8.0
Database: mysql
Build Hash: d1ed79a
Build Date: Thu Mar 15 23:11:12 UTC 2018
EE Build Hash: 6f563c1fa497d123134fd499eb37674eb2511325
Webapp Build Hash: 1eaf6a845cec0fdb46df960bd1d387279f0ed62e

**Expected behavior**
I can receive a mention notification when content of message contains 萌 or 番茄

**Observed behavior**
I cannot receive mention notification when the content of message contains my custom words

**Comment by phuihock** [comment]
Given the keyword "番茄" (tomato) and the message is "番茄", mention works. But if the keyword is part of a sentence such as "我爱吃番茄炒饭" (I like tomato fried rice), mention is not sent. The reason is "我爱吃番茄炒饭" being treated as a single word, which obviously wouldn't match the keyword "番茄".

A possible fix is to allow substring match with keyword prefix `~`.

So in this example, we write `~番茄`.

https://github.com/phuihock/mattermost-server/commit/95069324cb51e3f716d6550cb8aff41ad5788ba6

**Comment by jasonblais** [comment]
Thanks @phuihock for the suggestion! Would a "wildcard" search work in this case, like `*番茄`?

**Comment by phuihock** [comment]
Yes it does. "Fix" is pushed to my repo here https://github.com/phuihock/mattermost-server/commit/95069324cb51e3f716d6550cb8aff41ad5788ba6

**Comment by phuihock** [comment]
This fix uses regex https://github.com/phuihock/mattermost-server/tree/MM-10193-use_regex. Works with English, Chinese or mix of both. Should work with other language too.

**Comment by jasonblais** [comment]
Thanks @phuihock! Would you like to open a pull request and we can review the code changes by PM and devs?

Really appreciate your help here!

**Comment by phuihock** [comment]
Sure, I'm glad to.

**Comment by kaakaa** [comment]
I can take this issue.

**Comment by kaakaa** [comment]
I suppose that my two PR is fixed this issue, but some problems about multibyte characters still be.

There are some characters that **doesn't trigger notification and highlight, but can be registered as trigger word**.

| Type of characters | Server (trigger notification) | Webapp (highlighed) |
|:----:|:----:|:----:|
| Ascii (except for symbols)       | YES | YES |
| Ascii symbols (e.g.: `(`, `[`])) | NO  | NO  |
| Multibyte Character1 (MC1) ※1       | YES | YES |
| Multibyte Character2 (MC2) ※2     | YES | NO  |
| Multibyte Character3 (MC3) ※3     | NO  | NO  |

* ※1: **MC1** represents CJK characters [declared in webapp](https://github.com/mattermost/mattermost-webapp/blob/master/utils/text_formatting.jsx#L26).
* ※2: **MC2** represents multibyte characters that is not CJK and ascii, but is recognized as letter in 
[server](https://github.com/mattermost/mattermost-server/blob/master/app/notification.go#L474)
  * i.e.:`unicode.IsLetter(c)` returns `true`
  * This kind of characters is less frequently used (e.g.: 𩸽)
* ※3: **MC3** represents multibyte characters that isn't CJK, ascii, and letter
  * i.e.:`unicode.IsLetter(c)` returns `false`
  * Emojis (e.g.: :sushi:, :beer:) are included in this type

Although users can register trigger words including ascii symbols, **MC2**, and **MC3**, triggering mention and highlighting don't work fine. But since it is less frequently used as trigger word, it might be not critical.

---

I think that it had better that only ascii and CJK characters can be registered as trigger word. However, since the implementation language differs between server and client, it's difficult to share usable (or unusable) character list. 
I hope that this problem is issued as a new ticket.

**Comment by hanzei** [comment]
Wow, thanks you very much for the analysis on this problem @kaakaa! :tada:

@jasonblais might have some insights on what would be good tickets to follow this up.

**Comment by jasonblais** [comment]
Thanks @kaakaa! @hmhealey pinging you instead here as you have more expertise in this area. Happy to create tickets from here afterwards.

**Comment by hmhealey** [comment]
This sounds awesome! Will this also require changes on the mobile app as well? It uses different code for highlighting, so it may need additional work

**Comment by kaakaa** [comment]
I didn't catch that. I'll take a look into it. Thanks!

**Comment by hmhealey** [comment]
Let me know if you run into any issues with it. The main place you'll probably want to look at is the [`getFirstMention`](https://github.com/mattermost/mattermost-mobile/blob/master/app/components/markdown/transform.js#L308) function that looks for a single mention in a string of text.

**Comment by kaakaa** [comment]
Thanks for your supporting @hmhealey! 
I've made PR for mobile. https://github.com/mattermost/mattermost-mobile/pull/2590

I think that this issue will be resolved by my existing PRs,  leaving [my comment](https://github.com/mattermost/mattermost-server/issues/8642#issuecomment-462214980).

**Comment by saturninoabril** [comment]
Thank you @kaakaa for this great contribution!

All PRs to server, webapp and mobile were all merged.  Closing this ticket.
