### ISSUE TITLE
Public link ignores "site url" from system console

### ISSUE THREAD

**Issue by jmesserli** [mattermost/mattermost-server#8739]
#### Summary
When getting the public link for an image, it seems that the site URL set in the system console is ignored.

Maybe related to [MM-5079](https://mattermost.atlassian.net/browse/MM-5079).

#### Steps to reproduce
1. Set up a mattermost instance behind a reverse proxy server (in my case Nginx).
2. Configure site URL correctly
3. Try to get an image's public url

`[User] --[https://someurl.public:443]--> [Nginx] --[http://localhost:3321]--> [Mattermost in Docker]`

Nginx config part with relevant headers: 
https://github.com/jmesserli/.files/blob/386d24bb83bb51688bf1ec7d507699f78458fce8/snippets/nginx/proxy.conf#L13-L21

Mattermost Version: 4.9.1
Database Schema Version: 4.9.0
Database: postgres

#### Expected behavior
A URL containing the configured site url is displayed (which is not localhost in this case).

#### Observed behavior (that appears unintentional)
A URL containing localhost is displayed:
![grafik](https://user-images.githubusercontent.com/613138/39701914-3f6ea4f0-5203-11e8-80c3-6a4d96c64ec8.png)

#### Possible fixes

API method for create public link (I think):
https://sourcegraph.com/github.com/mattermost/mattermost-server@09c67708853199c015d659ed2526107ad4c10772/-/blob/api4/file.go#L232

Link is created here:
https://sourcegraph.com/github.com/mattermost/mattermost-server@09c67708853199c015d659ed2526107ad4c10772/-/blob/app/file.go#L294

SiteURLHeader is set here:
https://sourcegraph.com/github.com/mattermost/mattermost-server@09c67708853199c015d659ed2526107ad4c10772/-/blob/api4/context.go#L112

**Comment by hmhealey** [comment]
Hi @jmesserli,

We made a choice to use the `Host` header for those URLs so that those links would match the URL in the address bar for deployments where Mattermost is accessible through multiple URLs. Looking at your config, it looks like that header isn't being properly passed through nginx, so you should add 
```
       proxy_set_header Host $http_host;
```
as per [this documentation](https://docs.mattermost.com/install/config-proxy-nginx.html).

You'll also want to take a look at that since you appear to be missing a section required for Mattermost's websocket connection to work correctly.

**Comment by jmesserli** [comment]
Thank you very much!

I missed the nginx config section when setting up the server. Everything seems to be working now.
