### ISSUE TITLE
Changing profile picture error

### ISSUE THREAD

**Issue by 3ter** [mattermost/mattermost-server#8742]
#### Summary
When trying to change the profile picture with certain JPEGs after hitting save the picture gets reset and is not changed.

#### Steps to reproduce
Mattermost Version: 4.8.0
Database: postgres

- Account Settings - General - Profile Picture
- Select e.g. [this picture](https://is1-ssl.mzstatic.com/image/thumb/Purple62/v4/d9/ab/39/d9ab3919-7ff7-8763-5cfc-4178eefb4d12/source/256x256bb.jpg) after downloading it
  - (Notice the picture changed to the new image)
- Hit Save

#### Expected behavior
- The picture is saved

#### Observed behavior (that appears unintentional) 
- The picture is replaced by the previous profile picture

**Comment by lindy65** [comment]
Hi @3ter 

This is fixed in v4.9 and you can download the latest server version [here](https://about.mattermost.com/download/#mattermostServer).

Just a note that there is currently a [bug](https://mattermost.atlassian.net/browse/MM-10494) where a white screen is shown after selecting a profile pic and a PR has been submitted for release with v4.10 on May 16th.

**Comment by 3ter** [comment]
Hi @lindy65,

thanks for the info! I couldn't find the appropriate issue for the fix so I opened this one.

**Comment by lindy65** [comment]
No worries @3ter :)
