### ISSUE TITLE
Status on GDPR compliance ?

### ISSUE THREAD

**Issue by rzr** [mattermost/mattermost-server#8820]
I am wondering if mattermost complies to current EU regulation regarding privacy, it yes this it would be nice to know how did you manage to, if not then it could make sense to align implementation with other FLOSS projects and converge into a common architecture/interface.

For reference:
https://www.eugdpr.org/eugdpr.org.html

**Comment by jasonblais** [comment]
Hi @rzr - great question. Mattermost is compliant with EU GDRP and we're working through the following:
 - ensure our documentation and privacy policy are up to date with GDPR 
 - publish a guide for Mattermost admins and/or the Data Protection Officer (DPO) reviewing the capabilities of Mattermost to support compliance with the EU GDPR
 - announce compliance with the community

**Comment by rzr** [comment]
Excellent keep us posted

**Comment by sokoow** [comment]
This is totally not true, Mattermost currently lacks following technical capabilities to fully support GDPR (unless I missed something):

- offloading users and their historical chats - need to do it manually at the DB level currently - this can be fixed by posting a guideline on how to do it properly at the DB level first (for example by replacing all user's chats with <deleted> as a simple solution ), until a proper UI based element of user deletion and offloading will be improved. Dropping records off the DB for offloaded users causes problems, we tried it ;)

So it's not looking like I'm only criticizing, here's what's done exceptionally well:

- keeping personal information - Mattermost's ORM keeps user related personal data in a single table called 'users' - all interconnection to other aspects of the system (channels and messages) is done on a per-hash relationship basis, which is very awesome. 

Keep doing the good work, you're system is amazing, - but fix the stuff that I mentioned please as we're getting first requests to offload users and it's a pain currently :/

**Comment by lfbrock** [comment]
@sokoow - when you say dropping records off the DB for offloaded users causes problems, was that using the [platform user delete CLI tool](https://docs.mattermost.com/administration/command-line-tools.html#platform-user-delete) or doing it manually?

**Comment by sokoow** [comment]
Ah, I totally missed that CLI option! :D We were doing it manually, and yes, managed to snooker things this way. Is the CLI way safe to use ? Are you planning to extend that option to GUI as well, like you did with disabling users (fair play) ?

**Comment by sokoow** [comment]
One more thing - upon closer system inspection, we noticed that there's another place where user generated data is being stored, it's the data directory, which holds pictures, avatars and attachments that users added to the system. Do you have any selective way to offload that content too - does platform delete command take care about this ?

**Comment by jasonblais** [comment]
@sokoow I don't think that command would affect your file storage / data directory. I have touched base with our engineers to confirm.

By the way @sokoow @rzr we have an overview of GDPR [here](https://docs.mattermost.com/overview/compliance.html) and a summary of all our license agreements, terms and privacy policy [here](https://docs.mattermost.com/overview/faq.html#what-are-mattermost-s-policies-around-licensing-terms-of-service-and-privacy)

**Comment by jasonblais** [comment]
The command doesn't delete content from the data directory.

However, all file uploads include a `CreatorId`, which can be used to delete all uploads for a given user. Avatars are stored in `data/users/<userid>/profile.png`

**Comment by sokoow** [comment]
Cool, that's useful information thank you.

**Comment by realrolfje** [comment]
Currntly, Mattermost provides tools to delete users and posts, and make sure proper passwords and encryption are in place. This is all great, and needed for GDPR, but some things are missing, also from your GDPR compliance statement.

As far as I understand, GDPR requires a website or service to:
1. Clearly specify what data is asked for and what it is used for (at time of registration), in a readable (non-legalese) form.
2. Ask for consent for usage of this data, and store that consent for later reference
3. Only ask for data which is absolutely needed for correct functioning of the service

I am struggling to collect this data from our users and manually process deletes/activations and cleanups. Are there plans to add these possibilities to Mattermost so that we can legally keep using it in Europe? Can we help?

**Comment by amyblais** [comment]
Hi @realrolfje - letting you know that I've reached out to our Product Managers regarding your questions and we'll get back to you soon.

**Comment by realrolfje** [comment]
Thanks! I noticed that my former post was not entirely clear about people who registered before the GDPR invocation date: Our existing, pre-registered users all need to receive an email with a link which explains the new terms, and contains a way to explicitly re-affirm their consent. If they do not approve, or explicitly decline, we need to remove their data. It would really help if Mattermost provided tools to easily facilitate this, particularly for installations with large user bases.

**Comment by jasonblais** [comment]
Thanks @realrolfje for your excellent question. And sorry for the extended delay.

1. With email/password login, we link to the terms of service and privacy policy on the account creation page, which can both be customized as a System Admin via System Console > Customization > Legal and Support. By proceeding, the user agrees to the terms and privacy policy. The user is also asked to enter their email address during the account creation process, which is the only personal information required for login.

![image](https://user-images.githubusercontent.com/13119842/42570546-39df190e-84e2-11e8-9350-f1cccec7f856.png)

2. Those using a non-email/password login, such as GitLab SSO, AD/LDAP or SAML SSO, may automatically pull first/last name, nickname and position from the service provider. This is configured by the System Administrator and we've assumed such permissions have previously been accepted by the user.

3. All of the above information is stored in the Users table of the database, to which admins have easy access to. You can delete user records via the CLI: https://docs.mattermost.com/administration/command-line-tools.html#mattermost-user-delete

Let us know if this helps, and if we can clarify any of the above?

Note that the personal data (in this case your email) isn't used for marketing purposes and no other personally identifiable data is collected. So this is different from other services like websites which can collect information via cookies.

**Comment by realrolfje** [comment]
Dear Jason, thanks for the answer but this does not answer my question and to my knowledge does not cover GDPR.

1. As I said in my former most, **our existing, pre-registered users all need to receive an email with a link which explains the new terms, and contains a way to explicitly re-affirm their consent**. Any installation of Mattermost needs to do this.
2. The current Mattermost privacy policy does not explain in non-legalese text what the provided personal data is used for, where it is sent, and how to request permanent deletion of any data in the database (the right to be forgotten).

The GDPR includes high fines (depending on the situation up to EUR 20 million or 4% of the annual global turnover, whichever is the highest) and generally aims to enhance the enforcement by national data protection authorities. Stricter enforcement is to be expected.

This can become (strictly spoken already is) a big deal for European Mattermost installations.

**Comment by DSchalla** [comment]
Hi @realrolfje,

1. Understood, cannot disagree with that one. You could write something yourself to do this, but I understand that's won't work for everyone. Also, from my understanding, only MM instances that are operated by a company need to do this, this is not applicable from my understanding to hobbist communities e.g. - What solutions you'd have in mind? Lock out all users, send them an email, they have to confirm on a webpage that they accept the privacy policy to enable them again?

2. The privacy policy link can be overwritten, since your companies privacy policy may of course be different than the default MM one. Additionally, the contact for the right to be forgotten needs to be customized anyway, so you'll want to change that link to an internal version most likely: [Privacy Policy Link Config](https://docs.mattermost.com/administration/config-settings.html#privacy-policy-link). Your version can then of course contain in non-legalese text what data is stored and how to request removal.

_Disclaimer: I am just a contributor, and not a lawyer._

**Comment by jasonblais** [comment]
Thank you for the open feedback! I'll do some more research on this and get back to you. We want to get it right as well.

> For new users I think we can make a case that they at least had the chance to read all that, and confirmed by clicking the link.

The privacy policy with full disclosure on account creation page was also there prior to GDPR being launched.

Also, another point is that the software doesn't collect, share or otherwise use personal information - except for the email address I suppose. 

With that said, we are working on the ability for users to deactivate themselves. It's almost finished and releasing soon. Although it's not a full delete, it would automatically stop sending email notifications for instance https://github.com/mattermost/mattermost-webapp/pull/1152

**Comment by realrolfje** [comment]
Hi Jason, not to be a pain, but I guess Mattermost does collect personal information, namely:

Not optional:
- username (in our case we require users to use their HAM radio callsign for instance)
- email address

Optional:
- Full Name
- Position (job or job title)
- Profile picture

Having said that, I did see a couple of mails from services I registered at (for free) which do not do the "disable account and re-register to enable" trick. They just sent out a mail to all users linking to the new GDPR privacy policy explaining their options. So maybe I'm overthinking this, but I am not a lawyer either. I'll try to see if I can find other info or help in my professional network.

**Comment by jasonblais** [comment]
@realrolfje @DSchalla I thought about this more, and I think Mattermost covers GDPR requirements (which are also documented [here](https://docs.mattermost.com/overview/compliance.html#gdpr-compliance))

1 - The privacy policy with full disclosure on account creation page was also there prior to GDPR being launched, and didn't change.

So the privacy policy someone agreed to in 2015 was the same as May 2018 when GDPR launched.

2 - The privacy policy can be customized by every system, which gives more control for every organization to update it as needed.

3 - The information collected (anonymous username, and email) isn't used for any marketing, advertisement or other promotional services. Same for the other information.

4 - Moreover, a user has the right to request their account and all related information to be deleted - which an admin can do [via the command line tool](https://docs.mattermost.com/administration/command-line-tools.html#mattermost-user-delete).

5 - - Finally, from my understanding, consent to the terms of service or privacy policy every 12 months is not required for GDPR.

The one thing that comes to mind is that when/if an admin updates the privacy policy, we offer a recommendation that they share those updates with all their users. An at-all in Town Square or another announcement channel with a link to the privacy policy should suffice.

Let me know what you think? Again, appreciate your thoughtfulness on this matter thus far.

**Comment by wiersgallak** [comment]
Closing issue as there have been no recent conversations or comments on Jason's last comment.
