### ISSUE TITLE
[Help Wanted] [MM-10658] Ensure a blank config file has all defaults set correctly

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#8841]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://docs.mattermost.com/guides/developer.html), specifically for [machine setup](https://docs.mattermost.com/developer/developer-setup.html) and for [developer workflow](https://docs.mattermost.com/developer/developer-flow.html).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-10658)

If you run Mattermost with an empty config.json (or possibly containing just `{}`), some settings aren't set to their correct defaults. Notably, logging is disabled (LogSettings.EnableConsole and LogSetting.EnableFile are both set to false) and email sign up is disabled (EmailSettings.EnableSignUpWithEmail is set to false).

This basically happens with any setting in model/config.go that isn't set to a pointer because they're automatically set to their zeroed value, so we can't tell if they're unset or just turned off.

To fix this, we should change all of those settings to use pointers and set their defaults accordingly similar to how newer settings are done

**Comment by chclaus** [comment]
Hej hej,

I'll take this one.

**Comment by chclaus** [comment]
Hi @esethna,

I hope you're all right. Before I get started, I wanted to make sure:
- Should **all** types of normal variables really change to pointers?
- Is it correct that the default value of a `nil bool` pointer should be `false`?
- Is it correct that the default value of a `nil string` pointer should be an empty string?

Just changing the variables to pointers will not change the behavior of values like `LogSettings.EnableConsole`. Should new (other) defaults be stored? If yes, could you please provide a list of all deviating variables and corresponding default values?

Thanks and best,
Christian

**Comment by jasonblais** [comment]
@hmhealey Would you be able to help on this one?

**Comment by hmhealey** [comment]
@chclaus All fields of the Settings structs in [`model/config.go`](https://github.com/mattermost/mattermost-server/blob/master/model/config.go) should be changed to pointers. Most of them already are, so we just need to go change the ones that aren't. For example, if you look at [the ServiceSettings struct](https://github.com/mattermost/mattermost-server/blob/master/model/config.go#L164), most of the fields have been changed over already. Using pointers lets us tell if a setting is unset instead of false/blank.

The defaults should match their values in [`config/default.json`](https://github.com/mattermost/mattermost-server/blob/master/config/default.json). This will usually be false or the empty string, but there's some cases where they should default to true like `LogSettings.EnableConsole`. This ticket is mostly to fix the cases where those defaults don't match what is set automatically by Go.

Let me know if you have any other questions. I'm always happy to help on either here or our community channels linked in the ticket.

**Comment by chclaus** [comment]
hej @hmhealey thanks. I think I got it :)

**Comment by chclaus** [comment]
Hej hej,

I solved this issue in #8898.

Best,
Christian

**Comment by hanzei** [comment]
Done for TE wth https://github.com/mattermost/mattermost-server/pull/8898
EE PR is https://github.com/mattermost/mattermost-server/pull/9033

Closing this one for now. Thanks you very much @chclaus!
