### ISSUE TITLE
github.com/tylerb/graceful --> gopkg.in/tylerb/graceful.v1

### ISSUE THREAD

**Issue by onlyjob** [mattermost/mattermost-server#8866]
Canonical import path for [tylerb/graceful](https://github.com/tylerb/graceful) is 
"`gopkg.in/tylerb/graceful.v1`". Please update incorrect import in

https://github.com/mattermost/mattermost-server/blob/master/cmd/mattermost/main.go#L25

**Comment by amyblais** [comment]
Hi @onlyjob! Thank you for reporting this.

I opened a PR here to fix this and it's currently under review: https://github.com/mattermost/mattermost-server/pull/8873.

**Comment by crspeller** [comment]
Considering that library is not even maintained anymore. I think our current import paths are fine.

**Comment by onlyjob** [comment]
:(  I suppose we'll just have to carry patch downstream in Debian...

**Comment by SmartHoneybee** [comment]
@onlyjob, looks like you're trying to package [Mattermost for Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823556) (awesome!) and this issue as well as the others you opened are related to this plan. (Which should fix #4176.)
(I'm not sure whether this is obvious to others. Hence, this message. :slightly_smiling_face:)

So, why modify the import path? (Guessing a bit. Feedback welcome.)
`tylerb/graceful` is already [packaged for Debian](https://packages.debian.org/source/stretch/golang-gopkg-tylerb-graceful.v1) but won't be used during build unless the canonical import path is used. Thus, one needs to patch Mattermost's sources for the Debian package. Not good, since maintaining (downstream) patches is work. Fixing the issue upstream (i.e. here) is preferred.

Regards,
Bee
