### ISSUE TITLE
log4go: unmaintained library

### ISSUE THREAD

**Issue by onlyjob** [mattermost/mattermost-server#8867]
Mattermost currently depends on [alecthomas/log4go](https://github.com/alecthomas/log4go) which is stated to be "_an unmaintained fork_". Indeed project had little activity in the last three years and, more importantly, have no bug tracker...

As I was searching for alternatives I've found https://github.com/ccpaging/log4go which appears to be actively maintained. Its issue management is also disabled but I've asked the author to enable it: https://github.com/ccpaging/nxlog4go/issues/1

Should we consider alternatives to original _log4go_ library?

**Comment by amyblais** [comment]
Hi @onlyjob! Thank you for reaching out.

Is this issue related to the other issues that you have opened (#8865, #8866, #8870)?

**Comment by onlyjob** [comment]
I don't see how this issue is related to any other issues that I've opened. Do they look related? What would have been different if they were related?

**Comment by hmhealey** [comment]
Hi @onlyjob,

We recently stopped using log4go in Mattermost 4.10 in favour of a combination of https://github.com/uber-go/zap and https://github.com/natefinch/lumberjack because of the same reasons you mentioned and because we wanted some additional features that log4go didn't have. The latest released version of Mattermost uses the new logging system

**Comment by onlyjob** [comment]
That's great. Thanks, @hmhealey. I would have noticed if I were checking latest release... :)

**Comment by onlyjob** [comment]
Already fixed in latest version 4.10.0; closing...
