### ISSUE TITLE
when user joins channel, channel window goes blank until manually refreshed

### ISSUE THREAD

**Issue by andyseubert** [mattermost/mattermost-server#8919]
#### Summary
Bug report in one concise sentence
when a user joins channel, channel window goes blank (the chat messages disappear) for existing members, until the window is manually refreshed, each user must refresh her own window to see the chat.

#### Steps to reproduce
version 4.10.0
Whenever someone is added to the channel it blanks for people using the Mac app, Windows app, and Windows browser clients. The one person using the browser version on a Mac didn't experience the blanking and Tyler testing using the Android app and it never blanked.

#### Expected behavior
We expect that when someone joins a channel, that the chat window would continue uninterrupted.

**Comment by amyblais** [comment]
Hi @andyseubert! Thank you for the report.

Here are some initial suggestions:

1. Would you have a short video to share from around the time the issue occurs?
2. Do you see any errors in logs, or can you help send us logs from around the time the issue occurs?

**Comment by amyblais** [comment]
Hi @andyseubert, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
