### ISSUE TITLE
Missing help image

### ISSUE THREAD

**Issue by kaakaa** [mattermost/mattermost-server#8923]
#### Summary
Missing image in help page
(`https://docs.mattermost.com/_images/slashCommandsTable1.PNG` is missing)

<img width="871" alt="2018-06-06 23 37 58" src="https://user-images.githubusercontent.com/1453749/41045305-1bb440f4-69e3-11e8-8925-7a27e83bdaf6.png">

#### Steps to reproduce
Open help page: https://pre-release.mattermost.com/help/commands

#### Expected behavior
Render image

#### Observed behavior (that appears unintentional) 
Render alt text

#### Possible fixes
Maybe this can be fixed by core team only.

**Comment by amyblais** [comment]
Hi @kaakaa! Thank you for reporting this.

It appears that the place to edit it is here: https://github.com/mattermost/mattermost-webapp/edit/master/components/help/components/commands.jsx

Instead of a png file, the slash command table is in a different format as seen here: https://github.com/mattermost/docs/edit/master/source/help/messaging/executing-commands.rst

I'll open a PR to fix this within the next few days.

**Comment by amyblais** [comment]
Apologies for the delay - I opened a PR here: https://github.com/mattermost/mattermost-webapp/pull/1318.

I'm not 100% sure of the formatting yet, but it'll be figured out.

**Comment by amyblais** [comment]
The PR has been merged, so I'll close this Issue for now - thanks for reporting this bug!
