### ISSUE TITLE
Snippet like Slack

### ISSUE THREAD

**Issue by eglyn** [mattermost/mattermost-server#9026]
Hi :)

We have a problem with code integration, we need to use the `` but, this symbol is not on our keyboard, we have to use alt +... 3 times, it's not pratical :/

Is there a solution to have the same button like Slack, the left of the input box, witch open a windows like that : 
![slack](https://user-images.githubusercontent.com/24936778/42084278-7f881630-7b8d-11e8-89c3-884df3281133.JPG)

Thx :)

**Comment by amyblais** [comment]
Hi @eglyn! Thank you for reaching out.

Can you help with more details on what Mattermost server version you are using, as well what OS and device you're on?

**Comment by eglyn** [comment]
Mattermost v5.0
OS server: debian 9
OS webapp: Windows 10

**Comment by amyblais** [comment]
Hi @eglyn! Thank you for the additional information 👍 

Looks like we don't support this feature yet and it would be a great feature request.  

It looks like some people have already [contributed this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/), would you like to help upvote the feature requests?

If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by amyblais** [comment]
Hi @eglyn, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
