### ISSUE TITLE
MM Domain in Shared URL

### ISSUE THREAD

**Issue by uhlhosting** [mattermost/mattermost-server#9163]
#### Summary
When a user using a web browser Chrome in our test, used an address in form https://klipie.com the matermost server will link it in some cases in the form: 
https://chat.uhlhosting.ch/klipie.com

#### Steps to reproduce
1 user webapp / chrome | 2 nd user mattermost app OSx 

#### Expected behavior
When a user paste or writes an address no one wait to have it routed in the same domain ie: 
https://chat.uhlhosting.ch/klipie.com

#### Observed behavior (that appears unintentional)
When using that URL users will get a simillar message:
**Team Not Found
The team you're requesting is private or does not exist. Please contact your Administrator for an invitation.

Back to UHL Hosting**

#### Possible fixes
Double check the http https wrappers around chat window.

**Comment by amyblais** [comment]
Hi @uhlhosting! What Mattermost server version are you using?

**Comment by uhlhosting** [comment]
Hi @amyblais 
We use Mattermost Version: 5.1.0

**Comment by amyblais** [comment]
Thank you!

It seems that I'm not able to reproduce this, would you be able to provide more detailed repro steps? I just want to make sure I'm not missing anything.

**Comment by amyblais** [comment]
Hi @uhlhosting, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
