### ISSUE TITLE
Windows app: flash app doesn't work

### ISSUE THREAD

**Issue by poshl9k** [mattermost/mattermost-server#9228]
#### Summary
Flash app window and taskbar icon when a new message is received
If enabled, app window and taskbar icon flash for a few seconds when a new message is received.
doesnt work

#### Steps to reproduce
Latest

#### Expected behavior
Icon must flash when receiving messages

**Comment by amyblais** [comment]
Hi @poshl9k, thanks for reporting this 👍 

I'll test this out today - can you also help with more details on your Mattermost server version, desktop app version, and Windows or Linux version?

**Comment by amyblais** [comment]
Hi @poshl9k - I'm not able to repro this, would you have any additional details on your Mattermost server version, desktop app version, and Windows or Linux version?

**Comment by amyblais** [comment]
Hi @poshl9k, we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
