### ISSUE TITLE
Scrolling issue on Android 9

### ISSUE THREAD

**Issue by gigabit101** [mattermost/mattermost-server#9268]
Scrolling down or up in the app quickly after the android 9 update causes a bouncing effect forcing you to scroll in the opposite direction.

**Comment by amyblais** [comment]
Hi @gigabit101, thank you for reaching out!

Unfortunately Android 9 is not fully supported with React Native yet, and there is an ongoing discussion about this bug in the RN repo that we are following: https://github.com/facebook/react-native/issues/19434.

Here is a Github Issue that was originally reported to us: https://github.com/mattermost/mattermost-mobile/issues/1672. A community member also posted a workaround while the bug is being investigated: https://github.com/mattermost/mattermost-mobile/issues/1672#issuecomment-411106702.

There is already an Issue open [here that you can follow](https://github.com/mattermost/mattermost-mobile/issues/1672) so I'll close this one,
