### ISSUE TITLE
Reaction emojis are not displayed when Mattermost is installed to a subpath

### ISSUE THREAD

**Issue by s1shed** [mattermost/mattermost-server#9289]
#### Summary
Reaction emojis do not respect the `Site URL` setting when Mattermost Server is installed within a subpath.

This was seen in v5.2.0. I suspect it's also a problem on v5.2.1 (I plan to upgrade later tonight).

#### Steps to reproduce

1. Make Mattemost server available within a subpath
2. Add a reaction to a post
3. See that the reaction emoji is empty

#### Expected behavior

The URL for the emoji should contain the subpath.. On my server the image path was `/static/emoji/1f60e.png` instead of `/installation_subpath/static/emoji/1f60e.png` .

**Comment by amyblais** [comment]
Hi @s1shed! Thank you for reaching out.

We have a few ticket open related to this, does one of them seem to describe the issue you are seeing:

 - https://mattermost.atlassian.net/browse/MM-11706
 - https://mattermost.atlassian.net/browse/MM-11704

**Comment by amyblais** [comment]
Hi @s1shed!

Both of the tickets I referenced above have been resolved. Fix for https://mattermost.atlassian.net/browse/MM-11704 is available on v5.3 release (which was released today) and a fix for https://mattermost.atlassian.net/browse/MM-11706 will be available on v5.4 release next month. Please upgrade and let us know if the issue is not resolved.
