### ISSUE TITLE
Change TPNS to https ?

### ISSUE THREAD

**Issue by arjitc** [mattermost/mattermost-server#9309]
#### Summary
The TPNS (Test Push Notification Service) set by default is http and not, https.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?)

5.2

#### Expected behavior

The TPNS is set to http:// while the URL when accessed has https available, https://push-test.mattermost.com

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.

The default configuration does not use https.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

Change default from http to https, ie, http://push-test.mattermost.com to https://push-test.mattermost.com

**Comment by jasonblais** [comment]
Thanks @arjitc and appreciate opening a discussion about it. There is some past conversations here if you're interested reading more: https://github.com/mattermost/mattermost-server/pull/5384

**Comment by lfbrock** [comment]
@arjitc - we have a ticket here to do this: https://mattermost.atlassian.net/browse/MM-11909

**Comment by lfbrock** [comment]
Thanks for the feedback @arjitc - that's good to know. It's something we've discussed in the past, but at the time I believe Enterprise Edition E10 was less expensive (due to less features), so we weren't sure what the demand would be like for only push notifications. 

Maybe it makes sense to consider again though, I'll bring it up with the team. In the mean time, @esethna can confirm but I think we should be switching the TPNS to use https soon.

**Comment by arjitc** [comment]
Sounds good -- would be quite good to have the encrypted push service @lfbrock 👍

**Comment by amyblais** [comment]
The Jira ticket has been resolved and tested internally, and the improvement will be available in v5.6 release (which will be released in December 16th). I'll close this Issue for now as the work for this has been completed.
