### ISSUE TITLE
Default MySQL schema is broken

### ISSUE THREAD

**Issue by Genda1ph** [mattermost/mattermost-server#9469]
#### Summary
Automatically created schema in MySQL doesn't allow application to load Users.

#### Steps to reproduce
I encountered this trying to migrate our existing Mattermost install (using Percona 5.5.45 and Mattermost 5.1.0) to our new server (running Percona 5.7.22 and same version of Mattermost). Here is how I encountered it:

1. Dump existing database with `mysqldump --no-create-info` (originally from version 4.0.0)
2. `rsync` Mattermost directory
3. Create empty database and start Mattermost server (5.1.0)
4. Stop the server and import previously created dump
5. Start server again
6. Try to log in or change password via CLI (`mattermost user password`)
7. Get "User not found" error

Hoping that this was fixed in more recent versions I upgraded to 5.3.1 but the default schema was still broken.
I can provide structure dumps for our original database (originally from 4.0.0, upgraded to 5.1.0) and blank, created by 5.3.1.

#### Expected behavior
Importing data from same version of Mattermost server should work with default empty database.

#### Observed behavior (that appears unintentional) 
Application fails to import Users from database.

#### Possible fixes
I was able to fix this by slightly changing structure for Users table and importing old data:
  - changed `Timezone` from `text` to `varchar(256) DEFAULT '{"automaticTimezone":"","manualTimezone":"","useAutomaticTimezone":"true"}'`
  - changed `MfaActive` from `tinyint(1) DEFAULT NULL` to `tinyint(1) DEFAULT 0`, since at some point I managed to make app throw an error complaining at that specific column

**Comment by amyblais** [comment]
Thank you for reporting this @Genda1ph, I'll ask our devs about this.

**Comment by Genda1ph** [comment]
We haven't switched to new server yet, and I haven't had the time to check all the functionality, so I suggest performing a more thorough testing of this issue.

**Comment by SmartHoneybee** [comment]
Hi @Genda1ph,

what exactly did you copy with `rsync` (and why)?
Why did you start Mattermost in step 3?

Regards,
Bee

**Comment by hmhealey** [comment]
I don't know much about how MySQL handles default values internally, but I assume the difference is due to how those are set when upgrading vs setting up from scratch. Like for the user.Timezone field
1. When upgrading to the first version that had that, that column is created with the type and default value created above. This seems like it might automatically migrate it for existing users without changing the value in the database.
2. When first setting up a server above that version, that column is created by gorp with a different type and no default value. Newly created users have their default set by Mattermost so the database default doesn't matter

The problem you're encountering appears to be because it's using new database tables (as in the second case), but you're importing old data. While our handling of the tables on upgrade vs a fresh install is a bit weird, you can probably fix the problems you're seeing by running `mysqldump` instead of `mysqldump --no-create-info` and then skipping step 3 so that the tables are created by the import and the state of the new database completely matches the old one.

**Comment by Genda1ph** [comment]
@SmartHoneybee 
I `rsync`'ed our 5.1.0 server with all its data (save for database) to the same path (`/opt/mattermost`) on the new server.
Originally, I installed Mattermost 4.0.0 on MySQL 5.5, way back, however it tried to create Fulltext indexes on InnoDB tables - which MySQL 5.5 doesn't support - I had to slightly change default schema created by Mattermost. Over the year we upgraded to 5.1.0 and during migration to new server I decided to allow 5.1.0 re-initialize the database structure so that I can import only data, reverting any changes I made to the database structure.

@hmhealey that's exactly what I wanted to avoid: originally I had to switch a number of tables from InnoDB to MyISAM, mostly due to use of Fulltext indexes, I might have changed something else - I can't remember, so to revert all of my changes to database structure I decided to use fresh database structure. Weirdly enough the only table I got warnings for was `Users` (for `MfaActive` column), everything else imported without issues.

Is there any way to validate existing database structure for consistency with what application expects?

**Comment by hmhealey** [comment]
Ah, I see. There's no feature like that, but that sounds like something that would be great to add. We've certainly had a lot of problems in the past that resulted from people modifying the database directly, and having a CLI command that can be run to verify the database and check for that would be really helpful. I'll bring that up for discussion with the team since it'd be useful for everyone.

The only other thing I think you could do to validate your existing setup though would be to try something like [this](https://stackoverflow.com/a/8718572) to compare the schemas of the two databases. There's also a `mysqldbcompare` utility that might be able to do that as well.

I've also filed a Jira ticket to look into the inconsistent schema created on a fresh install vs an upgrade as well. You can track it [here](https://mattermost.atlassian.net/browse/MM-12378) if you want.

**Comment by hmhealey** [comment]
Ah, I see. Well it's queued for our developer meeting on Wednesday, although I assume the discussion will basically be "yeah, let's create some tickets and do it".

That meeting is also public if you'd like to join in that discussion. We have it every Wednesday at 8:30 San Fransisco time, and the link is in the ~developers-meeting channel on https://pre-release.mattermost.com

**Comment by amyblais** [comment]
Closing this Issue as the Jira ticket has been resolved and tested internally. The fix will be available in v5.8 release.
