### ISSUE TITLE
[Help Wanted] [MM-12358] Create CLI command "command modify"

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9597]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12358)

Mattermost is improving its CLI interface and we're looking for contributors to help with that effort. This Help Wanted issue is to implement `command modify` command in the CLI.

Allow modifying slash commands.

Example: `command modify w16zb5tu3n1zkqo18goqry1je --title MyCommand --description "My Command Description" --trigger-word mycommand --url http://localhost:8000/my-slash-handler --creator myusername --response-username my-bot-username --icon http://localhost:8000/my-slash-handler-bot-icon.png --autocomplete --post`

Before you start, make sure you read this short [Documentation](https://developers.mattermost.com/contribute/server/cli-commands/)

If you need other examples you can see the PR mattermost/mattermost-server#9094

**Comment by crazcalm** [comment]
Do you mind if I try my hand at this?

**Comment by amyblais** [comment]
Thank you @crazcalm! Let us know any questions.

**Comment by crazcalm** [comment]
Few Questions:
- What is this modifying (Note: I have never used mattermost)
- Once I have the command line input, which function should I be evoking? Is there a "modify" function that I pass this stuff into?
- In the command example, "w16zb5tu3n1zkqo18goqry1je" looks like the ID for whatever I am modifying. When writing the test, how do I obtain the ID of whatever I just created so that I can pass it in to the modify command?
- Also, do you know of an existing command that take in an arg right after the command and before setting the flags like this one does? I would like to reference it and see how to properly handle the passed ID.

Thanks in advance!

**Comment by amyblais** [comment]
@jespino Can you help take a look at these questions ^

**Comment by waseem18** [comment]
I think I can help you with answering your questions so that you're not blocked.

1.  The `command` deals with slash commands of teams. `command modify` modifies an existing slash command.
2. As of now there's no `modify` method and as a part of this issue we would need to write one. You can take a look at similar methods in the file `command.go`.
3. While testing we would need to create a mock command and use it's `Id`. You can see how the mock data is generated and used in some of the test cases. Example : `team_test.go`

I'm not sure about the fourth one actually.

Thanks

**Comment by crazcalm** [comment]
@waseem18 Thanks for the info!

I have written the boilerplate for the command, and I know the answer to my previously asked 4th question (Extra args, not behind flags, will get passed into my Run function callback as args), but I am still really fuzzy on writing the function that does the actual modifying.

1. Given that an ID is being passed in, I need to be able to query for this ID and, if it exist, modify the properties associated with it. Can someone help me with the query?

2. I see the app.App is connected to an Elastic Search server. Is this ticket meant to update the passed in values in Elastic Search with reference to the ID that is given?

Again, thanks for the help!

**Comment by jespino** [comment]
1. For update the command, you will need to use the `UpdateCommand` function in the `app/command.go`, but for that, you need to get the current existing command, for that use the `GetCommand` in the same file.

2. You don't need to deal with Elastic Search at all in this task, the elastic search is used for the indexation of Posts mainly, so it's not related with this concrete task.

**Comment by crazcalm** [comment]
@jespino Something seems off. I believe I found the UpdateCommand and GetCommand methods that you were talking about, but the flags used in the example posted in this ticket and the properties of model.Command are not matching up (response-username & post are left out, and I am not sure if the other items are matched up properly).

Can you check my last commit to make sure I am on the right track?
Thanks!

**Comment by jespino** [comment]
Sorry, the response username is the `Username` field in the model, and is used to override the username who post the response. The `--post` flag, modifies the `Method` field. If you pass `--post` the Method field must be `P` or even better `model.COMMAND_METHOD_POST` if not it must be `G` or `model.COMMAND_METHOD_GET`.

**Comment by crazcalm** [comment]
@jespino Thanks! I think I have the mappings from input to model correct now. 

In terms of testing this, how should I go about it? Currently, there is no command_test.go file. Should I create one, or place the test in another location?

Also, the test should look something like the following (let me know if I am wrong and please advise on the 'Help please' lines):

    th := api4.Setup().InitSystemAdmin()  //  Which init method should I use? Help please
    defer th.TearDown()

     // Used to create the slash command. I do not know what should be passed in. Help please
    CheckCommand()

     // Get the ID from the previous command. I am not sure how to do this. Help please
    ID := th.Something.GetAll()[0] // I am hoping that only one command is in the list

    //  Create the variables that will be used in the modify command
    variable := value {repeat}

    //  Run the modify command. 
    CheckCommand()

    // Get the command by ID
    model, err := th.GetCommand(ID)

    // Then check that the returned model has everything that was passed in with the modify command
    if model.Property != property { t.Error("NOT EQUAL!!!!")}

I will flush it out a little bit more, but, generally speaking, that is what the body of the test function should look like, right?

**Comment by crazcalm** [comment]
@esethna @waseem18 Any thoughts about the questions mentioned in my last comment?

**Comment by crazcalm** [comment]
@waseem18 You answered the question of whether or not I should create a command_test.go file, but you missed the other questions I posted.

Two comments ago, I wrote out a skeleton of the test function I would write. I wrote that comment after looking at `team_test.go` and a couple of other test files. If you can, please review that post again.

In summary, some of the questions were:
- Which init method should I use? (I have seen at least 2 different methods used)
- How do I use `CheckCommand` to create a slash command? (If you can tell me what to pass in and what to expect afterwards, that would be great.)
- How do I get the ID of the slash command I just created? (As far as I can tell, `CheckCommand` does not return anything. I could be wrong, but, if I am correct, then I will need a way to obtain the ID from the slash command I created so that I can pass it into the modify command.)

If any of this logic is wrong, please let me know.

**Comment by amyblais** [comment]
Pinging @grundleborg / @mkraft for the questions above ^

**Comment by grundleborg** [comment]
@crazcalm since you started working on this ticket, a separate PR has created a `command_test.go` file to test a *different* CLI command. If you are unsure of the boilerplate of creating a test case, I would suggest taking a look at that.

For the `init` I would suggest you just use `th := api4.Setup().InitBasic().InitSystemAdmin()` as that will make both the `Basic*` and `SystemAdmin*` components of the test helper initialised so you can use them if you need them.

For `CheckCommand` usage, I suggest you look at the test case in `test_command.go` on latest master as an example. In that example you will also see the answer to your third question: you can list all commands on a team and look for the one with the matching trigger to identify it.

**Comment by crazcalm** [comment]
I am having trouble running the tests for this. It says I am missing the docker file executable that is suppose to be in my path.

@grundleborg Do you know where I can find this docker file? Also, I just noticed that I did not use `InitSystemAdmin()`. Sorry about that, I will change it now.

    {"level":"info","ts":1540589651.5986907,"caller":"sqlstore/supplier.go:209","msg":"Pinging SQL master database"}
    {"level":"error","ts":1540589651.602586,"caller":"sqlstore/supplier.go:221","msg":"Failed to ping DB retrying in 10 seconds err=dial tcp: lookup dockerhost: no such host"}
    {"level":"info","ts":1540589661.6029289,"caller":"sqlstore/supplier.go:209","msg":"Pinging SQL master database"}
    {"level":"error","ts":1540589661.6069012,"caller":"sqlstore/supplier.go:221","msg":"Failed to ping DB retrying in 10 seconds err=dial tcp: lookup
    dockerhost: no such host"}
    {"level":"info","ts":1540589671.6071632,"caller":"sqlstore/supplier.go:209","msg":"Pinging SQL master database"}
    {"level":"error","ts":1540589671.6108983,"caller":"sqlstore/supplier.go:217","msg":"Failed to ping DB, server will exit err=dial tcp: lookup dockerhost: no such host"}
    FAIL    github.com/mattermost/mattermost-server/cmd/mattermost/commands 171.346s
    ?       github.com/mattermost/mattermost-server/cmd/platform    [no test files]
    ?       github.com/mattermost/mattermost-server/einterfaces     [no test files]
    ?       github.com/mattermost/mattermost-server/einterfaces/jobs        [no test files]
    ?       github.com/mattermost/mattermost-server/imports [no test files]
    ?       github.com/mattermost/mattermost-server/jobs    [no test files]
    ?       github.com/mattermost/mattermost-server/jobs/interfaces [no test files]
    ?       github.com/mattermost/mattermost-server/manualtesting   [no test files]
    panic: exec: "docker": executable file not found in $PATH

**Comment by waseem18** [comment]
@crazcalm Wanted to make sure if you ran the first step from this documentation - https://developers.mattermost.com/contribute/server/developer-setup/ I presume that's what is causing issues.

**Comment by crazcalm** [comment]
@hanzei I'm sorry. I can't. I no longer have enough free time to work on this.

**Comment by hanzei** [comment]
Still, thank you very much for the time and effort you put into this @crazcalm!

**Comment by crazcalm** [comment]
@hanzei Thanks!

**Comment by akhilanandbv003** [comment]
Can I work on this?

**Comment by mkraft** [comment]
@akhilanandbv003 Yes please! Let me know if you have any questions.

**Comment by hanzei** [comment]
Hey @akhilanandbv003,

Can we help with anything? As allays, you can DM on the Community Server.

**Comment by akhilanandbv003** [comment]
@hanzei Hey! Sorry I was on vacation all these days. Will get back to working on this .

**Comment by akhilanandbv003** [comment]
wouldn't this require an id and the creator so that we verify the creator is modifying the command?
Something like `command modify w16zb5tu3n1zkqo18goqry1je --creator actualuser`
Or just `command modify w16zb5tu3n1zkqo18goqry1je`  is sufficient as MarkFlagRequired ?

**Comment by hanzei** [comment]
Just passing the command ID is fine. There are no authentication checks for the CLI.

**Comment by hanzei** [comment]
Hey @akhilanandbv003,

Can we help with anything? Are you still working on this one?

**Comment by joshuabezaleel** [comment]
Can I have a shot on this?

**Comment by akhilanandbv003** [comment]
@hanzei sorry for the delayed response. I had some personal stuff to take care of. I need write some tests. Hoping to put a PR by tomorrow. I will DM you for any doubts.

**Comment by hanzei** [comment]
Hey @akhilanandbv003,

How are you doing with this issue? Do you have any questions?

**Comment by akhilanandbv003** [comment]
Hello @hanzei . Sorry about the delay. Lately I have been really bogged down with other stuff. I think I won't be able to complete this story.Please don't mind.

**Comment by hanzei** [comment]
No problem @akhilanandbv003. Still, thank you very much for looking into this and the other contribution you did. :+1:

**Comment by JVasky** [comment]
Can I have a crack at it?

**Comment by hanzei** [comment]
Surely @JVasky, go ahead! :tada:

**Comment by JVasky** [comment]
@hanzei Can you help direct me to someone who can give me a little guidance on this issue? Just trying to iron a few things out in terms of testing and a technical clarification or two. Thanks!
