### ISSUE TITLE
[Help Wanted] [MM-12244] Add documentation to developers.mattermost.com on how to build and deploy a custom server

### ISSUE THREAD

**Issue by esethna** [mattermost/mattermost-server#9680]
If you're interested please comment here and come [join our "Contributors" community channel](https://pre-release.mattermost.com/core/channels/tickets) on our daily build server, where you can discuss questions with community members and the Mattermost core team. For technical advice or questions, please  [join our "Developers" community channel](https://pre-release.mattermost.com/core/channels/developers).

New contributors please see our [Developer's Guide](https://developers.mattermost.com/contribute/getting-started/).

----

**Notes**: [Jira ticket](https://mattermost.atlassian.net/browse/MM-12244)

The Mattermost developer documentation (on https://developers.mattermost.com) could use a section describing how to build and deploy a customized version of Mattermost. This can be added to the Contribute section and should document how to compile and deploy a customized server package after the server and web apps have been set up.

The code for this website is here: https://github.com/mattermost/mattermost-developer-documentation

**Comment by avasconcelos114** [comment]
Oh this sounds like something I've had some experience doing! 

Would be glad to contribute to this one :)

**Comment by avasconcelos114** [comment]
Just got a couple of questions so that I know I'm writing the right things:
1. Did you need information on how to build and deploy each client? (Webapp / Desktop / Mobile)
2. For the server, should I only mention custom `templates` and `i18n` files? (Which is about as much as I've ever done)
3. If you also want information on cases where some customization goes to the `mattermost-server` project's code, I imagine this sort of customization is only applicable for team edition correct? (as in, it's impossible to have a custom enterprise version of the server code)

If the scope of the second one is limited to only `templates` and `i18n` files then feel free to ignore that last question

**Comment by hanzei** [comment]
@avasconcelos114 Did @hmhealey help you? Do you have any other questions?

**Comment by avasconcelos114** [comment]
Ah yes, I'm sorry I haven't been following up on this.

I had run into one thing that needed clearing up since I've only done the customizing of templates/i18n files and individual clients without recompiling a whole new server.

When downloading installation tarballs from the Mattermost website, the `mattermost` directory usually comes with its many components built-in (client, config, templates, i18n, etc). 

But if I'm using the `Makefile`'s `build-linux` command (for example), it seems that the output I get are the binaries `platform` and `mattermost`, so the question here is: 

Would it be correct to instruct people to get a tarball from the [download page](http://about.mattermost.com/download) and replace the `platform` and `mattermost` files with their own compiled counterparts?

**Comment by hanzei** [comment]
You can just use `make package` to bundle up all needed files. But you need to run `make build`, or `make build-linux` if you are building for a specific OS, first.

**Comment by tankerkiller125** [comment]
I'm not 100% certain if this should be a separate issue of if this is related to this question however I feel that it fits here if it does not please let me know and I'll make a separate issue for it.

Is there any documentation/possibility for developers to compile an "enterprise-ready" edition of the source code. So far I've tried setting the environment variables listed in the makefile with no success. The reason I ask is that I'm looking at modifying some of the code and it seems that the license keeps getting removed from the application every hour or so when I'm using my self-compiled copy. Is there something I'm missing?

**Comment by hanzei** [comment]
Fixed with https://github.com/mattermost/mattermost-developer-documentation/pull/210
