### ISSUE TITLE
Don't highlight room if thread panel opened

### ISSUE THREAD

**Issue by Ppjet6** [mattermost/mattermost-server#9875]
#### Summary

Channel in channel list gets displayed as if there were unread messages even though these messages get into a thread I currently have opened.

#### Steps to reproduce
- Join channelA, start a thread threadA (right panel opens)
- Change to channelB but keep threadA opened
- Wait that somebody sends a message in threadA

#### Expected behavior
Message is displayed in the thread, that's it.

#### Observed behavior (that appears unintentional)
Message is displayed in the thread, and the channel is displayed as if there were unread messages.

Maybe it's just that the unread message rules are not entirely clear?
Still, having to reopen channelA to clear unread messages is annoying.

This of course wouldn't apply if somebody sent messages to channelA that weren't in threadA.

**Comment by amyblais** [comment]
Hi @Ppjet6,

I opened a ticket for our UX team to determine whether this behaviour should be changed: https://mattermost.atlassian.net/browse/MM-13156.

**Comment by amyblais** [comment]
The Jira ticket was closed with this note:

"This is a lot more complicated than it sounds and likely requires an entire re-architecting of how we do unread messages. This has been in the product since day 1, so I'm going to close as won't fix as it clearly isn't a priority issue or worth the mana yet."

I'll close this Issue for now until we decide to revisit this,

**Comment by amyblais** [comment]
Reopening this as another dev team reopened the above the ticket for future consideration.

**Comment by amyblais** [comment]
Closing as this has been submitted for upcoming v5.14 release: https://mattermost.atlassian.net/browse/MM-4989.
