### ISSUE TITLE
Unable to create Test account for mattermost

### ISSUE THREAD

**Issue by bullsseye** [mattermost/mattermost-server#9925]
I am not able to create an account for my mattermost developer setup on my machine. I am successful in setting up everything else.

When I run this command:go build -o mattermost && ./mattermost user create --email <email> --username <username> --password <password>

I get the following error:
can't load package: package github.com/mattermost: no Go files in /Users/Raman/go/src/github.com/mattermost/

I tried the above command at various other levels of directory like inside mattermost-server, github.com etc.

**Comment by hanzei** [comment]
Hey @bullsseye 
The main file for Mattermost in located in `cmd/mattermost`. Hence you should run `go run cmd/mattermost/main.go user create --email --username --password`.

Hope this helps.

**Comment by amyblais** [comment]
Hi @bullsseye, did Hanzei's suggestion help?

**Comment by amyblais** [comment]
Hi @bullsseye , we haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
